// Generated by tools/build_border_art.py; edit art/event-scenes.js.
// Code-native League performances, compiled into the existing static delivery route.
// Detection, admission, clocks and saved presentation data remain with their owners.
import {WorldPaint,smooth,TAU,pathOf} from './subtle.js';
// Local material and path tools. Event owners supply all subjects and staging.
function eventInk(c,e){
 const w=new WorldPaint(c),o=w.o,t=e.elapsed||0,finite=Number.isFinite(e.duration),p=finite?Math.max(0,Math.min(1,t/Math.max(.1,e.duration))):.4;
 const line=(pts,color,width=1,alpha=.7)=>w.beam(pts,color,width,alpha);
 const poly=(pts,fill,alpha=1)=>{c.save();c.globalAlpha*=alpha;c.fillStyle=fill;c.beginPath();pts.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.fill();c.restore();};
 const metal=(axis,colors)=>{const g=c.createLinearGradient(...axis);colors.forEach((color,i)=>g.addColorStop(i/(colors.length-1),color));return g;};
 const place=(x,y,s,angle,draw,delay=0)=>{const arrive=finite?smooth((p-delay)/.15):smooth(t/1.2);c.save();c.globalAlpha*=arrive;c.translate(x,y+(1-arrive)*12);c.rotate(angle);c.scale(s,s);draw();c.restore();};
 const arc=(x,y,rx,ry,a=0,b=TAU)=>u=>[x+Math.cos(a+u*(b-a))*rx,y+Math.sin(a+u*(b-a))*ry];
 const wake=(path,color,delay=0,width=2,tail=.22,rate=.16)=>{w.line(path,color,.7,.27);w.light(path,finite?p*1.3-delay:(t*rate-delay)%1.4,color,width,tail,.95);};
 const shard=(x,y,size,color,angle=0,glass=true)=>o.shard(x,y,size,color,finite?p:t*.08,angle,glass);
 const ring=(x,y,rx,ry,color,width=1,alpha=.7,turn=0)=>o.arc(x,y,rx,ry,0,TAU,color,width,alpha,turn);
 // Absolute particle births make long-lived atmosphere develop without resets.
 const motes=(count,lifetime,spacing,draw)=>{const last=Math.floor(t/spacing);for(let serial=Math.max(0,last-count+1);serial<=last;serial++){const age=t-serial*spacing;if(age<0||age>lifetime)continue;const seed=((serial*2654435761)>>>0)/4294967296;draw(age/lifetime,serial,seed,Math.sin(age/lifetime*Math.PI));}};
 return {c,w,o,t,p,finite,line,poly,metal,place,arc,wake,shard,ring,motes};
}

// Reusable subject silhouettes. Composition, acting and event meaning stay local.
function eventProps(ink){
 const {o,t,p,line,poly,metal,place,shard,ring}=ink,gold='#e7cb94',ice='#c4eaf2';
 const blade=(x,y,s,turn,color=ice,delay=0)=>place(x,y,s,turn,()=>{
  poly([[-7,18],[-10,-79],[0,-112],[10,-79],[7,18]],metal([-10,-112,10,18],['#e5eff0','#829ab5','#e8e9c9','#435b7c']),.95);line([[0,-104],[0,10]],color,1.7,.8);poly([[-28,20],[-28,13],[28,13],[28,20],[10,23],[-10,23]],metal([-28,13,28,23],['#e8cd91','#526e88','#cbb888']),.94);poly([[-7,24],[7,24],[7,56],[-7,56]],'#53647c',.94);for(let j=0;j<4;j++)line([[-7,27+j*7],[7,30+j*7]],gold,1,.7);shard(0,65,9,color,.05,false);
 },delay);
 const shield=(x,y,s,turn,color=ice,delay=0)=>place(x,y,s,turn,()=>{
  poly([[-32,-35],[0,-49],[32,-35],[27,14],[0,43],[-27,14]],metal([-32,-49,32,43],['#d8dec5','#4e718c','#b7c3d7','#354f72']),.92);poly([[-22,-28],[0,-37],[22,-28],[19,9],[0,29],[-19,9]],color,.18);line([[-24,-27],[0,-38],[24,-27]],gold,1.3,.8);line([[0,-34],[0,25]],color,1.4,.8);shard(0,-4,12,color,0);
 },delay);
 const coin=(x,y,s,turn=0,delay=0)=>place(x,y,s,turn,()=>{o.orb(0,0,14,gold,t*.4,{flat:.86});ring(0,0,10,11,'#fae6b7',1,.85);line([[-4,-6],[4,-6],[-3,6],[4,6]],'#8b8067',1.5,.8);line([[0,-8],[0,8]],ice,.7,.6);},delay);
 const heart=(x,y,s,turn,color,delay=0)=>place(x,y,s,turn,()=>{poly([[0,35],[-34,3],[-35,-15],[-21,-28],[-7,-24],[0,-14],[7,-24],[21,-28],[35,-15],[34,3]],metal([-35,-28,35,35],['#e2c8d3',color,'#867d9e','#3e5279']),.89);line([[-26,-11],[-18,-19],[-9,-15]],ice,1.2,.82);line([[0,-8],[0,26]],color,1,.6);},delay);
 const helmet=(x,y,s,turn,color,delay=0)=>place(x,y,s,turn,()=>{poly([[-25,23],[-28,-15],[-18,-36],[0,-43],[21,-33],[29,-9],[23,26],[8,30],[0,13],[-8,30]],metal([-28,-43,29,30],['#d7ddce','#66829b','#b6becf','#425d7b']),.94);poly([[-20,-11],[-3,-7],[-6,3],[-20,-1]],'#233f55',.9);poly([[3,-7],[20,-11],[20,-1],[6,3]],'#233f55',.9);line([[-20,-11],[-3,-7]],color,1.2,.8);line([[3,-7],[20,-11]],color,1.2,.8);line([[0,-37],[0,6]],gold,2,.8);shard(0,-43,9,color,.1);},delay);
 const glove=(x,y,s,turn,color,delay=0)=>place(x,y,s,turn,()=>{poly([[-34,27],[-35,-6],[-27,-29],[-16,-32],[-11,-17],[-5,-36],[5,-36],[10,-17],[18,-30],[27,-25],[25,0],[39,-9],[46,-1],[28,31],[3,40]],metal([-35,-36,46,40],['#d9caae','#5b7a92',color,'#3f5777']),.92);line([[-27,-29],[-16,-32],[-11,-17]],ice,1.2,.75);line([[-24,21],[2,29],[28,20]],gold,1.2,.7);},delay);
 const book=(x,y,s,turn,color,delay=0)=>place(x,y,s,turn,()=>{poly([[-43,-28],[-21,-34],[0,-22],[21,-34],[43,-28],[41,28],[21,23],[0,37],[-21,23],[-41,28]],metal([-43,-34,43,37],['#e5d7b6','#aeb1ae','#e0d6c6','#778a9c']),.88);line([[0,-22],[0,33]],gold,1.6,.8);for(let j=0;j<5;j++){line([[-34,-17+j*8],[-19,-21+j*8],[-7,-15+j*8]],color,1,.6);line([[7,-15+j*8],[19,-21+j*8],[34,-17+j*8]],color,1,.6);}},delay);
 const vial=(x,y,s,turn,color,delay=0)=>place(x,y,s,turn,()=>{poly([[-17,-19],[-9,-25],[-9,-45],[9,-45],[9,-25],[17,-19],[21,30],[-21,30]],'#c4e4e428',.85);line([[-17,-19],[-21,30],[21,30],[17,-19],[9,-25],[9,-45],[-9,-45],[-9,-25],[-17,-19]],ice,1.2,.8);poly([[-18,8+Math.sin(t*1.8)*3],[18,8-Math.sin(t*1.8)*3],[19,28],[-19,28]],color,.47);line([[-12,-15],[-15,23]],ice,1,.65);line([[-12,-44],[12,-44]],gold,4,.85);ring(0,3,2,3,color,1,.7);},delay);
 return {blade,shield,coin,heart,helmet,glove,book,vial};
}

// Six separate elemental worlds. Hextech retains its approved renderer.
function elementalPerformance(c,e){
 if(!['dragon_earth','dragon_fire','dragon_water','dragon_air','dragon_chemtech','dragon_elder'].includes(e.key))return false;
 const {w,o,t,p,finite,line,poly,metal,place,arc,wake,shard,ring,motes}=eventInk(c,e);
 const gold='#e9c788',ice='#c8f7ff';
 c.save();
 if(e.key==='dragon_earth'){
  // A mineral dragon rises from layered stone; geological seams grow light.
  const a='#dec18a',teal='#91d9c1';
  for(const side of [0,1])for(let j=0;j<(side?6:10);j++){const y=205+j*52,x=side?1912:8,sgn=side?-1:1;
   place(x,y,1,Math.sin(t*.22+j)*.018,()=>{poly([[0,-25],[sgn*36,-33],[sgn*72,-13],[sgn*58,18],[sgn*26,29],[0,19]],metal([0,-33,sgn*72,29],['#7b8177','#b4ae8b','#364b4b','#82796a']),.88);line([[sgn*8,-8],[sgn*33,-18],[sgn*53,-10]],a,1.1,.75);line([[sgn*33,-18],[sgn*30,10],[sgn*16,22]],teal,1,.55);},j*.013);
   wake(u=>[x+sgn*(9+u*52),y-6-Math.sin(u*4)*8],j%2?a:teal,j*.035,1.7,.38);
  }
  place(91,469,1.05,-.11,()=>{
   poly([[-52,19],[-42,-51],[-16,-92],[-3,-57],[29,-73],[20,-29],[48,-7],[31,15],[1,28],[-9,52]],metal([-50,-85,45,48],['#c9c8b0','#616b63','#a4a983','#2d484d']));
   poly([[-36,-35],[-19,-51],[6,-36],[-6,-18]],'#8b9b80',.72);line([[-49,15],[-22,-8],[4,-20],[20,-9],[36,-7]],gold,1.6);line([[1,28],[17,22],[31,15]],teal,1.2);o.orb(11,-13,5,teal,t*.5);shard(-31,-53,17,teal,.2);line([[-14,8],[18,9]],'#1a3438',3);
  },.04);
  for(let j=0;j<17;j++){const x=340+j*76;shard(x,1058-Math.sin(t*.4+j)*5,9+j%3*3,j%3?teal:gold,j*.31);}
  for(let j=0;j<3;j++)wake(pathOf([[310,32+j*9],[540,32+j*9],[605,67+j*9],[1090,67+j*9],[1160,29+j*9],[1590,29+j*9]]),j%2?teal:a,j*.13,1.8,.24);
  w.mist(54,462,90,177,teal,.35);motes(30,5,.1,(u,j,r,a)=>w.mote(j%2?1885+Math.sin(j)*21:51+Math.sin(j)*31,800-u*580,1+r*2,teal,a*.7));
 }else if(e.key==='dragon_fire'){
  // Obsidian claws and an ember dragon; molten filaments unfurl in the margins.
  const amber='#ffb67c',red='#e77e88';
  for(const [x,y,s,a]of [[1840,359,1.2,.1],[56,634,.8,-.3],[1430,47,.53,1.3]])place(x,y,s,a,()=>{
   poly([[-51,31],[-39,-14],[-29,-70],[-9,-41],[8,-80],[21,-37],[46,-15],[35,5],[59,22],[23,40]],metal([-51,-70,51,40],['#b98e83','#372e42','#926471','#212b3c']),.94);
   line([[-29,-70],[-22,-21],[-39,7]],amber,1.8);line([[8,-80],[9,-34],[24,-19],[35,5]],red,1.4);poly([[14,1],[29,0],[22,8]],amber);line([[23,40],[32,21],[59,22]],gold,1.2);shard(-17,4,20,red,-.18);
  });
  for(let j=0;j<6;j++){const side=j%2,x=side?1894-j*5:25+j*6,sgn=side?-1:1;
   o.ribbon(u=>[x+sgn*Math.sin(u*8-t*.8+j)*23,998-u*810],{width:11+j%3*3,color:amber,secondary:red,phase:t*.65+j,glass:true,alpha:.48});
   wake(u=>[x+sgn*Math.sin(u*8-t*.8+j)*23,998-u*810],j%2?red:amber,j*.08,2,.27);
  }
  for(let j=0;j<18;j++){const x=340+j*71;poly([[x,1080],[x+21,1048],[x+44,1080]],metal([x,1048,x+43,1080],['#775970','#ba8e76','#3c3546']),.62);wake(u=>[x+4+u*20,1079-u*22],amber,j*.027,1.5,.55);}
  for(let j=0;j<3;j++)wake(u=>[300+u*1290,28+j*14+Math.sin(u*14-t*.4+j)*7],j===1?red:amber,j*.17,2,.17);
  motes(44,4.8,.065,(u,j,r,a)=>{const x=j%2?1883+Math.sin(j+u*3)*32:47+Math.sin(j+u*4)*35,y=970-u*810;w.star(x,y,2+r*3,amber,a*.72);});w.mist(1867,394,90,184,red,.38);
 }else if(e.key==='dragon_water'){
  // Ocean glass: a coiled sea-dragon, suspended droplets and tidal lenses.
  const aqua='#92e9cf',blue='#86bee6';
  place(72,461,1,0,()=>{
   o.ribbon(u=>[Math.sin(u*8+t*.25)*40,96-u*179],{width:34,color:aqua,secondary:blue,phase:t*.3,glass:true,alpha:.77});
   poly([[-26,-72],[-23,-98],[0,-111],[15,-143],[17,-104],[39,-83],[27,-65],[0,-69]],metal([-26,-143,39,-65],['#c2f1e3','#438b9a','#96cecd','#2e4d68']),.85);poly([[7,-91],[20,-87],[10,-84]],ice,.9);line([[17,-104],[28,-94],[39,-83]],gold,1);for(let j=0;j<6;j++)ring(Math.sin(j*.8+t*.25)*31,72-j*27,7,3,ice,1,.5);
  });
  for(let j=0;j<7;j++){const y=196+j*73;place(1870+Math.sin(j+t*.35)*8,y,1,Math.sin(t*.3+j)*.04,()=>{o.orb(0,0,21+j%3*5,aqua,t*.4+j,{glass:true,flat:1.15});ring(0,0,34,13,blue,1,.6);line([[-13,-10],[-8,-17],[2,-18]],ice,1.1,.75);},j*.019);}
  for(let j=0;j<6;j++)o.ribbon(u=>[320+u*1240,1054+Math.sin(u*12-t*.7+j*.5)*8-j*3],{width:7,color:j%2?blue:aqua,secondary:ice,phase:t*.5+j,glass:true,alpha:.42});
  for(let j=0;j<4;j++)wake(u=>[310+u*1320,30+j*13+Math.sin(u*8-t*.6+j*.24)*10],j%2?aqua:blue,j*.16,1.8,.24);
  motes(34,5.5,.11,(u,j,r,a)=>{const x=j%2?1850+Math.sin(j)*30:61+Math.sin(j)*29;ring(x,900-u*711,3+r*7,4+r*9,aqua,1,a*.7);});w.mist(40,495,94,220,blue,.25);
 }else if(e.key==='dragon_air'){
  // A wind dragon made of vanes and feathers; silk streamers lift independently.
  const pearl='#d0e6e0',lavender='#b6b2e3';
  place(1831,391,1.2,.12+Math.sin(t*.5)*.04,()=>{
   for(let j=0;j<8;j++){const x=-17+j*5,y=48-j*14;o.ribbon(u=>[x-u*(27+j*5),y+u*32+Math.sin(u*4+t*.5)*4],{width:12,color:pearl,secondary:lavender,phase:t*.3+j,glass:true,alpha:.7});}
   poly([[-8,10],[-20,-27],[-8,-72],[2,-105],[9,-68],[32,-56],[42,-32],[22,-14]],metal([-20,-105,42,10],['#e0e8db','#748798','#bec6dc','#4e6981']),.84);line([[2,-105],[7,-67],[32,-56]],gold,1);poly([[16,-43],[26,-39],[19,-36]],ice);line([[42,-32],[30,-24],[22,-14]],lavender,1.4);
  });
  for(let j=0;j<5;j++){const y=207+j*110;o.ribbon(u=>[28+Math.sin(u*6-t*.7+j)*24,y+u*102],{width:13+j*2,color:pearl,secondary:lavender,phase:t*.5+j,glass:true,alpha:.46});wake(u=>[28+Math.sin(u*6-t*.7+j)*24,y+u*102],pearl,j*.11,1.5,.27);}
  for(let j=0;j<22;j++){const x=342+j*55,y=29+Math.sin(j*.5+t*.5)*14;w.petal(x,y,9+j%4,pearl,-.3+Math.sin(t*.4+j)*.15,.66);if(j%3===0)wake(u=>[x-24+u*48,y+Math.sin(u*Math.PI)*9],lavender,j*.023,1.4,.35);}
  for(let j=0;j<3;j++)wake(u=>[1580-u*1260,1060-j*9+Math.sin(u*9-t*.4+j)*6],j%2?lavender:pearl,j*.17,1.8,.36);
  motes(35,4.8,.1,(u,j,r,a)=>w.petal(j%2?1872+Math.sin(j+u*6)*24:58+Math.sin(j+u*5)*27,873-u*690,5+r*8,pearl,j*.31+u*1.4,a*.66));
 }else if(e.key==='dragon_chemtech'){
  // Botanical laboratory: segmented glass dragon, living vines and pressure vials.
  const acid='#d5eb8b',mint='#8bdfb8';
  place(84,436,1.1,-.12,()=>{
   for(let j=0;j<7;j++){const y=64-j*20,x=Math.sin(j*.7+t*.25)*17;shard(x,y,18,j%2?acid:mint,.1+j*.04);ring(x,y,23,6,gold,1,.62);}
   poly([[-22,-67],[-9,-93],[-10,-127],[6,-105],[24,-83],[42,-72],[24,-57],[2,-60]],metal([-22,-127,42,-57],['#d4e5a3','#5c897c','#adcfa2','#375f68']),.8);poly([[12,-80],[25,-77],[16,-72]],acid);line([[-10,-127],[6,-105],[24,-83]],gold,1.3);
  });
  for(let j=0;j<5;j++){const y=208+j*101;place(1858,y,.86,Math.sin(t*.35+j)*.045,()=>{
   poly([[-19,-35],[-10,-41],[-10,-59],[10,-59],[10,-41],[19,-35],[24,32],[-24,32]],'#75afa925',.85);line([[-19,-35],[-24,32],[24,32],[19,-35],[10,-41],[10,-59],[-10,-59],[-10,-41],[-19,-35]],mint,1.2,.8);poly([[-21,16+Math.sin(t*1.7+j)*4],[21,13+Math.sin(t*1.7+j)*4],[23,30],[-23,30]],acid,.37);line([[-16,-28],[-16,20]],ice,1,.64);line([[-14,-57],[14,-57]],gold,4,.75);for(let b=0;b<3;b++)ring(-9+b*9,12-(t*12+b*17)%41,2+b,2+b,acid,1,.6);
  },j*.019);}
  for(const side of [0,1]){const x=side?1904:18,sgn=side?-1:1;const stem=u=>[x+sgn*Math.sin(u*12-t*.3)*17,820-u*650];wake(stem,mint,side*.18,2,.24);for(let j=0;j<12;j++){const [xx,y]=stem(j/12);w.petal(xx+sgn*12,y,12,acid,sgn*-.8+Math.sin(t*.6+j)*.08,.55);}}
  for(let j=0;j<12;j++){const x=380+j*102;ring(x,48,17,9,mint,1,.5);shard(x,48,8,acid,j*.3);if(j<11)wake(u=>[x+17+u*68,48+Math.sin(u*Math.PI)*10],acid,j*.03,1.5,.35);}
  motes(28,4.5,.12,(u,j,r,a)=>ring(j%2?1878:46,1000-u*815,3+r*5,3+r*5,acid,1,a*.55));w.mist(64,426,92,184,mint,.25);
 }else{
  // Elder: silver skeletal dragon wing with ancient rings and soul wisps.
  const silver='#d3d8f2',blue='#92cde6';
  place(75,455,1,-.08,()=>{
   for(let j=0;j<7;j++){const path=u=>[-24+u*(92-j*7),-89+j*25+Math.sin(u*Math.PI)*(27+j*2)];o.ribbon(path,{width:8,color:silver,secondary:gold,phase:t*.15+j,glass:false,alpha:.79});wake(path,blue,j*.07,1.7,.23);}
   poly([[-37,5],[-30,-79],[-12,-105],[1,-151],[6,-94],[21,-77],[39,-52],[29,-38],[4,-43],[-5,12]],metal([-37,-145,39,12],['#e7e2cf','#647b94','#c3d0d6','#334a68']),.9);line([[1,-151],[6,-94],[21,-77],[39,-52]],gold,1.1);poly([[8,-70],[23,-62],[12,-58]],blue);for(let j=0;j<4;j++)line([[0,-36+j*11],[23-j*3,-30+j*11]],silver,1,.75);
  });
  for(let j=0;j<6;j++){const y=211+j*83;place(1876,y,1,-.2+Math.sin(t*.3+j)*.05,()=>{w.petal(0,0,31,silver,-.8,.8);line([[-23,16],[23,-16]],gold,1,.6);for(let n=0;n<5;n++)line([[-9+n*6,9-n*4],[-3+n*6,19-n*4]],blue,.7,.6);},j*.02);}
  for(let j=0;j<15;j++){const x=360+j*84;ring(x,42,15,23,silver,1,.56);wake(arc(x,42,15,23),gold,j*.025,1.6,.24);shard(x,42,7,blue,.3);}
  for(let j=0;j<4;j++)o.ribbon(u=>[300+u*1290,1066-j*6+Math.sin(u*7-t*.3+j)*8],{width:6,color:silver,secondary:blue,phase:t*.2+j,glass:true,alpha:.43});
  motes(36,6,.11,(u,j,r,a)=>{const x=j%2?1865+Math.sin(j+u*8)*24:49+Math.sin(j+u*6)*28,y=1000-u*816;w.mist(x,y,9+r*6,18+r*8,blue,a*.4);w.star(x,y,2+r*2,gold,a*.7);});
 }
 c.restore();return true;
}

// Void objectives and theft: creature acting, not recolored trophy frames.
function voidPerformance(c,e){
 if(!['baron','herald','void_grub','objective_steal','atakhan_legacy','dragon'].includes(e.key))return false;
 const {w,o,t,p,line,poly,metal,place,arc,wake,shard,ring,motes}=eventInk(c,e);
 const violet='#c4a4ef',pink='#e79cc8',ice='#bedcf3',gold='#e6c787';
 c.save();
 if(e.key==='baron'){
  // An iridescent serpentine head, fanged jaw, three eyes and living side tendrils.
  place(85,446,1.03,-.09+Math.sin(t*.6)*.025,()=>{
   o.ribbon(u=>[-30+Math.sin(u*8+t*.36)*30,205-u*215],{width:50,color:violet,secondary:pink,phase:t*.3,alpha:.86});
   poly([[-57,-29],[-52,-80],[-23,-113],[-20,-151],[-7,-108],[9,-132],[18,-98],[47,-73],[41,-46],[20,-18],[-7,-10]],metal([-57,-151,47,-10],['#bcaddf','#504971','#9b79b1','#302f51']),.95);
   for(const [x,y,r]of [[-28,-71,8],[0,-77,10],[26,-62,7]]){o.orb(x,y,r,pink,t*.7,{glass:true});line([[x-4,y],[x+4,y]],ice,1.5);}
   const jaw=7+Math.sin(t*1.1)*4;poly([[-35,-26],[-15,-11],[18,-21],[35,-38],[28,-10-jaw],[-13,8+jaw],[-35,-6]],'#292942',.94);line([[-35,-26],[-15,-11],[18,-21],[35,-38]],violet,1.4);for(let j=0;j<6;j++){const x=-27+j*10,y=-23+Math.sin(j*.5)*9;poly([[x,y],[x+5,y+10],[x+8,y-1]],metal([x,y,x+8,y+11],['#e9ddcd','#798397','#c9d1d9']),.94);}
   for(let j=0;j<8;j++)shard(-21+Math.sin(j*.7+t*.3)*22,30+j*20,13,ice,-.25+j*.045);line([[-52,-80],[-23,-113],[-7,-108]],gold,1,.7);
  });
  for(let j=0;j<6;j++){const side=j%2,x=side?1891:20,sgn=side?-1:1;const tendril=u=>[x+sgn*(Math.sin(u*11+t*.4+j)*25+u*16),925-u*(580+j*20)];o.ribbon(tendril,{width:10+j%3*3,color:violet,secondary:pink,phase:t*.3+j,glass:true,alpha:.59});wake(tendril,j%2?pink:ice,j*.075,1.7,.21);}
  for(let j=0;j<13;j++){const x=358+j*92;place(x,48,1,0,()=>{poly([[-23,-8],[0,-22],[23,-8],[17,6],[0,16],[-17,6]],'#64568955',.8);o.orb(0,-1,8,pink,t*.4+j,{glass:true,flat:.67});line([[-23,-8],[0,-22],[23,-8]],violet,1,.6);},j*.014);}
  for(let j=0;j<4;j++)wake(u=>[340+u*1220,1059-j*6+Math.sin(u*10+t*.5+j)*9],j%2?pink:violet,j*.15,2,.19);
  motes(40,5,.08,(u,j,r,a)=>w.mist(j%2?1863+Math.sin(j)*29:56+Math.sin(j)*25,998-u*814,4+r*6,7+r*13,violet,a*.45));
 }else if(e.key==='herald'){
  // Shelly's eye turns and blinks above her segmented shell and little feet.
  place(1835,441,1.04,Math.sin(t*.65)*.035,()=>{
   poly([[-44,40],[-59,-12],[-41,-65],[-15,-88],[19,-83],[51,-47],[57,2],[38,47]],metal([-59,-88,57,47],['#bca4d4','#485d78','#8e83bb','#2d445e']));
   for(let j=0;j<5;j++){const y=-48+j*19;line([[-40,y],[-12,y+9],[28,y-2],[47,y-16]],violet,1.1,.71);}
   const blink=.28+.72*Math.abs(Math.cos(t*1.2));poly([[-37,-13],[0,-13-29*blink],[37,-13],[0,-13+29*blink]],'#332d59',.94);ring(0,-13,19,19*blink,pink,2,.85);o.orb(Math.sin(t*.9)*4,-13,10,pink,t*.5,{glass:true,flat:blink});line([[-9,-13],[-2,-20],[5,-14]],ice,1.5,.8);
   for(const side of [-1,1])for(let j=0;j<3;j++){const y=10+j*17;line([[side*41,y],[side*(64+Math.sin(t*3+j)*4),y+8],[side*57,y+16]],ice,3,.75);}shard(0,-74,13,gold,0);
  });
  for(let j=0;j<4;j++){const path=arc(1835,428,56+j*13,107+j*24,.7,5.5);wake(path,j%2?pink:ice,j*.12,1.7,.17);}
  for(let j=0;j<8;j++){const y=238+j*60;place(51,y,.65,Math.sin(t*.6+j)*.08,()=>{poly([[-20,0],[0,-15],[20,0],[0,15]],violet,.3);ring(0,0,8,9,ice,1,.65);shard(0,0,7,pink,.1);},j*.016);}
  for(let j=0;j<11;j++){const x=350+j*115;poly([[x,1077],[x+14,1053],[x+28,1077]],metal([x,1053,x+28,1077],['#aab2d4','#4e657d','#9186b6']),.67);wake(u=>[x+14,1077-u*24],pink,j*.033,1.6,.5);}
  wake(u=>[300+u*1300,42+Math.sin(u*Math.PI)*34],violet,0,2.1,.24);motes(24,4,.12,(u,j,r,a)=>w.star(44+Math.sin(j+u*5)*30,928-u*747,2+r*2,pink,a*.55));
 }else if(e.key==='void_grub'){
  // Three large playful grubs and an independently marching swarm of voidmites.
  const grub=(x,y,s,phase)=>place(x,y,s,Math.sin(t*2.5+phase)*.06,()=>{
   poly([[-31,19],[-36,-13],[-23,-34],[0,-43],[24,-31],[37,-9],[31,21]],metal([-36,-43,37,21],['#c9c0e0','#6d669a','#a994c6','#454568']),.9);for(let j=0;j<3;j++)line([[-26,-19+j*12],[0,-12+j*12],[26,-19+j*12]],violet,1,.75);
   for(const side of [-1,1])for(let j=0;j<3;j++){const x=side*(16+j*8),y=12+j%2*3;line([[x,y],[x+side*9,y+7+Math.sin(t*5+phase+j)*4],[x+side*5,y+14]],ice,2,.8);}o.orb(-10,-20,4,pink,t*.5);o.orb(10,-20,4,pink,t*.5);line([[-4,-9],[0,-6],[4,-9]],ice,1.2,.85);
  });
  grub(57,327,1.14,0);grub(1869,563,1.04,2);grub(1390,1050,.8,4);
  for(let j=0;j<18;j++){const x=320+j*71+(p*.4+Math.sin(t*.6+j)*.05)*42,y=1054+Math.sin(t*3+j)*4;grub(x,y,.24+(j%3)*.06,j*.8);}
  for(let j=0;j<8;j++){const y=208+j*66;shard(1887,y,9+j%3*3,violet,Math.sin(t*.4+j)*.2);wake(u=>[1892-u*35,y-16+u*43],pink,j*.04,1.4,.32);}
  wake(u=>[280+u*1340,35+Math.sin(u*12-t*.5)*9],ice,0,1.5,.2);for(let j=0;j<4;j++)wake(u=>[20+j*9+Math.sin(u*11+t*.5+j)*7,927-u*690],violet,j*.14,1.5,.2);
 }else if(e.key==='objective_steal'){
  // A hooked light steals a jewel out of one socket into a waiting glove.
  const q=smooth((p-.13)/.6),x=1600-q*1120,y=44+Math.sin(q*Math.PI)*48;
  place(1597,50,1,-.1,()=>{ring(0,0,34,19,violet,2,.75);line([[-25,0],[-25,24],[25,24],[25,0]],ice,1.2,.6);});
  place(470,49,1,-.12,()=>{poly([[-38,23],[-41,3],[-34,-13],[-24,-18],[-19,-10],[-12,-24],[-3,-25],[2,-10],[11,-19],[19,-15],[19,6],[35,-1],[42,6],[19,32]],metal([-41,-25,42,32],['#e7cf98','#617881','#ccb47b','#3f5564']),.92);line([[-34,-13],[-24,-18],[-19,-10]],ice,1.2);line([[-19,16],[7,22],[19,13]],gold,1,.8);});
  const path=u=>[1600-u*1120,44+Math.sin(u*Math.PI)*48];o.ribbon(path,{width:9,color:gold,secondary:ice,phase:p*6.5,glass:true,alpha:.6});wake(path,gold,0,2.5,.23);shard(x,y,18,ice,t*1.2,false);ring(x,y,25,12,gold,1,.55);
  for(let j=0;j<6;j++){const yy=243+j*70;place(1859,yy,.7,Math.sin(t*.5+j)*.05,()=>{poly([[-18,15],[-13,-19],[0,-29],[18,-11],[13,16]],violet,.26);line([[-18,15],[-13,-19],[0,-29],[18,-11]],gold,1.3,.72);},j*.027);}
  for(let j=0;j<4;j++)wake(u=>[22+j*15,899-u*655],j%2?ice:gold,j*.12,2,.2);motes(28,4,.09,(u,j,r,a)=>w.star(j%2?1863:57,1000-u*800,2+r*3,gold,a*.7));
 }else if(e.key==='atakhan_legacy'){
  // Archived event only: blood roses and a thorned, slowly opening mask.
  const red='#df9ba6';
  place(1852,425,1.2,.08,()=>{poly([[-42,-51],[-14,-104],[0,-74],[22,-111],[38,-54],[43,28],[13,57],[-21,47],[-45,4]],metal([-45,-110,43,57],['#d4a8ab','#4d3e59','#ad7c9a','#293747']),.93);poly([[-31,-19],[-5,-26],[-12,-9]],red);poly([[6,-26],[29,-21],[15,-10]],red);line([[-17,14],[0,28],[15,10]],gold,1.4);shard(0,-50,15,red,t*.4);});
  for(let j=0;j<9;j++){const y=230+j*53;place(41,y,.75,Math.sin(t*.3+j)*.07,()=>{for(let n=0;n<5;n++)w.petal(Math.cos(n*TAU/5)*11,Math.sin(n*TAU/5)*11,13,red,n*TAU/5+t*.05,.76);shard(0,0,8,gold,0);},j*.018);}
  const stem=u=>[18+Math.sin(u*12+t*.27)*14,922-u*736];wake(stem,red,0,2.2,.24);for(let j=0;j<16;j++){const [x,y]=stem(j/16);poly([[x,y],[x+16,y-9],[x+7,y+3]],'#b597b166',.8);}
  for(let j=0;j<3;j++)wake(u=>[310+u*1300,1060-j*10+Math.sin(u*9+t*.3+j)*7],j%2?gold:red,j*.15,1.8,.18);motes(24,5,.12,(u,j,r,a)=>w.petal(1871+Math.sin(j+u*3)*26,190+u*628,4+r*7,red,j+u,a*.65));
 }else{
  // Unspecialized dragon event still has its own ancient scale procession.
  place(1831,434,1.1,.12,()=>{poly([[-43,37],[-42,-37],[-23,-84],[-15,-119],[-3,-70],[23,-74],[39,-45],[54,-22],[29,-2],[7,-2],[-4,31]],metal([-43,-119,54,37],['#e2d5ac','#4e7890','#9fb7bd','#3b4d72']),.94);line([[-15,-119],[-3,-70],[23,-74],[39,-45],[54,-22]],gold,1.1);poly([[14,-38],[29,-34],[18,-28]],ice);for(let j=0;j<5;j++)shard(-26+j*3,7+j*15,12,ice,-.25);});
  for(let j=0;j<15;j++){const y=216+j*38;place(41,y,1,-.2,()=>{poly([[0,-14],[15,0],[0,19],[-15,0]],metal([-15,-14,15,19],['#cadcdd','#53748f','#bdc1aa','#374b70']),.73);line([[0,-14],[0,12]],gold,1,.65);},j*.014);}
  for(let j=0;j<4;j++)wake(u=>[320+u*1270,38+j*11+Math.sin(u*8-t*.35+j)*9],j%2?gold:ice,j*.13,1.7,.23);motes(28,5,.11,(u,j,r,a)=>w.petal(j%2?1884:57,997-u*778,6+r*5,ice,j*.2+u,a*.6));
 }
 c.restore();return true;
}

// Architectural events have separate destruction, reward and reassembly acts.
function structurePerformance(c,e){
 if(!['turret_destroyed','first_turret','inhibitor_destroyed','inhibitor_respawning_soon','inhibitor_respawned'].includes(e.key))return false;
 const {w,o,t,p,line,poly,metal,place,arc,wake,shard,ring,motes}=eventInk(c,e);
 const ice='#a8deef',gold='#e4c78a',pink='#cbade8';
 c.save();
 if(e.key==='turret_destroyed'){
  // A broken watchtower dismantles into measured masonry, not an impact flash.
  const q=smooth((p-.09)/.68);
  place(1850,400,1,0,()=>{
   poly([[-44,82],[-38,62],[38,62],[44,82]],metal([-44,62,44,82],['#b2c2c3','#52677e','#9baab4','#354e66']));
   for(let j=0;j<6;j++){const dy=q*q*(28+j*4),dx=Math.sin(j*2.4)*q*(15+j*4),angle=(j%2?1:-1)*q*.25;place(dx,42-j*22+dy,1,angle,()=>{poly([[-29,-14],[29,-14],[31,8],[-31,8]],metal([-31,-14,31,8],['#c9c9b5','#6c8490','#a0b3c1','#435e79']));line([[-24,-8],[24,-8]],ice,1,.55);});}
   place(q*18,-93+q*q*69,1,q*.22,()=>{poly([[-38,0],[-38,-24],[-23,-24],[-23,-9],[-8,-9],[-8,-29],[8,-29],[8,-9],[23,-9],[23,-24],[38,-24],[38,0]],metal([-38,-29,38,0],['#d8d3af','#738da1','#b4c2c5','#52677f']),.9);});
   shard(0,-102+q*q*92,18,ice,q*1.2);ring(0,80,57,12,gold,1,.67);
  });
  for(let j=0;j<11;j++){const y=233+j*48,x=35+Math.sin(j*2.1)*23;place(x,y+q*q*25,1,q*Math.sin(j)*.2,()=>{poly([[-14,-8],[15,-12],[19,7],[-9,11]],metal([-14,-12,19,11],['#b3c4c2','#566e86','#a8b4ad']),.7);line([[-10,-5],[8,-8]],gold,1,.7);},j*.02);}
  for(let j=0;j<3;j++)wake(pathOf([[14+j*14,930],[14+j*14,555],[49+j*14,520],[49+j*14,177]]),ice,j*.13,1.7,.18);
  for(let j=0;j<14;j++){const x=340+j*87;line([[x,1052],[x+42,1052],[x+42,1074]],gold,1,.52);wake(u=>[x,1052+u*22],ice,j*.023,1.4,.5);}
  motes(28,4,.09,(u,j,r,a)=>shard(j%2?1868+Math.sin(j)*26:49+Math.sin(j)*22,340+u*397,3+r*4,ice,j*.5+u));
 }else if(e.key==='first_turret'){
  // First structure reward: a gold foundation seal opens a small coin treasury.
  place(82,436,1.03,-.05,()=>{
   poly([[-37,68],[-29,25],[-27,-58],[27,-58],[29,25],[37,68]],metal([-37,-58,37,68],['#d7c59a','#637c88','#b7b493','#3e6175']));
   poly([[-41,-56],[-41,-78],[-24,-78],[-24,-67],[-9,-67],[-9,-84],[9,-84],[9,-67],[24,-67],[24,-78],[41,-78],[41,-56]],metal([-41,-84,41,-56],['#ead79f','#677f8d','#cfba84','#405e73']));
   ring(0,4,24,31,gold,2,.9);shard(0,4,17,ice,0);line([[-37,68],[37,68]],gold,2,.88);for(let j=0;j<4;j++)line([[-22,28+j*8],[22,28+j*8]],ice,1,.5);
  });
  for(let j=0;j<12;j++){const x=357+j*103,y=1052-Math.sin(p*3+j)*7;place(x,y,1,Math.sin(t*.8+j)*.13,()=>{o.orb(0,0,11,gold,t*.5+j,{flat:.9});ring(0,0,8,8,ice,1,.7);line([[-2,-4],[2,-4],[-2,4],[2,4]],gold,1.3);},j*.018);}
  for(let j=0;j<7;j++){const y=225+j*73;place(1871,y,1,0,()=>{ring(0,0,23,14,gold,1.5,.72);poly([[-7,-5],[0,-12],[7,-5],[4,8],[-4,8]],ice,.6);},j*.022);wake(u=>[1850-u*31,y-15+u*40],gold,j*.04,1.4,.3);}
  for(let j=0;j<3;j++)wake(u=>[330+u*1240,38+j*12+Math.sin(u*Math.PI)*20],j%2?gold:ice,j*.17,2,.28);motes(28,4,.12,(u,j,r,a)=>w.star(j%2?1881:55,930-u*710,2+r*3,gold,a*.65));
 }else if(e.key==='inhibitor_destroyed'){
  // A magenta crystal loses containment; individually engraved facets drift out.
  const q=smooth((p-.07)/.76);
  place(1838,427,1.1,0,()=>{
   ring(0,85,53,17,ice,2,.7);line([[-45,75],[-45,100],[45,100],[45,75]],gold,1.2,.65);
   for(let j=0;j<8;j++){const a=j*TAU/8,x=Math.cos(a)*(13+q*38),y=-6+Math.sin(a)*(42+q*39);shard(x,y,22+5*(j%3),j%2?pink:ice,a*.3+q*Math.sin(j)*.7);line([[x,y-10],[x+4,y+12]],gold,.8,.5);}
   for(let j=0;j<4;j++)wake(arc(0,0,42+q*24+j*9,73+q*17+j*8),j%2?pink:ice,j*.09,1.5,.19);
  });
  for(let j=0;j<9;j++){const y=224+j*56;shard(50+Math.sin(j)*19+q*Math.cos(j)*18,y+q*14,11+j%3*3,pink,j*.5+q*.4);wake(u=>[20+u*56,y-10+u*34],ice,j*.035,1.5,.34);}
  for(let j=0;j<3;j++)o.ribbon(u=>[330+u*1240,1059+Math.sin(u*15+t*.4+j)*11-j*6],{width:5,color:pink,secondary:ice,phase:t*.5+j,glass:true,alpha:.54});
  motes(36,4,.07,(u,j,r,a)=>w.star(j%2?1854+Math.sin(j+u*5)*34:48+Math.sin(j+u*4)*28,290+u*443,2+r*3,pink,a*.65));
 }else if(e.key==='inhibitor_respawning_soon'){
  // A dormant crystal clock: three offset countdown arcs and sleeping fragments.
  place(76,451,1,0,()=>{
   for(let j=0;j<3;j++){const r=39+j*12;wake(arc(0,0,r,r*1.57,.3+j*.5,5.5+j*.5),j%2?gold:pink,j*.14,1.8,.18);}
   for(let j=0;j<5;j++){const y=-54+j*27;shard(Math.sin(j+t*.3)*7,y,16,pink,.3+Math.sin(t*.4+j)*.06);}
   line([[-23,81],[23,81]],gold,2,.7);ring(0,81,35,8,ice,1,.5);
   for(let j=0;j<12;j++){const a=j*TAU/12;line([[Math.cos(a)*68,Math.sin(a)*104],[Math.cos(a)*74,Math.sin(a)*113]],ice,j%3===0?2:1,.58);}
  });
  for(let j=0;j<9;j++){const y=230+j*52;place(1874,y,1,.15,()=>{poly([[-13,0],[0,-18],[13,0],[0,18]],pink,.17);line([[-13,0],[0,-18],[13,0]],ice,1,.6);ring(0,0,3,3,gold,1,.7);},j*.019);}
  for(let j=0;j<15;j++){const x=348+j*83;line([[x,49],[x,23],[x+17,14],[x+34,23],[x+34,49]],pink,.9,.46);wake(u=>[x+17,47-u*32],gold,j*.025,1.5,.24);}
  for(let j=0;j<3;j++)wake(u=>[1570-u*1250,1060-j*7+Math.sin(u*9+t*.3+j)*6],ice,j*.19,1.4,.21);
 }else{
  // Rebirth: floating fragments snap softly into a restored central crystal.
  const q=smooth((p-.04)/.65);
  place(1842,440,1.12,0,()=>{
   for(let j=0;j<6;j++){const a=j*TAU/6,spread=(1-q)*34;shard(Math.cos(a)*spread,-28+Math.sin(a)*spread,27,j%2?ice:pink,a*.23*(1-q));}
   shard(0,-28,53,pink,.03,true);line([[0,-81],[0,24]],ice,1.4,.8);ring(0,64,51,14,gold,1.7,.8);ring(0,73,45,13,ice,1,.6);line([[-35,70],[-35,90],[35,90],[35,70]],gold,1.3,.7);
   for(let j=0;j<3;j++)wake(arc(0,-28,38+j*12,69+j*14),j%2?gold:ice,j*.13,1.9,.22);
  });
  for(let j=0;j<13;j++){const y=230+j*39;place(44,y,1,0,()=>{shard(0,0,11,pink,0);line([[-17,8],[0,-11],[17,8]],ice,1.4,.71);},j*.015);}
  for(let j=0;j<4;j++)wake(u=>[330+u*1250,29+j*11+Math.sin(u*Math.PI)*25],j%2?pink:gold,j*.11,1.8,.28);
  motes(32,4.7,.085,(u,j,r,a)=>{const x=j%2?1879+Math.sin(j)*23:46+Math.sin(j)*25;shard(x,1000-u*804,3+r*5,ice,j*.3);});
 }
 c.restore();return true;
}

// Death's continuous clock comes from observed state. No result, timer or scene policy.
function soulPerformance(c,death){
 const {w,o,t,line,poly,metal,place,arc,wake,shard,ring,motes}=eventInk(c,{elapsed:death.elapsed||0,duration:Infinity});
 const blue=death.worth?'#c9ddbd':'#a8d4ef',pearl='#deddf0',gold='#dcc79c';
 c.save();c.globalAlpha*=smooth(t/1.25);
 // Four staggered soul lanterns have different etched windows and pendulum phases.
 for(const[x,y,s,phase]of [[66,298,1.08,0],[1849,382,1.06,1.7],[43,655,.74,3.3],[1880,627,.64,4.8]]){
  const swing=Math.sin(t*.55+phase)*.055;
  place(x,y,s,swing,()=>{
   line([[0,-128],[0,-65]],gold,.9,.6);ring(0,-66,9,7,gold,1.3,.8);
   poly([[-32,-44],[-15,-61],[15,-61],[32,-44],[26,35],[12,48],[-12,48],[-26,35]],metal([-32,-61,32,48],['#c7d1dd','#4f7087','#b6b2c7','#385670']),.85);
   poly([[-20,-37],[20,-37],[16,30],[0,39],[-16,30]],blue,.13);line([[-20,-37],[-16,30],[0,39],[16,30],[20,-37]],blue,1.2,.75);
   for(let j=0;j<3;j++){const yy=-23+j*19;line([[-17,yy],[0,yy-8],[17,yy]],pearl,.8,.65);}
   o.ribbon(u=>[Math.sin(u*7+t*.7+phase)*9,23-u*49],{width:10,color:blue,secondary:pearl,phase:t*.22+phase,glass:true,alpha:.74});
   w.mist(0,3,23,40,blue,.7);line([[-32,-44],[32,-44]],gold,2,.75);line([[-26,35],[26,35]],gold,1.4,.75);
  });w.mist(x,y,62*s,113*s,blue,.23);
 }
 // The top hourglass has an actual remaining-life fill and a flowing sand thread.
 place(1444,66,.63,.12,()=>{
  line([[-33,-54],[33,-54]],gold,4,.8);line([[-33,54],[33,54]],gold,4,.8);line([[-26,-48],[-26,48]],blue,2,.65);line([[26,-48],[26,48]],blue,2,.65);
  poly([[-20,-44],[20,-44],[7,-4],[7,4],[20,44],[-20,44],[-7,4],[-7,-4]],'#b9e4f225',.83);
  const fill=Number.isFinite(death.remaining)?Math.min(1,Math.max(0,death.remaining)/35):.6;
  poly([[-16*fill,-38],[16*fill,-38],[0,-5]],blue,.48);poly([[-17,41],[17,41],[0,41-(1-fill)*28]],pearl,.43);wake(u=>[Math.sin(u*5+t*.7)*1.5,-4+u*35],gold,0,1.1,.12,.62);
  line([[-20,-44],[-7,-4],[-7,4],[-20,44]],pearl,1,.7);line([[20,-44],[7,-4],[7,4],[20,44]],blue,1,.6);
 });
 // Soul silk floats at two unequal edges, carrying light rather than an opaque wall.
 for(const [x,sgn,j]of [[17,1,0],[1901,-1,1]])for(let n=0;n<3;n++){
  const path=u=>[x+sgn*(Math.sin(u*10+t*.16+j+n*.32)*18+n*9),932-u*751];
  o.ribbon(path,{width:11+n*4,color:blue,secondary:pearl,phase:t*.13+n+j,glass:true,alpha:.31});wake(path,n%2?gold:blue,n*.24+j*.14,1.4,.21,.071+n*.008);
 }
 // Soul moths: absolute serials select their route and wing phases, no visible reset.
 motes(24,11,.46,(u,j,r,a)=>{
  const x=j%2?1853+Math.sin(u*7+j)*33:58+Math.sin(u*6+j)*34,y=1048-u*855;
  c.save();c.globalAlpha*=a*.64;c.translate(x,y);c.rotate(Math.sin(j+u*2)*.35);const wing=3+Math.abs(Math.sin(t*3.2+j))*8;
  w.petal(-wing*.7,0,wing,blue,-.55,.86);w.petal(wing*.7,0,wing,pearl,.55,.86);line([[0,-5],[0,5]],gold,1.1,.8);c.restore();
 });
 // Long top and lower constellations have staggered charge routes and hanging charms.
 for(let j=0;j<13;j++){const x=350+j*86,y=1058+Math.sin(t*.2+j*.4)*7;shard(x,y,5+j%3*2,j%2?blue:pearl,Math.sin(t*.2+j)*.1);if(j<12)wake(u=>[x+8+u*69,y+Math.sin(u*Math.PI)*4],j%2?blue:gold,j*.11,1.2,.25,.046);}
 for(let j=0;j<5;j++){const x=438+j*211;line([[x,8],[x,28]],gold,.8,.4);ring(x,38,8,14,pearl,.9,.6);shard(x,38,5,blue,.1);}
 c.restore();
}

// Every combat cue has a distinct little act and its own arrangement of charms.
function combatPerformance(c,e){
 if(!['kill','assist','first_blood','low_hp_kill','low_hp_multikill','double_kill','triple_kill','quadra_kill','pentakill','ace','manpower_advantage'].includes(e.key))return false;
 const ink=eventInk(c,e),{w,o,t,p,line,poly,metal,place,arc,wake,shard,ring,motes}=ink,{blade,shield,heart,helmet,glove,coin}=eventProps(ink);
 const gold='#e8cb91',ice='#bde5ef',rose='#e3a6bd',mint='#a9dfc2';
 c.save();
 if(e.key==='kill'){
  // A single rapier cools into etched metal while spent shards settle opposite it.
  blade(1856,450,1.07,-.32+smooth(p)*.16,ice);
  for(let j=0;j<7;j++){const y=244+j*65;shard(42+Math.sin(j)*18,y+smooth(p)*12,10+j%3*3,j%2?ice:rose,j*.33+p*.3);wake(u=>[18+u*47,y+u*29],ice,j*.04,1.5,.32);}
  for(let j=0;j<3;j++)wake(u=>[1879-j*15+Math.sin(u*Math.PI)*18,884-u*650],j%2?gold:ice,j*.13,1.9,.2);
  for(let j=0;j<13;j++){const x=360+j*88;line([[x,43],[x+19,31],[x+39,43]],ice,1,.55);if(j%3===0)shard(x+19,37,6,rose,.2);}
  motes(25,3,.07,(u,j,r,a)=>w.star(1866+Math.sin(j+u*4)*31,841-u*601,2+r*2,ice,a*.6));
 }else if(e.key==='double_kill'){
  // A two-blade duet: one unsheathes upward while the second turns downward.
  const q=smooth((p-.04)/.65);blade(67,452-q*42,1.03,.24+q*.14,ice);blade(1858,377+q*48,1.03,Math.PI-.34-q*.13,rose,.045);
  for(let j=0;j<4;j++){const y=236+j*125;ring(32,y,16,24,j%2?rose:ice,1.2,.6);ring(1889,y+34,16,24,j%2?ice:rose,1.2,.6);}
  wake(u=>[310+u*1300,49+Math.sin(u*Math.PI)*29],ice,0,2,.3);wake(u=>[1610-u*1300,1060-Math.sin(u*Math.PI)*20],rose,.13,2,.3);
  for(let j=0;j<15;j++){const x=350+j*85;shard(x,1059+Math.sin(t*.7+j)*4,7,j%2?ice:rose,j*.4);}
 }else if(e.key==='triple_kill'){
  // Three daggers rotate around an off-center optical clock, with three chain runs.
  for(let j=0;j<3;j++){const a=j*TAU/3+t*.25;blade(1851+Math.cos(a)*22,424+Math.sin(a)*84,.66,a+.75,j%2?gold:ice,j*.04);wake(arc(1851,424,41+j*10,102+j*12),j%2?rose:ice,j*.11,1.7,.21);}
  for(let j=0;j<9;j++){const y=233+j*58;place(40,y,1,Math.sin(t*.6+j)*.08,()=>{poly([[-13,-7],[0,-17],[13,-7],[10,11],[-10,11]],metal([-13,-17,13,11],['#d1dbe4','#647a92','#cbb8aa']),.72);ring(0,1,6,7,rose,1,.7);},j*.017);}
  for(let j=0;j<3;j++)wake(u=>[320+u*1270,31+j*13+Math.sin(u*9+j)*8],j===1?rose:ice,j*.16,1.7,.22);
  motes(28,3.7,.08,(u,j,r,a)=>w.star(38+Math.sin(j+u*6)*28,970-u*760,2+r*3,gold,a*.6));
 }else if(e.key==='quadra_kill'){
  // Four compass blades and four articulated corner petals form a rotating crest.
  for(const[x,y,a,j]of [[66,254,-.48,0],[1855,280,.48,1],[62,674,2.65,2],[1860,629,3.63,3]]){blade(x,y,.76,a+Math.sin(t*.5+j)*.04,j%2?rose:ice,j*.025);for(let n=0;n<3;n++)wake(arc(x,y,36+n*9,65+n*14,.25,5.9),j%2?gold:ice,j*.06+n*.08,1.4,.19);}
  for(let j=0;j<4;j++){const x=480+j*305;place(x,46,1.2,Math.sin(t*.6+j)*.04,()=>{for(let n=0;n<4;n++)w.petal(Math.cos(n*TAU/4)*12,Math.sin(n*TAU/4)*12,16,n%2?rose:ice,n*TAU/4,.63);shard(0,0,8,gold,0);},j*.022);}
  for(let j=0;j<18;j++){const x=360+j*68;line([[x,1066],[x+17,1046],[x+34,1066]],gold,1.1,.57);}
 }else if(e.key==='pentakill'){
  // Five champions' blades rise into a stage crown; small pennants follow the charge.
  for(let j=0;j<5;j++){const x=490+j*236;blade(x,52,.39,-.13+j*.065,gold,j*.035);ring(x,54,30,23,ice,1,.57);wake(u=>[x,80-u*77],rose,j*.07,2.2,.2);}
  for(const side of [0,1])for(let j=0;j<6;j++){const x=side?1878:42,y=230+j*83;place(x,y,1,(side?-1:1)*.12,()=>{poly([[-17,-23],[17,-23],[17,23],[0,14],[-17,23]],metal([-17,-23,17,23],['#e8d09b','#6c638b','#c0a8cb']),.77);line([[-14,-19],[14,-19]],gold,1.4,.85);shard(0,-1,8,ice,.1);},j*.018);wake(u=>[x,y-17+u*33],gold,j*.04,1.7,.3);}
  for(let j=0;j<5;j++)wake(u=>[320+u*1280,1064-j*7+Math.sin(u*13-t*.4+j*.3)*7],j%2?ice:gold,j*.12,1.5,.22);
  motes(38,4,.07,(u,j,r,a)=>w.star(j%2?1867+Math.sin(j)*32:52+Math.sin(j)*27,1000-u*813,2+r*3,gold,a*.7));
 }else if(e.key==='first_blood'){
  // A garnet drop opens into crimson silk and one ceremonial blade.
  place(79,413,1.14,Math.sin(t*.5)*.03,()=>{poly([[0,-71],[39,-10],[30,27],[0,48],[-30,27],[-39,-10]],metal([-39,-71,39,48],['#f1c7ce','#a36586','#e3a6a8','#4c466d']),.91);line([[0,-63],[0,39]],gold,1.4,.72);line([[-27,-3],[-15,-17]],ice,1.3,.8);shard(0,6,20,rose,.05);});blade(1855,455,.89,.3,rose,.035);
  for(let j=0;j<3;j++)o.ribbon(u=>[21+j*15+Math.sin(u*11-t*.35+j)*17,930-u*680],{width:13,color:rose,secondary:gold,phase:t*.4+j,glass:true,alpha:.51});
  for(let j=0;j<12;j++){const x=370+j*96;place(x,1060,1,Math.sin(t*.4+j)*.08,()=>poly([[0,-11],[7,0],[0,8],[-7,0]],rose,.63),j*.015);}
  wake(u=>[330+u*1240,38+Math.sin(u*9)*14],gold,0,1.8,.22);motes(26,4,.1,(u,j,r,a)=>w.petal(1867+Math.sin(j)*26,222+u*540,4+r*6,rose,j*.3+u,a*.65));
 }else if(e.key==='low_hp_kill'){
  // A cracked heart is repaired by a moving gold needle and luminous stitches.
  heart(1842,435,1.15,-.09,rose);const q=smooth((p-.05)/.75);
  line([[1834,403],[1848,420],[1835,435],[1848,451],[1840,466]],'#374464',2,.8);
  for(let j=0;j<5;j++){const y=408+j*12;line([[1830,y],[1852,y+5]],gold,1.4,smooth((q-j*.16)/.2));}
  const ny=395+q*77;line([[1812,ny],[1829,ny+17]],ice,2,.85);ring(1812,ny,3,4,gold,1,.7);
  shield(58,401,.79,.08,mint,.03);for(let j=0;j<7;j++){const y=250+j*65;heart(39,y,.19,Math.sin(t*.7+j)*.08,j%2?rose:gold,j*.017);}
  const pulse=pathOf([[315,1056],[591,1056],[607,1044],[619,1071],[635,1033],[654,1056],[944,1056],[964,1048],[982,1056],[1600,1056]]);wake(pulse,gold,0,2.1,.23);
  motes(25,4,.095,(u,j,r,a)=>w.star(1867+Math.sin(j)*23,930-u*703,2+r*2,gold,a*.6));
 }else if(e.key==='low_hp_multikill'){
  // An ember heart spreads feather wings; three pulse capsules charge in sequence.
  heart(67,438,1.02,.07,rose);
  for(const side of [-1,1])for(let j=0;j<6;j++){const x=69+side*(12+j*3),y=405+j*13;w.petal(x,y,24-j*2,j%2?gold:ice,side*(-.7-j*.04)+Math.sin(t*.6+j)*.04,.7);}
  for(let j=0;j<3;j++){const y=302+j*152;place(1858,y,1,0,()=>{ring(0,0,24,51,rose,1.4,.67);heart(0,0,.44,.06,gold);wake(u=>[0,-39+u*78],ice,j*.15,1.8,.23);},j*.04);}
  for(let j=0;j<4;j++)wake(u=>[320+u*1280,32+j*12+Math.sin(u*11-t*.4+j)*9],j%2?gold:rose,j*.1,1.8,.2);
  motes(30,4,.08,(u,j,r,a)=>w.petal(j%2?1869:37,962-u*717,5+r*8,gold,j*.3+u,a*.65));
 }else if(e.key==='assist'){
  // Two armored hands meet and braided light passes between little support shields.
  const q=smooth((p-.04)/.5);glove(67+q*8,419,.75,-.27,mint);glove(92-q*8,434,.75,2.78,ice,.045);shield(1849,429,1,.08,mint,.02);
  for(let j=0;j<3;j++)wake(u=>[330+u*1260,1055+Math.sin(u*13+t*.3+j*TAU/3)*11],j%2?ice:mint,j*.14,1.8,.24);
  for(let j=0;j<8;j++){const y=238+j*62;ring(1879,y,14,21,mint,1.3,.65);if(j%2===0)shield(1879,y,.18,.03,gold);}
  for(let j=0;j<12;j++){const x=370+j*94;ring(x,43,13,8,j%2?mint:ice,1,.6);wake(arc(x,43,13,8),gold,j*.025,1.3,.25);}
 }else if(e.key==='ace'){
  // Five fallen helmet charms settle beneath fluttering banners and team laurels.
  for(let j=0;j<5;j++){const x=483+j*238;helmet(x,57,.55,-.12+j*.055,gold,j*.034);line([[x-35,17],[x+35,17]],ice,1,.61);}
  for(const side of [0,1])for(let j=0;j<4;j++){const x=side?1877:42,y=240+j*111;place(x,y,.9,Math.sin(t*.7+j)*.055,()=>{line([[-18,-31],[-18,35]],gold,1.4,.75);poly([[-18,-27],[21,-27+Math.sin(t*1.1+j)*3],[16,12],[0,4],[-18,12]],ice,.24);line([[-18,-27],[21,-27+Math.sin(t*1.1+j)*3],[16,12]],gold,1,.7);},j*.025);}
  for(let j=0;j<18;j++){const x=340+j*72;w.petal(x,1058+Math.sin(t*.4+j)*5,11,gold,-.3+j*.04,.74);}
  for(let j=0;j<3;j++)wake(u=>[310+u*1290,1048-j*6-Math.sin(u*Math.PI)*11],j%2?mint:gold,j*.15,1.7,.23);
 }else{
  // Allied advantage is a balancing instrument, without invented player counts.
  place(1848,435,1,Math.sin(t*.55)*.035,()=>{line([[0,-82],[0,73]],gold,4,.85);line([[-44,-39],[43,-53]],ice,3,.8);for(const[x,y]of [[-37,-37],[36,-52]]){line([[x,y],[x-18,y+57],[x+18,y+57],[x,y]],gold,.8,.7);ring(x,y+57,23,8,ice,1.3,.7);}poly([[-30,76],[0,66],[30,76],[30,84],[-30,84]],metal([-30,66,30,84],['#d4cbad','#67859b','#a7b4c3']),.83);shard(-37,15,14,mint,.05);shard(36,-5,21,ice,.05);});
  for(let j=0;j<7;j++){const y=241+j*66;shield(47,y,.32,Math.sin(t*.6+j)*.05,j%2?gold:mint,j*.02);}
  for(let j=0;j<3;j++)wake(u=>[340+u*1230,35+j*13+Math.sin(u*10+j)*7],j%2?ice:mint,j*.15,1.6,.22);
  for(let j=0;j<12;j++){const x=365+j*99;ring(x,1059,10,10,gold,1,.65);shard(x,1059,5,mint,.1);}
 }
 c.restore();return true;
}

// Health and revival: protective, restorative or fractured props with quiet edges.
function vitalPerformance(c,e){
 const custom=e.key?.startsWith('custom_');
 if(!['respawn','low_health','heavy_health_loss','large_heal'].includes(e.key)&&!custom)return false;
 const ink=eventInk(c,e),{w,o,t,p,line,poly,metal,place,arc,wake,shard,ring,motes}=ink,{heart,shield,vial}=eventProps(ink);
 const ice='#c0e5ef',mint='#a7dfbd',rose='#e3a3b9',gold='#e1ca98';
 c.save();
 if(e.key==='respawn'){
  // A small gate opens and an armored spirit steps through, trailing fresh leaves.
  const q=smooth((p-.04)/.68);
  place(76,439,1.1,0,()=>{
   for(const side of [-1,1]){poly([[side*25,-70],[side*43,-54],[side*43,66],[side*27,66]],metal([side*25,-70,side*43,66],['#cad9d3','#547b93','#adbabf','#3a607c']),.91);line([[side*29,-66],[side*29,61]],gold,1.3,.8);}
   poly([[-25,-70],[0,-99],[25,-70],[16,-64],[0,-80],[-16,-64]],metal([-25,-99,25,-64],['#d4dabc','#6c889b','#bccbcb']),.9);
   for(const side of [-1,1]){const x=side*(1+q*19);poly([[x,-64],[x+side*19,-61],[x+side*19,56],[x,59]],mint,.17);line([[x,-64],[x,59]],ice,1.2,.72);}
   o.orb(0,-23,12,ice,t*.4,{glass:true});poly([[-9,-4],[9,-4],[17,23],[8,37],[-8,37],[-17,23]],mint,.3);line([[-8,36],[-10,56],[0,61]],gold,1.2,.75);line([[8,36],[11,56],[19,57]],gold,1.2,.75);
   ring(0,71,50,11,mint,1.6,.75);
  });
  for(let j=0;j<9;j++){const y=230+j*54;place(1870,y,1,Math.sin(t*.4+j)*.06,()=>{for(let n=0;n<3;n++)w.petal(Math.cos(n*TAU/3)*8,Math.sin(n*TAU/3)*8,12,mint,n*TAU/3,.75);shard(0,0,5,gold,0);},j*.021);}
  for(let j=0;j<4;j++)wake(u=>[330+u*1260,1058-j*8-Math.sin(u*Math.PI)*13],j%2?mint:ice,j*.12,1.8,.27);
  motes(32,4,.09,(u,j,r,a)=>w.petal(j%2?1866:38,985-u*781,5+r*7,mint,j*.5+u,a*.64));
 }else if(e.key==='low_health'){
  // A glass heart hangs inside a protective cage; one gentle pulse traces its cable.
  heart(1859,442,.84,Math.sin(t*.6)*.025,rose);for(let j=0;j<3;j++)wake(arc(1859,435,36+j*8,62+j*13,.5,5.6),j%2?ice:rose,j*.17,1.4,.19);
  line([[1840,360],[1859,343],[1879,360]],gold,1.2,.68);line([[1859,343],[1859,212]],ice,.85,.5);
  const pulse=pathOf([[30,925],[30,623],[45,612],[23,595],[62,575],[30,552],[30,188]]);wake(pulse,rose,0,1.8,.24);
  for(let j=0;j<7;j++){const y=257+j*61;shield(41,y,.22,Math.sin(t*.5+j)*.07,j%2?ice:rose,j*.02);}
  for(let j=0;j<15;j++){const x=343+j*87;line([[x,1060],[x+17,1060],[x+25,1052],[x+31,1065],[x+40,1060]],rose,1,.48);}
  motes(20,3.8,.12,(u,j,r,a)=>w.mote(1863+Math.sin(j)*21,885-u*635,1+r*2,rose,a*.6));
 }else if(e.key==='heavy_health_loss'){
  // A transparent shield breaks into tempered panes that soften and settle.
  const q=smooth((p-.04)/.68);
  place(70,445,1.1,0,()=>{
   const parts=[[[-28,-35],[-4,-45],[-4,-4],[-23,8]],[[-1,-45],[28,-33],[24,9],[3,-4]],[[-23,11],[-5,-1],[0,35],[-16,20]],[[4,-1],[24,12],[14,23],[2,35]]];
   parts.forEach((pts,j)=>{c.save();c.translate(Math.cos(j*2.3)*q*13,Math.sin(j*2.1)*q*14);o.sheet(pts,j%2?ice:rose,p,{glass:true,alpha:.82});c.restore();});
   line([[-31,-36],[-4,-49],[30,-34]],gold,1.4,.72);for(let j=0;j<4;j++)shard(-24+j*17,68+q*12,8,ice,j*.45+q*.3);
  });
  for(let j=0;j<4;j++)wake(pathOf([[1882-j*9,225],[1875-j*9,355],[1890-j*9,391],[1849-j*9,431],[1880-j*9,476],[1871-j*9,713]]),j%2?rose:ice,j*.11,1.6,.19);
  for(let j=0;j<13;j++){const x=350+j*93;shard(x,44+Math.sin(t*.4+j)*4,7+j%3*2,j%2?ice:rose,j*.4);}
  motes(28,4,.085,(u,j,r,a)=>shard(1871+Math.sin(j+u*3)*27,279+u*413,3+r*5,rose,j*.4+u));
 }else if(e.key==='large_heal'){
  // Restorative garden: a vial pours into a sprouting glass heart and fresh leaves.
  vial(1849,352,.91,-.42-smooth(p)*.25,mint);heart(1849,484,.95,.06,mint,.03);
  wake(u=>[1856+Math.sin(u*9-t)*6,373+u*80],mint,0,1.9,.3);
  for(const side of [-1,1]){const path=u=>[1849+side*(22+Math.sin(u*Math.PI)*18),508-u*110];wake(path,gold,side>0?.15:0,1.5,.22);for(let j=0;j<6;j++){const [x,y]=path(j/6);w.petal(x+side*10,y,14,mint,side*.7+Math.sin(t*.5+j)*.05,.65);}}
  for(let j=0;j<8;j++){const y=241+j*67;place(45,y,.7,Math.sin(t*.5+j)*.07,()=>{for(let n=0;n<5;n++)w.petal(Math.cos(n*TAU/5)*9,Math.sin(n*TAU/5)*9,12,n%2?mint:ice,n*TAU/5,.66);o.orb(0,0,4,gold,t*.3);},j*.02);}
  for(let j=0;j<3;j++)wake(u=>[320+u*1270,1057-j*9+Math.sin(u*12-t*.4+j)*7],j%2?mint:ice,j*.15,1.8,.23);
  motes(30,4,.09,(u,j,r,a)=>w.petal(j%2?1867:39,954-u*739,5+r*7,mint,j*.3+u,a*.68));
 }else{
  // The saved disabled health-threshold example has a calibrated warning instrument.
  // Unknown future custom rules keep a neutral instrument without claiming a cause.
  const health=String(e.title||'').toLowerCase().includes('health');
  place(1848,428,1,0,()=>{ring(0,0,39,67,health?rose:ice,1.7,.72);for(let j=0;j<12;j++){const a=-1.3+j*.23;line([[Math.cos(a)*39,Math.sin(a)*64],[Math.cos(a)*45,Math.sin(a)*73]],gold,j%3===0?2:1,.7);}line([[0,0],[Math.cos(-.8+p*.35)*29,Math.sin(-.8+p*.35)*48]],ice,2,.9);o.orb(0,0,6,gold,t*.4);if(health)heart(0,23,.31,.05,rose);else shard(0,23,14,ice,.05);});
  for(let j=0;j<9;j++){const y=233+j*57;ring(39,y,9,14,health?rose:ice,1,.61);shard(39,y,5,gold,0);}
  for(let j=0;j<3;j++)wake(u=>[330+u*1250,36+j*12+Math.sin(u*10+j)*6],health?rose:ice,j*.14,1.6,.21);
 }
 c.restore();return true;
}

// Spell progression and resource use: books, instruments and small magical machines.
function progressPerformance(c,e){
 if(!['resource_spent','level_up','ultimate_learned','ability_rank_up'].includes(e.key))return false;
 const ink=eventInk(c,e),{w,o,t,p,line,poly,metal,place,arc,wake,shard,ring,motes}=ink,{book,vial}=eventProps(ink);
 const ice='#bae6ef',violet='#c4b1e9',gold='#e4cc97';
 c.save();
 if(e.key==='resource_spent'){
  // A translucent mana reservoir drains into three travelling droplets.
  place(1848,437,1,0,()=>{
   poly([[-27,-75],[27,-75],[31,64],[19,76],[-19,76],[-31,64]],'#afd4eb1e',.85);line([[-27,-75],[-31,64],[-19,76],[19,76],[31,64],[27,-75]],ice,1.4,.72);line([[-30,-77],[30,-77]],gold,4,.8);line([[-20,-67],[-20,54]],ice,1,.55);
   const level=-45+smooth(p)*83;poly([[-25,level],[25,level],[28,61],[16,69],[-16,69],[-28,61]],violet,.33);line([[-24,level],[24,level]],ice,1.1,.8);for(let j=0;j<8;j++)line([[15,-55+j*15],[28,-55+j*15]],gold,1,.6);ring(0,81,38,11,ice,1,.6);
  });
  for(let j=0;j<3;j++){const q=smooth((p-j*.09)/.71),y=409+q*203;shard(1882,y,10,violet,-.3);wake(u=>[1882+Math.sin(u*6+j)*7,407+u*214],ice,j*.13,1.6,.2);}
  for(let j=0;j<8;j++){const y=243+j*61;vial(43,y,.32,Math.sin(t*.6+j)*.09,j%2?violet:ice,j*.022);}
  for(let j=0;j<3;j++)wake(u=>[1570-u*1240,1061-j*8+Math.sin(u*11+j)*6],violet,j*.15,1.5,.2);
 }else if(e.key==='level_up'){
  // A tiny rune staircase unfolds while a book turns its illuminated pages.
  book(1845,421,1.02,.1,violet);
  for(let j=0;j<8;j++){const y=654-j*54,x=21+j%3*12,q=smooth((p-j*.035)/.27);place(x,y,1,0,()=>{poly([[0,10],[43,10],[43,-3],[0,-3]],metal([0,-3,43,10],['#ceccad','#607b91','#bdb5d2']),.77);line([[0,-3],[43,-3]],j%2?gold:ice,1.4,.85);shard(24,-12,7,violet,0);},j*.035);wake(u=>[x+24,y+6-u*33],gold,j*.06,1.6,.33);}
  for(let j=0;j<12;j++){const x=370+j*96;place(x,48,1,0,()=>{poly([[-11,10],[0,-8],[11,10]],ice,.2);line([[-11,10],[0,-8],[11,10]],gold,1.1,.6);},j*.019);}
  motes(28,3.8,.085,(u,j,r,a)=>w.star(1868+Math.sin(j)*27,988-u*750,2+r*3,gold,a*.63));
 }else if(e.key==='ultimate_learned'){
  // Four floating spell panels rotate open around an arcane observatory.
  place(75,438,1,0,()=>{
   for(let j=0;j<4;j++){const a=j*TAU/4+t*.2,x=Math.cos(a)*34,y=Math.sin(a)*78;c.save();c.translate(x,y);c.rotate(a*.12);o.sheet([[-17,-25],[17,-25],[17,25],[-17,25]],j%2?violet:ice,p,{glass:true,alpha:.8});shard(0,0,10,j%2?gold:ice,0);c.restore();}
   o.orb(0,0,21,violet,t*.4,{glass:true});for(let j=0;j<3;j++)wake(arc(0,0,31+j*12,59+j*20),j%2?gold:ice,j*.15,1.8,.2);line([[0,-129],[0,-104]],gold,1.3,.7);ring(0,-139,8,8,ice,1,.6);
  });
  book(1848,433,.96,-.08,violet,.04);
  for(let j=0;j<9;j++){const y=221+j*61;shard(1872,y,9+j%3*2,violet,j*.2);line([[1860,y],[1884,y]],gold,.8,.45);}
  for(let j=0;j<4;j++)wake(u=>[330+u*1250,35+j*11+Math.sin(u*Math.PI)*18],j%2?gold:violet,j*.11,1.8,.25);
  for(let j=0;j<16;j++){const x=350+j*79;ring(x,1060,9,9,ice,1,.53);if(j%3===0)shard(x,1060,5,gold,0);}
 }else{
  // One ability rune clicks into a machined notch; little spell seals witness it.
  place(1849,433,1,0,()=>{
   ring(0,0,40,54,ice,1.7,.75);for(let j=0;j<8;j++){const a=j*TAU/8;poly([[Math.cos(a)*36,Math.sin(a)*49],[Math.cos(a)*47,Math.sin(a)*62],[Math.cos(a+.13)*46,Math.sin(a+.13)*61]],gold,.7);}shard(0,-28+smooth(p)*28,25,violet,.04,false);line([[-14,38],[14,38]],gold,2,.8);ring(0,0,22,31,violet,1,.5);
  });
  for(let j=0;j<7;j++){const y=243+j*66;place(42,y,1,Math.sin(t*.4+j)*.04,()=>{poly([[-12,-10],[0,-18],[12,-10],[12,10],[0,18],[-12,10]],ice,.13);line([[-12,-10],[0,-18],[12,-10]],gold,1,.7);shard(0,0,7,violet,.1);},j*.019);}
  for(let j=0;j<3;j++)wake(u=>[320+u*1260,1059-j*8+Math.sin(u*8+j)*5],j%2?ice:gold,j*.16,1.6,.2);
 }
 c.restore();return true;
}

// Four different economy/vision subjects. Actual event titles retain their values.
function economyPerformance(c,e){
 if(!['inventory_added','inventory_removed','cs_milestone','vision_activity'].includes(e.key))return false;
 const ink=eventInk(c,e),{w,o,t,p,line,poly,metal,place,arc,wake,shard,ring,motes}=ink,{coin}=eventProps(ink);
 const ice='#b4e2ed',gold='#e6c98c',mint='#a8ddba',violet='#c6b1e4';
 c.save();
 if(e.key==='inventory_added'){
  // A jewelled satchel opens to receive a gem; little inventory tags hang beside it.
  const q=smooth((p-.06)/.69);
  place(77,445,1,0,()=>{poly([[-41,-40],[38,-40],[43,43],[26,58],[-29,58],[-43,38]],metal([-43,-40,43,58],['#c4c0b4','#556f87','#b6a3ac','#385b7a']),.91);line([[-39,-34],[-33,36],[32,36],[37,-34]],gold,1.3,.72);poly([[-40,-40],[37,-40],[25,-73-q*15],[-28,-73-q*15]],ice,.19);line([[-28,-73-q*15],[25,-73-q*15]],gold,1.3,.76);ring(0,40,9,8,ice,1.3,.75);shard(0,-109+q*95,20,violet,q*.2);});
  for(let j=0;j<8;j++){const y=239+j*64;place(1871,y,1,Math.sin(t*.6+j)*.055,()=>{line([[0,-24],[0,-12]],gold,.8,.65);poly([[-13,-9],[0,-17],[13,-9],[13,15],[-13,15]],ice,.21);ring(0,-6,3,3,gold,1,.7);shard(0,6,6,violet,.1);},j*.02);}
  for(let j=0;j<12;j++){const x=370+j*96;coin(x,1057,.48,Math.sin(t*.6+j)*.1,j*.017);}
  for(let j=0;j<3;j++)wake(u=>[330+u*1250,34+j*12+Math.sin(u*8+j)*7],j%2?violet:gold,j*.15,1.7,.25);
 }else if(e.key==='inventory_removed'){
  // An empty drawer retracts; a departing jewel turns into a few quiet coins.
  const q=smooth((p-.05)/.72);
  place(1845,441,1,0,()=>{poly([[-44,-44],[44,-44],[44,45],[-44,45]],metal([-44,-44,44,45],['#d5cdb5','#6e8b9d','#b1b2c6','#49677d']),.85);poly([[-33,-30],[33,-30],[33,31],[-33,31]],'#1c3e5833',.9);line([[-33,-30],[33,-30],[33,31],[-33,31],[-33,-30]],ice,1,.62);const dy=28*(1-q);poly([[-34,dy],[34,dy],[29,dy+22],[-29,dy+22]],ice,.22);line([[-29,dy+21],[29,dy+21]],gold,1.4,.7);ring(0,dy+11,7,3,gold,1,.7);shard(-q*37,-71-q*52,20,violet,-q*.4);});
  for(let j=0;j<9;j++){const y=247+j*61;coin(43,y,.56,Math.sin(t*.7+j)*.1,j*.022);}
  for(let j=0;j<3;j++)wake(u=>[1590-u*1270,1057-j*9+Math.sin(u*8+j)*6],j%2?ice:gold,j*.15,1.7,.2);
  motes(25,4,.09,(u,j,r,a)=>w.star(1868+Math.sin(j)*26,254+u*440,2+r*2,violet,a*.6));
 }else if(e.key==='cs_milestone'){
  // A gilded harvest sickle, grain sheaves and little earned coin charms.
  place(1842,420,1.05,-.22+Math.sin(t*.6)*.035,()=>{line([[0,-27],[0,84]],gold,5,.85);const path=arc(9,-24,43,67,3.1,6.05);o.ribbon(path,{width:15,color:ice,secondary:gold,phase:t*.2,alpha:.8});line([[0,61],[-11,61],[11,61]],ice,1.2,.6);ring(0,91,8,7,gold,1.5,.8);});
  for(let j=0;j<9;j++){const y=231+j*57;place(46,y,.72,Math.sin(t*.45+j)*.065,()=>{line([[0,29],[0,-34]],gold,1.2,.72);for(let n=0;n<4;n++){w.petal(-8,-26+n*12,10,gold,-.65,.75);w.petal(8,-26+n*12,10,mint,.65,.68);}},j*.02);}
  for(let j=0;j<16;j++){const x=350+j*78;coin(x,1056,.41,Math.sin(t*.5+j)*.1,j*.014);}
  for(let j=0;j<3;j++)wake(u=>[325+u*1260,37+j*13+Math.sin(u*11-t*.4+j)*7],j%2?mint:gold,j*.15,1.7,.23);
 }else{
  // A real ward-like lookout lens pivots while a scan reveals tiny sentinel lights.
  place(74,432,1.04,Math.sin(t*.5)*.03,()=>{poly([[-17,75],[-13,21],[13,21],[17,75]],metal([-17,21,17,75],['#c9ccb9','#567e96','#a2b8c0']),.92);poly([[-34,8],[-27,-46],[0,-69],[28,-46],[34,8],[16,27],[-16,27]],metal([-34,-69,34,27],['#d5d9cc','#526c8b','#9eabc6','#365c7b']),.87);poly([[-26,-24],[0,-43],[26,-24],[0,-7]],'#325475',.7);o.orb(Math.sin(t*.8)*5,-25,12,mint,t*.4,{glass:true,flat:.79});line([[-27,-46],[0,-69],[28,-46]],gold,1.2,.75);ring(0,78,31,9,ice,1.4,.7);});
  for(let j=0;j<4;j++)wake(arc(74,412,39+j*15,91+j*32,.6,5.2),j%2?ice:mint,j*.14,1.6,.18);
  for(let j=0;j<9;j++){const y=225+j*62;place(1871,y,1,0,()=>{poly([[-14,0],[0,-10],[14,0],[0,10]],mint,.17);o.orb(0,0,4,ice,t*.5);line([[-14,0],[0,-10],[14,0]],gold,1,.63);},j*.025);}
  for(let j=0;j<14;j++){const x=350+j*88;ring(x,46,9,5,mint,1,.56);wake(arc(x,46,9,5),ice,j*.021,1.3,.24);}
  for(let j=0;j<3;j++)wake(u=>[330+u*1250,1060-j*7+Math.sin(u*9+j)*5],mint,j*.17,1.4,.2);
 }
 c.restore();return true;
}

// Match milestones. Pictures retain their existing owner; these decorate their edges.
function lifecyclePerformance(c,e){
 if(!['game_start','minions_spawning','victory','defeat','game_end'].includes(e.key))return false;
 const ink=eventInk(c,e),{w,o,t,p,line,poly,metal,place,arc,wake,shard,ring,motes}=ink,{helmet,book,shield}=eventProps(ink);
 const ice='#c0e3ef',gold='#e8cc92',mint='#aedcbd',violet='#bfaee0';
 c.save();
 if(e.key==='game_start'){
  // Two summoning pillars reveal little allied heralds and a ceremonial entry key.
  for(const [x,sgn]of [[55,1],[1865,-1]])place(x,437,1,0,()=>{
   poly([[-24,-104],[24,-104],[31,88],[-31,88]],metal([-31,-104,31,88],['#d4d9c4','#5d7c98','#a8b9c8','#3c5f7c']),.84);line([[sgn*18,-97],[sgn*18,77]],gold,1.4,.8);for(let j=0;j<7;j++){shard(0,-75+j*24,8,j%2?ice:violet,.1);line([[-17,-66+j*24],[17,-66+j*24]],ice,.8,.45);}ring(0,96,42,11,gold,1.3,.72);
  });
  for(let j=0;j<5;j++){const x=494+j*237;helmet(x,55,.44,-.1+j*.04,ice,j*.023);}
  for(let j=0;j<4;j++)wake(u=>[315+u*1290,1063-j*8-Math.sin(u*Math.PI)*13],j%2?gold:violet,j*.13,1.8,.25);
  motes(30,4,.085,(u,j,r,a)=>w.star(j%2?1880:37,975-u*754,2+r*3,ice,a*.65));
 }else if(e.key==='minions_spawning'){
  // Little armored and caster minions take an uneven march along the lower lane.
  for(let j=0;j<13;j++){const x=335+j*99+smooth(p)*34,y=1049+Math.sin(t*3+j*.8)*3;
   place(x,y,.41,Math.sin(t*3+j)*.05,()=>{
    if(j%3===0){poly([[-15,10],[-20,-8],[0,-38],[20,-8],[15,10]],violet,.4);o.orb(0,-12,7,ice,t*.5);line([[17,-17],[17,29]],gold,2,.8);shard(17,-22,7,violet,.1);}else{helmet(0,-12,.7,.02,j%2?gold:ice);poly([[-13,0],[13,0],[18,18],[-18,18]],metal([-18,0,18,18],['#bacfcd','#526b89','#a8b8cb']),.81);shield(-18,6,.38,-.1,ice);}
    const gait=Math.sin(t*5+j*.8)*6;line([[-7,18],[-10-gait,29]],ice,3,.8);line([[7,18],[10+gait,29]],ice,3,.8);
   },j*.013);
  }
  for(let j=0;j<7;j++){const y=235+j*71;place(40,y,.74,Math.sin(t*.6+j)*.055,()=>{line([[-17,-24],[-17,27]],gold,1.1,.71);poly([[-17,-24],[20,-19+Math.sin(t+j)*2],[13,11],[-17,5]],j%2?ice:violet,.22);line([[-17,-24],[20,-19+Math.sin(t+j)*2]],ice,1,.6);},j*.021);}
  for(let j=0;j<8;j++){const y=239+j*62;shard(1878,y,8+j%3*2,ice,j*.3);}
  wake(u=>[320+u*1270,43+Math.sin(u*11-t*.4)*8],violet,0,1.6,.23);
 }else if(e.key==='victory'){
  // A gold cup, moving laurel branches, foil ribbons and champion's pennants.
  place(75,411,1.03,-.06,()=>{
   poly([[-30,-61],[30,-61],[26,-11],[10,10],[-10,10],[-26,-11]],metal([-30,-61,30,10],['#fae5b4','#988d72','#dbc69b','#5f7485']),.94);for(const side of [-1,1]){const path=arc(side*28,-38,16,21,-1.57,1.57);o.ribbon(path,{width:6,color:gold,secondary:ice,phase:t*.25,alpha:.8});}line([[0,10],[0,47]],gold,7,.87);poly([[-27,47],[27,47],[32,59],[-32,59]],metal([-32,47,32,59],['#dbcda4','#788c9a','#edddb4']),.9);shard(0,-31,13,ice,.1);line([[-22,-52],[22,-52]],ice,1.2,.78);
  });
  for(const side of [0,1]){const x=side?1894:19,sgn=side?-1:1,path=u=>[x+sgn*Math.sin(u*5-t*.06)*18,873-u*652];wake(path,gold,side*.18,1.6,.26);for(let j=0;j<15;j++){const [xx,y]=path(j/15);w.petal(xx+sgn*12,y,15, j%3?gold:mint,sgn*(-.65)+Math.sin(t*.4+j)*.055,.69);}}
  for(let j=0;j<11;j++){const x=371+j*115;place(x,48,1,Math.sin(t*.6+j)*.04,()=>{line([[-15,-24],[-15,23]],gold,.9,.67);poly([[-15,-21],[19,-21+Math.sin(t+j)*3],[13,16],[0,10],[-15,16]],gold,.25);shard(0,-4,6,ice,0);},j*.014);}
  for(let j=0;j<3;j++)o.ribbon(u=>[310+u*1290,1061-j*8+Math.sin(u*12-t*.5+j)*6],{width:5,color:gold,secondary:ice,phase:t*.3+j,glass:true,alpha:.49});
  motes(32,4.3,.075,(u,j,r,a)=>w.petal(j%2?1866:51,204+u*633,4+r*7,gold,j*.5+u,a*.7));
 }else if(e.key==='defeat'){
  // A torn silver standard, dimming lamps and a few persistent blue fireflies.
  place(1857,412,1.05,.07,()=>{
   line([[-18,-92],[-18,94]],gold,2,.72);poly([[-18,-84],[32,-78+Math.sin(t*.6)*3],[26,-12],[9,-19],[16,-4],[-3,-10],[-18,3]],metal([-18,-84,32,3],['#b9c5d9','#758499','#b1c0c9','#3b5771']),.62);line([[-18,-84],[32,-78+Math.sin(t*.6)*3]],ice,1,.65);shard(-18,-98,8,ice,.03);ring(-18,99,22,6,ice,1,.4);
  });
  for(let j=0;j<7;j++){const y=240+j*67;place(43,y,.68,Math.sin(t*.5+j)*.04,()=>{poly([[-17,-21],[17,-21],[13,21],[-13,21]],ice,.13);line([[-17,-21],[-13,21],[13,21],[17,-21]],ice,1,.62);w.mist(0,0,15,21,ice,.22*(1-p)+.05);ring(0,-28,6,7,gold,.9,.58);},j*.018);}
  for(let j=0;j<3;j++)wake(u=>[1560-u*1230,1062-j*9+Math.sin(u*8+j)*5],ice,j*.2,1.2,.27);
  for(let j=0;j<13;j++){const x=360+j*91;w.petal(x,41+Math.sin(t*.3+j)*5,7,ice,-.4+j*.07,.47);}
  motes(22,4.3,.115,(u,j,r,a)=>w.star(j%2?1879+Math.sin(j+u*7)*18:43+Math.sin(j+u*5)*20,900-u*652,1+r*2,ice,a*.54));
 }else{
  // The final folio closes; tiny paper stars leave through a hanging keyhole.
  const q=smooth((p-.05)/.74);book(77,439,1-q*.35,-.06,violet);
  place(1857,437,1,0,()=>{ring(0,-22,29,38,gold,1.7,.72);poly([[-10,4],[10,4],[14,52],[-14,52]],ice,.2);o.orb(0,-22,12,violet,t*.3,{glass:true});line([[-14,52],[14,52]],gold,1.1,.64);});
  for(let j=0;j<12;j++){const x=371+j*96;place(x,50,1,Math.sin(t*.5+j)*.07,()=>{poly([[-11,-12],[11,-12],[11,12],[-11,12]],ice,.13);line([[-8,-6],[7,-6]],gold,.8,.55);line([[-8,0],[5,0]],violet,.8,.5);},j*.018);}
  for(let j=0;j<3;j++)wake(u=>[330+u*1250,1061-j*9+Math.sin(u*9+j)*7],j%2?ice:violet,j*.16,1.5,.24);
  motes(25,4,.095,(u,j,r,a)=>w.star(1869+Math.sin(j+u*4)*24,933-u*710,2+r*2,gold,a*.6));
 }
 c.restore();return true;
}

// Optional inferred signals remain tentative. Artwork never upgrades their confidence.
function inferencePerformance(c,e){
 if(!e.key?.startsWith('possible_'))return false;
 const ink=eventInk(c,e),{w,o,t,p,line,poly,metal,place,arc,wake,shard,ring,motes}=ink,{coin,vial,blade,heart,shield,book}=eventProps(ink);
 const ice='#b2dfea',gold='#dfc68e',mint='#a5d5b9',violet='#c2abe1';
 c.save();c.globalAlpha*=.86;
 switch(e.key){
 case 'possible_purchase':{
  // A merchant purse with a few tentative coins, no receipt or purchase claim.
  place(1847,445,1,0,()=>{poly([[-24,-31],[-14,-48],[14,-48],[24,-31],[34,23],[17,45],[-17,45],[-34,23]],metal([-34,-48,34,45],['#c9c2a6','#5f8096','#a4a1b3','#405e7b']),.88);line([[-23,-28],[23,-28]],gold,2,.7);line([[-5,-28],[-11,-52]],ice,1,.6);line([[5,-28],[13,-53]],ice,1,.6);coin(0,6,.57,.05);});
  for(let j=0;j<9;j++)coin(42,242+j*64,.42,Math.sin(t*.5+j)*.13,j*.022);
  for(let j=0;j<12;j++){const x=370+j*94;ring(x,1059,7,8,gold,1,.53);}
  for(let j=0;j<2;j++)wake(u=>[330+u*1250,39+j*15+Math.sin(u*11+j)*7],j?ice:gold,j*.2,1.6,.22);break;
 }
 case 'possible_item_upgrade':{
  // A jeweller's small hammer checks a faceted stone on a floating forge.
  place(73,448,1,0,()=>{poly([[-38,34],[38,34],[27,56],[-27,56]],metal([-38,34,38,56],['#c9c9b5','#627f93','#acbac6']),.84);shard(0,8,27,violet,.02);const a=-.45+Math.sin(t*1.2)*.14;c.save();c.translate(12,-52);c.rotate(a);line([[0,-20],[0,43]],gold,4,.8);poly([[-23,-32],[23,-32],[23,-12],[-23,-12]],metal([-23,-32,23,-12],['#d8d8c5','#5c7d96','#bcc6ce']),.88);c.restore();});
  for(let j=0;j<9;j++){const y=239+j*63;shard(1873,y,9+j%3*2,violet,j*.4);ring(1873,y,16,7,ice,1,.49);}
  for(let j=0;j<3;j++)wake(u=>[330+u*1250,1059-j*8+Math.sin(u*10+j)*6],j%2?gold:violet,j*.16,1.5,.21);break;
 }
 case 'possible_consumable_use':{
  // Cork, vial and botanical vapor make a small apothecary moment.
  vial(1852,438,1.04,-.12,mint);place(1837,370-smooth(p)*22,.9,-.2-p*.2,()=>{poly([[-10,-7],[10,-7],[9,8],[-9,8]],gold,.78);line([[-8,-2],[8,-2]],ice,.8,.53);});
  for(let j=0;j<3;j++)wake(u=>[1856+Math.sin(u*9-t*.5+j)*12,417-u*172],j%2?ice:mint,j*.16,1.4,.21);
  for(let j=0;j<8;j++){const y=235+j*71;w.petal(42,y,13,mint,-.6+Math.sin(t*.5+j)*.08,.61);shard(42,y,4,gold,.1);}
  for(let j=0;j<13;j++){const x=350+j*92;ring(x,1059,6,7,mint,1,.53);}break;
 }
 case 'possible_base_visit':{
  // A little home gate, hanging key and replenishment lanterns suggest a return.
  place(75,444,1,0,()=>{poly([[-33,49],[-33,-51],[0,-78],[33,-51],[33,49]],metal([-33,-78,33,49],['#c7d5c8','#5e7d92','#a7b4c7']),.8);poly([[-19,45],[-19,-30],[0,-47],[19,-30],[19,45]],ice,.18);line([[-19,-30],[0,-47],[19,-30]],gold,1.2,.65);ring(8,6,4,4,gold,1.3,.7);});
  for(let j=0;j<7;j++){const y=249+j*67;place(1870,y,.7,Math.sin(t*.5+j)*.08,()=>{ring(0,-10,10,11,gold,1.3,.7);line([[0,0],[0,22],[9,22],[9,16]],ice,2,.7);},j*.022);}
  for(let j=0;j<3;j++)wake(u=>[1570-u*1240,1059-j*8-Math.sin(u*Math.PI)*18],j%2?gold:ice,j*.16,1.5,.23);break;
 }
 case 'possible_combat':{
  // One partially drawn blade beside a scabbard and a few restrained clash rings.
  const q=smooth(p);blade(1849,414-q*15,.85,.25,ice);place(1866,475,1,.25,()=>{poly([[-9,-31],[9,-31],[9,43],[0,59],[-9,43]],metal([-9,-31,9,59],['#8092aa','#344f71','#a0aec0']),.74);line([[-11,-32],[11,-32]],gold,2,.7);});
  for(let j=0;j<7;j++){const y=242+j*70;ring(42,y,13,17,violet,1,.55);wake(arc(42,y,13,17),ice,j*.07,1.4,.19);}
  for(let j=0;j<2;j++)wake(u=>[330+u*1250,40+j*15+Math.sin(u*9+j)*7],j?gold:ice,j*.2,1.5,.2);break;
 }
 case 'possible_low_hp_escape':{
  // A paper bird carries a small heart toward the outside of the right edge.
  const q=smooth((p-.03)/.76),x=1842+q*47,y=472-q*164;
  place(x,y,.83,-.27,()=>{const flap=Math.sin(t*3)*6;poly([[-32,3],[0,-17],[38,-8],[12,12],[-3,7],[-18,32]],metal([-32,-17,38,32],['#d3e5e0','#778caa','#c2cad7']),.8);poly([[-4,-11],[-29,-34-flap],[-8,12]],ice,.48);poly([[7,-7],[32,-31+flap],[15,11]],violet,.4);line([[-3,7],[-13,29]],gold,.9,.7);heart(-13,36,.2,.08,'#dda4ba');});
  for(let j=0;j<8;j++){const y=240+j*70;poly([[35,y-8],[47,y],[35,y+8],[42,y]],ice,.45);}
  for(let j=0;j<3;j++)wake(u=>[1863-j*10+Math.sin(u*6+j)*7,844-u*591],j%2?gold:ice,j*.15,1.5,.19);wake(u=>[330+u*1250,1059+Math.sin(u*9)*6],violet,0,1.4,.2);break;
 }
 case 'possible_teamfight':{
  // Allied shield pennants gather around a glass rendezvous knot.
  for(let j=0;j<4;j++){const y=281+j*102;shield(46,y,.52,Math.sin(t*.5+j)*.07,j%2?mint:ice,j*.023);shield(1873,y+31,.43,-.1,j%2?violet:gold,j*.027);}
  for(let j=0;j<3;j++)wake(u=>[325+u*1270,1057+Math.sin(u*12+j*TAU/3)*11],j===1?gold:ice,j*.15,1.5,.22);
  for(let j=0;j<11;j++){const x=370+j*112;place(x,47,1,0,()=>{ring(0,0,12,8,mint,1,.53);ring(7,0,12,8,violet,1,.53);},j*.019);}break;
 }
 case 'possible_objective_fight':{
  // Two opposing pit gates face a small suspended objective crystal.
  for(const[x,sgn]of [[40,1],[1880,-1]])place(x,440,1,0,()=>{for(let j=0;j<5;j++){const y=-94+j*43;poly([[0,y],[sgn*27,y-10],[sgn*35,y+19],[0,y+31]],metal([0,y,sgn*35,y+31],['#bdb0cf','#4c647e','#9884af']),.76);line([[sgn*5,y+4],[sgn*23,y-3]],ice,.9,.6);}shard(sgn*39,0,24,violet,.05);});
  for(let j=0;j<11;j++){const x=350+j*117;shard(x,50,8,j%2?gold:ice,.15);}
  for(let j=0;j<3;j++)wake(u=>[320+u*1280,1059-j*8+Math.sin(u*12+j)*8],j%2?gold:violet,j*.15,1.6,.21);break;
 }
 case 'possible_power_spike':{
  // A charged prism and ascending instrument needles hint at a new power window.
  place(1848,438,1,0,()=>{shard(0,0,49,violet,.04);for(let j=0;j<3;j++)wake(arc(0,0,35+j*11,64+j*15),j%2?gold:ice,j*.15,1.6,.19);line([[-29,76],[29,76]],gold,2,.72);});
  for(let j=0;j<8;j++){const y=244+j*65;place(43,y,.74,0,()=>{ring(0,0,16,23,ice,1,.6);line([[0,0],[10*Math.sin(p+1),-18*Math.cos(p+1)]],gold,1.5,.8);shard(0,0,4,violet,.1);},j*.023);}
  for(let j=0;j<3;j++)wake(u=>[330+u*1250,38+j*13+Math.sin(u*Math.PI)*18],j%2?violet:gold,j*.15,1.6,.24);break;
 }
 case 'possible_roam':{
  // A compass on a folded map and travelling footprint lights along an unequal route.
  place(77,437,1,0,()=>{poly([[-44,-30],[-15,-40],[15,-29],[44,-39],[44,32],[15,42],[-15,31],[-44,41]],metal([-44,-40,44,42],['#d8d4b5','#8b9aa5','#d0c9b5','#627c95']),.73);line([[-15,-40],[-15,31]],gold,.9,.6);line([[15,-29],[15,42]],gold,.9,.6);ring(0,0,27,31,ice,1.5,.75);const a=-.3+t*.18;line([[Math.sin(a)*16,-Math.cos(a)*23],[-Math.sin(a)*16,Math.cos(a)*23]],violet,3,.75);shard(0,0,5,gold,0);});
  for(let j=0;j<9;j++){const y=240+j*63;place(1871+Math.sin(j)*12,y,.7,(j%2?1:-1)*.15,()=>{ring(0,-3,5,9,ice,1,.58);ring(0,12,5,4,gold,1,.58);},j*.022);}
  wake(pathOf([[335,1064],[625,1064],[655,1044],[1160,1044],[1190,1064],[1590,1064]]),ice,0,1.7,.24);for(let j=0;j<12;j++){const x=375+j*93;w.star(x,44+Math.sin(j*.6)*9,3,gold,.5);}break;
 }
 case 'possible_jungle_activity':{
  // A lantern among mushrooms, leaves and individually born forest fireflies.
  place(1853,430,1,Math.sin(t*.5)*.045,()=>{line([[0,-100],[0,-58]],gold,.9,.6);ring(0,-53,9,9,gold,1.2,.7);poly([[-24,-32],[24,-32],[19,33],[-19,33]],ice,.18);line([[-24,-32],[-19,33],[19,33],[24,-32]],gold,1.2,.67);w.mist(0,4,24,38,mint,.5);shard(0,5,12,mint,.05);});
  for(let j=0;j<7;j++){const y=250+j*68;place(46,y,.78,Math.sin(t*.4+j)*.045,()=>{line([[0,-3],[0,27]],gold,4,.72);poly([[-22,-4],[-13,-21],[3,-27],[21,-14],[24,-4]],metal([-22,-27,24,-4],['#c8d7ba','#668b8a','#b6c79e']),.77);ring(-7,-13,3,2,ice,1,.55);ring(9,-12,4,2,ice,1,.55);},j*.02);}
  for(let j=0;j<16;j++){const x=350+j*80;w.petal(x,1059+Math.sin(t*.4+j)*5,10,mint,-.4+j*.05,.6);}
  motes(26,4,.09,(u,j,r,a)=>w.star(j%2?1868+Math.sin(j+u*6)*24:43+Math.sin(j+u*4)*26,939-u*716,1+r*2,mint,a*.7));break;
 }
 default:c.restore();return false;
 }
 c.restore();return true;
}

export const artReady=Promise.resolve();
export function eventRelics(c,e){
 return elementalPerformance(c,e)||voidPerformance(c,e)||structurePerformance(c,e)||
  combatPerformance(c,e)||vitalPerformance(c,e)||progressPerformance(c,e)||
  economyPerformance(c,e)||lifecyclePerformance(c,e)||inferencePerformance(c,e);
}
export function soulRelics(c,death){soulPerformance(c,death);}
