'use strict';
// Analysis presentation uses public HTTP actions; source review remains in app.js.
let analysisCatalogue={games:[],replays:[],analyzed:[]}, analysisBusy=false, analysisPage=0;
const analysisPageSize=30;
const rankingNames={victory:'Victory',speaking:'Speaking activity',voice_spikes:'Voice spikes',early_kda:'Early kills / assists'};
const rankingWeights=JSON.parse(localStorage.getItem('footage-ranking-weights')||'{"victory":1,"speaking":1,"voice_spikes":1,"early_kda":1}');
$('ranking-controls').innerHTML=Object.entries(rankingNames).map(([key,label])=>`<label><input type="checkbox" data-metric="${key}" ${rankingWeights[key]>0?'checked':''}> ${label}<input type="number" aria-label="${label} weight" data-weight="${key}" min="0" max="10" step="0.5" value="${rankingWeights[key]||1}"></label>`).join('');
function analysisWeights(){const values={};for(const key of Object.keys(rankingNames))values[key]=document.querySelector(`[data-metric="${key}"]`).checked?Number(document.querySelector(`[data-weight="${key}"]`).value):0;return values;}
async function refreshAnalysis(){if(analysisBusy)return;analysisBusy=true;try{analysisCatalogue=await api('/api/analysis?weights='+encodeURIComponent(JSON.stringify(analysisWeights())));renderAnalysis();}finally{analysisBusy=false;}}
function renderAnalysis(){
  const current=analysisCatalogue.analyzed.filter(a=>!a.stale).length, outdated=analysisCatalogue.analyzed.length-current;
  $('analysis-summary').textContent=`${current} / ${analysisCatalogue.candidate_count} eligible recordings analyzed${outdated?` · ${outdated} awaiting refresh`:''} · ${analysisCatalogue.games.filter(g=>!g.stale).length} current games · ${analysisCatalogue.replays.filter(r=>!r.stale).length} current replays`;
  const query=$('analysis-search').value.toLowerCase(),outcome=$('analysis-outcome').value;
  const games=analysisCatalogue.games.filter(g=>(!query||[g.source_name,g.source_path,g.outcome].join(' ').toLowerCase().includes(query))&&(!outcome||g.outcome===outcome));
  analysisPage=Math.min(analysisPage,Math.max(0,Math.ceil(games.length/analysisPageSize)-1));
  const pageStart=analysisPage*analysisPageSize;
  $('analysis-page-label').textContent=games.length?`Games ${pageStart+1}–${Math.min(games.length,pageStart+analysisPageSize)} of ${games.length}`:'No matching games';
  $('analysis-prev').disabled=analysisPage===0;$('analysis-next').disabled=pageStart+analysisPageSize>=games.length;
  $('detected-games').innerHTML=games.slice(pageStart,pageStart+analysisPageSize).map(g=>`<article class="detected-game"><div class="game-score">${g.score.toFixed(1)}<small>score</small></div><div class="game-details"><strong>${escape(g.source_name)} · Game ${g.index+1}</strong><p>${time(g.start)} → ${time(g.end)} · <span class="badge ${g.outcome==='victory'?'keep':g.outcome==='defeat'?'reject':''}">${escape(g.outcome)}</span> · ${(g.confidence*100).toFixed(0)}% boundary confidence${g.partial_start||g.partial_end?' · Incomplete boundary':''}${g.stale?' · Analysis outdated — reanalyze':''}</p><p>${g.metrics.speaking_seconds===undefined?'Speech not analyzed':`${time(g.metrics.speaking_seconds)} speaking · ${(100*g.metrics.speaking_fraction).toFixed(1)}% activity · ${g.metrics.spike_count} voice spikes · +${g.metrics.strongest_spike_db.toFixed(1)} dB strongest`} · ${g.metrics.early_kda?'Early KDA flag':'No early KDA flag'}</p><small class="muted">${escape(g.audio_label||'')} · IN/OUT includes 60 seconds each side, clamped to source.</small><div class="actions"><button data-game-play="${g.video_id}:${g.index}">▶ Review game</button><button data-game-keep="${g.video_id}:${g.index}" ${g.stale?'disabled':''}>Keep buffered game</button><button data-game-export="${g.video_id}:${g.index}" ${g.stale||g.availability!=='online'?'disabled':''}>Extract game</button></div><details><summary>${g.moments.length} interesting snippets · boundary evidence</summary><p>${escape(g.start_reason)} / ${escape(g.end_reason)}</p>${g.moments.map((m,i)=>`<button data-moment-play="${g.video_id}:${g.index}:${i}">${time(m.time)} · ${escape(m.label)}${m.above_baseline_db!==undefined?' +'+m.above_baseline_db.toFixed(1)+' dB':''}</button>`).join('')}</details></div></article>`).join('')||'<p class="muted">Analyze a recording to discover games. Completed recordings appear here while the queue continues.</p>';
  $('detected-replays').innerHTML=analysisCatalogue.replays.map((r,i)=>`<div class="replay-row"><span>${escape(r.source_name)} · ${r.kind==='browser_playback'?'Browser clip playback':'Instant Replay'} · ${time(r.start)}–${time(r.end)}</span><button data-replay-play="${i}">Review</button><button data-replay-mark="${i}" ${r.stale?'disabled':''}>Mark deletion candidate</button></div>`).join('')||'<p class="muted small">Replay sections are excluded from game progression, early KDA flags and speech scores.</p>';
}
$('show-analysis').onclick=()=>{$('analysis-panel').hidden=!$('analysis-panel').hidden;if(!$('analysis-panel').hidden){player.pause();$('workspace').hidden=true;$('workflow-panel').hidden=true;$('empty').hidden=true;action(refreshAnalysis);}else workflow?.render();};
$('close-analysis').onclick=()=>{$('analysis-panel').hidden=true;workflow?.render();};
$('ranking-controls').onchange=()=>action(async()=>{analysisPage=0;localStorage.setItem('footage-ranking-weights',JSON.stringify(analysisWeights()));await refreshAnalysis();});
function resetAnalysisPage(){analysisPage=0;renderAnalysis();}
$('analysis-search').oninput=resetAnalysisPage;$('analysis-outcome').onchange=resetAnalysisPage;
$('analysis-prev').onclick=()=>{analysisPage=Math.max(0,analysisPage-1);renderAnalysis();};$('analysis-next').onclick=()=>{analysisPage++;renderAnalysis();$('analysis-pager').scrollIntoView({behavior:'smooth',block:'start'});};
async function queueAnalysis(ids){const payload={sample_seconds:Number($('analysis-interval').value),audio:true,audio_track:$('analysis-audio').value,force:$('analysis-force').checked};if(ids)payload.ids=ids;await api('/api/analyze',payload);notify('Game analysis queued. Completed results appear as each recording finishes.');await refresh();}
$('analyze-selected').onclick=()=>action(async()=>{if(!selected)throw Error('Choose a recording first');await queueAnalysis([selected.id]);});
$('analyze-library').onclick=()=>action(()=>queueAnalysis());
async function reviewDetection(g,start,end){navigateView('library');await reviewSourceRange(g.video_id,start,end);}
$('detected-games').onclick=e=>action(async()=>{const b=e.target.closest('button');if(!b)return;const raw=b.dataset.gamePlay||b.dataset.gameKeep||b.dataset.gameExport||b.dataset.momentPlay;if(!raw)return;const [videoId,index,moment]=raw.split(':').map(Number),g=analysisCatalogue.games.find(g=>g.video_id===videoId&&g.index===index);if(b.dataset.gamePlay)await reviewDetection(g,g.trim_start,g.trim_end);if(b.dataset.momentPlay){const m=g.moments[moment];await reviewDetection(g,m.start,m.end);}if(b.dataset.gameKeep||b.dataset.gameExport){const kept=await api('/api/analysis-keep',{video_id:videoId,index});if(b.dataset.gameExport)await api('/api/export',{ids:[kept.id],padding:0,mode:$('export-mode').value});await refresh();notify(b.dataset.gameExport?'Buffered game extraction queued. Source metadata is retained.':'Buffered game saved as a keeper.');}});
$('detected-replays').onclick=e=>action(async()=>{const b=e.target.closest('button');if(!b)return;const r=analysisCatalogue.replays[Number(b.dataset.replayPlay??b.dataset.replayMark)];if(b.dataset.replayPlay!==undefined)await reviewDetection(r,r.start,r.end);if(b.dataset.replayMark!==undefined){const index=analysisCatalogue.replays.filter(x=>x.video_id===r.video_id).indexOf(r);await api('/api/analysis-replay',{video_id:r.video_id,index});await refresh();notify('Replay marked as a deletion candidate.');}});
$('analysis-csv').onclick=()=>{const rows=[['source_path','source_id','game_start','game_end','buffered_start','buffered_end','outcome','score','speaking_seconds','speaking_fraction','spike_count','early_kda'],...analysisCatalogue.games.map(g=>[g.source_path,g.video_id,g.start,g.end,g.trim_start,g.trim_end,g.outcome,g.score,g.metrics.speaking_seconds,g.metrics.speaking_fraction,g.metrics.spike_count,g.metrics.early_kda])];const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='detected-games.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
setInterval(()=>{if(!$('analysis-panel').hidden)action(refreshAnalysis);},8000);
