import {esc} from '../utils.js';
import {toast} from '../toast.js';
import {createTools} from './league-stats-tools.js';
let root=null,timer=null,epoch=0,busy=false,settingsLoaded=false,tools=null;
const url='/api/league-stats', $=id=>root?.querySelector('#'+id);
const n=(v,d=0)=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
const label=k=>k.replaceAll('_',' ').replace(/\bcs\b/gi,'CS');
const duration=s=>s==null?'—':`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
async function request(path=url,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
function filters(){return new URLSearchParams({period:$('lsPeriod')?.value||'all',champion:$('lsChampion')?.value||'',queue:$('lsQueue')?.value||'',session_id:$('lsPeriod')?.value==='session'?$('lsSession')?.value||'':'',...($('lsAccount')?.value?{account:$('lsAccount').value}:{})}).toString();}
const card=(title,value,sub='')=>`<div class="card" style="padding:18px"><div style="color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.06em">${esc(title)}</div><div style="font-size:28px;margin:6px 0;font-variant-numeric:tabular-nums">${esc(value)}</div><div style="color:var(--muted);font-size:12px">${esc(sub)}</div></div>`;
function table(headers,rows){return `<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;text-align:left"><thead><tr>${headers.map(h=>`<th style="padding:10px;border-bottom:1px solid var(--line);color:var(--muted)">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td style="padding:10px;border-bottom:1px solid var(--line)">${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
export async function mount(container){
 root=container;const token=++epoch;settingsLoaded=false;
 root.innerHTML=`<div class="page-header"><div><div class="page-title">League Stats</div><div class="page-subtitle">Every game adds to your personal record. Trusted viewers fill in the misses.</div></div><a class="btn" href="/league-stats/overlay.html" target="_blank">Stream overlay ↗</a></div>
 <div class="card" style="margin-bottom:16px"><p id="lsStatus" role="status">Connecting to tracker…</p><p id="lsSync" style="color:var(--muted)"></p><div style="display:flex;gap:10px;flex-wrap:wrap"><label>Period <select id="lsPeriod" class="input"><option value="all">All recorded</option><option value="today">Today</option><option value="session">Saved stream session</option></select></label><label>Champion <select id="lsChampion" class="input"><option value="">All champions</option></select></label><label>Queue <select id="lsQueue" class="input"><option value="">All queues</option></select></label><label>Account <select id="lsAccount" class="input"><option value="">Current account</option></select></label><button class="btn" id="lsImport">Import recent 100 games</button><a class="btn" id="lsExport" href="${url}/export" download>Export JSON</a></div></div>
 <div id="lsCards" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-bottom:18px"></div>
 <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,340px),1fr));gap:18px;margin-bottom:18px;align-items:start">
 <section class="card"><div class="card-title">Current game</div><div id="lsLive"></div></section>
 <section class="card"><div class="card-title">Viewer helpers</div><p><code>!melee</code> · <code>!range</code> · <code>!cannon</code> · <code>!statundo</code></p><p style="color:var(--muted)">Only your broadcaster account, allowed moderators, and named helpers can count a miss. The shared cooldown prevents duplicate reports.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" data-miss="missed_melee">+ Melee</button><button class="btn" data-miss="missed_ranged">+ Ranged</button><button class="btn" data-miss="missed_cannon">+ Cannon</button><button class="btn" data-miss="nexus_last_hits_manual">+ Nexus last hit</button><button class="btn" id="lsUndo">Undo last entry</button></div><p id="lsHelper" role="status"></p><details><summary>Helper permissions &amp; preferences</summary><label style="display:block;margin:12px 0">Named helpers (Twitch login names, comma separated)<input id="lsHelpers" class="input" style="width:100%;margin-top:6px" placeholder="trusted_viewer, another_helper"></label><label style="display:block;margin:12px 0"><input id="lsMods" type="checkbox" style="width:auto;margin-right:8px"> Allow Twitch moderators</label><label style="display:block;margin:12px 0"><input id="lsEnabled" type="checkbox" style="width:auto;margin-right:8px"> Enable observations</label><label>Shared cooldown <input id="lsCooldown" class="input" type="number" min="5" max="60" style="width:80px"> seconds</label><label style="display:block;margin:12px 0"><input id="lsCustom" type="checkbox" style="width:auto;margin-right:8px"> Include custom / practice games in summaries</label><label>Riot platform <input id="lsRegion" class="input" style="width:90px" placeholder="na1"></label><p style="color:var(--muted)">Local tracking needs no API key. Optional Match-v5 enrichment reads RIOT_API_KEY from the Hub environment.</p><button class="btn" id="lsSave">Save preferences</button></details></section></div>
 <section class="card" style="margin-bottom:18px"><div class="card-title">Win rates by matchup</div><select id="lsBreakdown" class="input" style="margin:12px 0"><option value="enemy_adc">Enemy ADC</option><option value="ally_support">Your support</option><option value="enemy_support">Enemy support</option><option value="ally_adc">Your ADC</option><option value="champion">Your champion</option></select><p style="color:var(--muted)">Roles come from reported lane assignments. Unknown or ambiguous roles are excluded. These are your recorded results; small samples do not predict a matchup.</p><div id="lsMatchups"></div></section>
 <section class="card" style="margin-bottom:18px"><div class="card-title">All tracked statistics</div><p style="color:var(--muted)">Totals include saved live and partial observations. Per-game averages use completed games with that field. Coverage shows how many games reported it; a missing stat stays unknown.</p><div id="lsMetrics"></div></section>
 <section class="card" style="margin-bottom:18px"><div class="card-title">Items you finish with</div><p style="color:var(--muted)">Final inventory frequency and observed win rate. Item appearances during the game are saved separately as observations, since upgrades and transformations are not always purchases.</p><div id="lsItems"></div></section>
 <section class="card"><div class="card-title">Recent matches</div><div id="lsMatches"></div><p id="lsArchive" style="color:var(--muted);overflow-wrap:anywhere"></p><p style="color:var(--muted)">Streaming Hub is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games. Riot Games and League of Legends are trademarks or registered trademarks of Riot Games, Inc.</p></section>`;
 tools=createTools(root,request,refresh);
 for(const id of ['lsPeriod','lsChampion','lsQueue','lsAccount'])$(id).onchange=()=>refresh();
 root.querySelectorAll('[data-miss]').forEach(b=>b.onclick=()=>act('observe',{metric:b.dataset.miss}));
 $('lsUndo').onclick=()=>act('undo',{});$('lsImport').onclick=()=>act('import',{});
 $('lsSave').onclick=async()=>{try{await request(`${url}/settings`,{...tools.preferences(),helpers:$('lsHelpers').value.split(/[\s,]+/).filter(Boolean),allow_moderators:$('lsMods').checked,helper_enabled:$('lsEnabled').checked,cooldown_seconds:Number($('lsCooldown').value),include_custom:$('lsCustom').checked,region:$('lsRegion').value.trim().toLowerCase()});toast.success('Tracker preferences saved');await refresh();}catch(e){toast.error(e.message);}};
 await refresh();if(token===epoch)timer=setInterval(refresh,2000);
}
export function unmount(){epoch++;clearInterval(timer);root=null;busy=false;}
async function act(action,body){try{const result=await request(`${url}/${action}`,body);toast.success(result.message||result.text||'Saved');await refresh();}catch(e){toast.error(e.message);}}
function options(id,values,first,labels={}){const el=$(id),value=el.value;const html=`<option value="">${esc(first)}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(labels[v]||v)}</option>`).join('');if(el.innerHTML!==html){el.innerHTML=html;el.value=value;}}
async function refresh(){
 if(!root||busy)return;busy=true;const token=epoch;
 try{const query=filters(),s=await request(url+'?'+query);if(token!==epoch||!root)return;
 tools.render(s);
 $('lsStatus').textContent=s.error?`${s.status} · ${s.error}`:s.status;$('lsSync').textContent=`${s.history_status} · ${s.chat?.status||'Chat disconnected'}`;
 options('lsChampion',s.champions,'All champions');options('lsQueue',s.queues,'All queues');options('lsAccount',s.accounts,'Current account',s.account_labels);$('lsExport').href=url+'/export?'+query;
 if(!settingsLoaded){const c=s.settings;$('lsHelpers').value=c.helpers.join(', ');$('lsMods').checked=c.allow_moderators;$('lsEnabled').checked=c.helper_enabled;$('lsCooldown').value=c.cooldown_seconds;$('lsCustom').checked=c.include_custom;$('lsRegion').value=c.region;settingsLoaded=true;}
 const a=s.summary,m=a.metrics,get=k=>m[k]?.total;
 $('lsCards').innerHTML=card('Games',n(a.completed_games),`${n(a.live_or_partial_games)} live / partial`)+card('Win rate',a.win_rate==null?'—':n(a.win_rate,1)+'%',`${a.wins} wins · ${a.losses} losses`)+card('CS / minute',n(a.cs_per_minute,2),'Total CS ÷ total completed minutes')+card('Average game',duration(a.average_game_seconds),'Completed games')+card('K / D / A in this view',`${n(get('kills'))} / ${n(get('deaths'))} / ${n(get('assists'))}`,'Recorded totals')+card('Total CS',n(get('cs')),'Recorded creep score')+card('Missed minions',n(get('missed_minions')),`${n(get('missed_melee'))} melee · ${n(get('missed_ranged'))} ranged · ${n(get('missed_cannon'))} cannon`)+card('KDA / participation',`${n(a.kda,2)} / ${n(a.kill_participation,1)}%`,'Completed games with coverage');
 const c=s.current,v=c?.metrics||{};
 $('lsLive').innerHTML=c?`<p><strong>${esc(c.champion)}</strong> · ${esc(c.connected?'Live':c.state)} · ${duration(c.duration)}</p><p style="font-size:24px">${n(v.kills)} / ${n(v.deaths)} / ${n(v.assists)}</p><p>${n(v.cs)} CS · ${n(c.cs_per_minute,2)} CS/min · ${n(v.vision_score,1)} vision</p><p>${(c.items||[]).map(i=>esc(i.name)).join(' · ')||'No items reported'}</p><p>Missed: ${n(v.missed_melee)} melee / ${n(v.missed_ranged)} ranged / ${n(v.missed_cannon)} cannon</p>`:'<p>Open League and play a game to start live tracking.</p>';
 const last=(c?.observations||[]).at(-1),remaining=last?Math.max(0,s.settings.cooldown_seconds-(Date.now()/1000-last.at)):0;
 root.querySelectorAll('[data-miss]').forEach(b=>{const recentNexus=b.dataset.miss==='nexus_last_hits_manual'&&c?.state==='complete'&&c.ended_at&&Date.now()/1000-c.ended_at<=120;b.disabled=(!c?.connected&&!recentNexus)||remaining>0||!s.settings.helper_enabled;});
 $('lsHelper').textContent=remaining>0?`Shared cooldown: ${Math.ceil(remaining)}s remaining`:s.last_helper?.text||'Ready for trusted helpers during a live game.';
 $('lsUndo').disabled=!(c?.observations||[]).some(o=>!o.undone);
 function renderBreakdown(){const rows=s.breakdowns[$('lsBreakdown').value]||[];$('lsMatchups').innerHTML=rows.length?table(['Champion','Games','W / L','Win rate','CS/min','KDA'],rows.map(r=>[esc(r.name),n(r.completed_games),`${r.wins} / ${r.losses}`,r.win_rate==null?'—':n(r.win_rate,1)+'%',n(r.cs_per_minute,2),n(r.kda,2)])):'<p>No completed games with confirmed roles in this view yet.</p>';}
 $('lsBreakdown').onchange=renderBreakdown;renderBreakdown();
 const renderMetrics=()=>{$('lsMetrics').innerHTML=Object.keys(m).length?table(['Statistic','Total / best','Per completed game','Coverage'],Object.entries(m).filter(([k])=>label(k).toLowerCase().includes($('lsMetricSearch').value.toLowerCase())).map(([k,v])=>[esc(label(k)),n(v.is_peak?v.maximum:v.total,1),v.is_peak?'—':n(v.average,2),`${v.games} reported · ${v.completed_games} completed`])):'<p>Your statistics will appear here as games are recorded or imported.</p>';};$('lsMetricSearch').oninput=renderMetrics;renderMetrics();
 $('lsItems').innerHTML=s.items.length?table(['Item','Games with item','Wins','Win rate'],s.items.map(i=>[esc(i.name),n(i.games),n(i.wins),i.win_rate==null?'—':n(i.win_rate,1)+'%'])):'<p>No completed item inventories yet.</p>';
 $('lsMatches').innerHTML=s.matches.length?s.matches.map(r=>`<details style="padding:14px 0;border-bottom:1px solid var(--line)"><summary>${esc(r.champion)} · ${r.win===true?'Win':r.win===false?'Loss':esc(r.state)} · ${duration(r.duration)} · ${n(r.metrics.kills)}/${n(r.metrics.deaths)}/${n(r.metrics.assists)} · ${n(r.metrics.cs)} CS · ${esc(new Date(r.started_at*1000).toLocaleDateString())}</summary><p>Queue ${esc(String(r.queue??'unknown'))} · ${esc(r.role||'Role unknown')} · ${esc(r.source)} · ${esc(r.patch||'')}</p><p>${Object.entries(r.matchups||{}).map(([k,v])=>`${esc(label(k))}: ${esc(v)}`).join(' · ')}</p><p>${r.items.map(i=>esc(i.name)).join(' · ')}</p><p>${(r.observations||[]).map(o=>`${esc(o.actor)}: ${esc(label(o.metric))}${o.undone?' (undone)':''} at ${duration(o.game_time)}`).join('<br>')||'No viewer observations'}</p></details>`).join(''):'<p>No matches recorded for these filters.</p>';
 $('lsArchive').textContent='Your persistent archive: '+s.archive_path;
 }catch(e){if(root&&token===epoch)$('lsStatus').textContent=e.message;}
 finally{if(token===epoch)busy=false;}
}
