import {esc} from '../utils.js';
let root=null,epoch=0,timer=0,selected='signal_found',data=null,dirty=false;
const endpoint='/api/mood-cues',previewOrigin='http://127.0.0.1:7444';
async function request(path=endpoint,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(value.error||'Could not update mood cue.');return value;}
export function beforeLeave(){return !dirty||window.confirm('Discard unsaved mood edits?');}
export async function mount(container){
 root=container;const token=++epoch;dirty=false;
 container.innerHTML=`<div class="page-header"><div><div class="desk-eyebrow">A feeling, on cue</div><h1 class="page-title">Mood cues</h1><p class="page-subtitle">Your Love Me sequence, with a whole palette of moments beside it.</p></div><button class="btn" id="mcStop">Stop cue</button></div>
 <section class="card" style="padding:16px;margin-bottom:18px;display:flex;gap:12px;align-items:center;flex-wrap:wrap"><strong>Original Love Me · 987</strong><span style="color:var(--muted)">Advance the four existing stages. Final stage toggles off.</span><button class="btn" id="mcOriginal">Next original stage</button><button class="btn" id="mcReload">Reload saved</button><span id="mcRuntime" role="status"></span></section>
 <div id="mcGallery" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px;margin-bottom:18px"></div>
 <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,420px),1fr));gap:20px;align-items:start">
 <section class="card" style="padding:18px"><div style="display:flex;justify-content:space-between;gap:12px"><h2 id="mcTitle">Choose a feeling</h2><button class="btn" id="mcClone">Make a variation</button></div><p id="mcDescription" style="color:var(--muted)"></p><iframe id="mcPreview" title="Private mood cue preview" style="width:100%;aspect-ratio:16/9;border:1px solid #ffffff18;border-radius:12px" allow="autoplay"></iframe><p id="mcTreatment" style="color:var(--muted)"></p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" id="mcPreviewPlay">Preview excerpt</button><button class="btn" id="mcPreviewStop">Stop preview</button><button class="btn btn-primary" id="mcPlay">Save & play in OBS</button></div><label>Scrub the visual cue sheet<input id="mcScrub" type="range" min="0" max="20" step=".05" style="width:100%"></label><p id="mcFeedback" role="status"></p>
 <details><summary>Suggested sound & alignment</summary><p id="mcReference"></p><p id="mcHint"></p><p>Reference tracks are suggestions. Use audio you have permission to stream. Music is excluded from recordings by default; that routing does not grant music rights.</p></details></section>
 <section class="card" style="padding:18px"><form id="mcForm"><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><label>Name<input class="input" id="mcName" maxlength="80" required></label><label>Hotkey sequence<input class="input" id="mcHotkey" maxlength="8" placeholder="e.g. 986"></label></div><p style="color:var(--muted)">Type the sequence within 300 ms. Trigger the same variation again to stop it.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><label>Playback<select class="input" id="mcMode"><option value="once">One shot</option><option value="repeat">Fixed repeats</option><option value="continuous">Continuous until stopped</option></select></label><label>Total plays<input class="input" type="number" id="mcRepeats" min="2" max="20" step="1"></label><label>Opacity<input class="input" id="mcOpacity" type="number" min="10" max="100" step="1"></label><label><span id="mcScaleLabel">Size (%)</span><input class="input" id="mcScale" type="number" min="50" max="115" step="1"></label><label>Placement<select class="input" id="mcPosition"><option value="top">Above gameplay</option><option value="left">Left perimeter</option><option value="right">Right perimeter</option></select></label><label><input id="mcReduced" type="checkbox"> Gentle motion</label></div><div id="mcCaptionFields"><p>Text</p><label>Opening<input class="input" id="mcWord0" maxlength="60"></label><label>Lift<input class="input" id="mcWord1" maxlength="60"></label><label>Closing<input class="input" id="mcWord2" maxlength="60"></label>
 </div><div id="mcLyricFields"><label>First image · musical hit (file seconds)<input class="input" id="mcImageOnset" type="number" min="0" max="14400" step=".001" placeholder="Empty: follow the first word"></label><p>Rapid image changes start on this measured audio hit. Word timings stay independent.</p><h3>Sung words</h3><p>Original-file seconds, one word per line: start end word. Held words fade; gaps stay empty.</p><textarea class="input" id="mcLyrics" rows="11" spellcheck="false" style="width:100%;font:13px monospace"></textarea><label>Lyric delay (seconds)<input class="input" id="mcLyricOffset" type="number" min="-30" max="30" step=".01"></label><label>Change typeface every (seconds)<input class="input" id="mcFontInterval" type="number" min=".07" max=".5" step=".01"></label><label>Start fading held words after (seconds)<input class="input" id="mcHoldFade" type="number" min=".2" max="3" step=".05"></label></div><hr style="margin:22px 0;opacity:.15"><h3>Your audio</h3><div id="mcDrop" style="border:1px dashed #889caa66;border-radius:10px;padding:18px"><label>Drop or choose audio (up to 20 MB)<input id="mcUpload" type="file" accept=".mp3,.wav,.ogg,.m4a" style="display:block;margin-top:10px;max-width:100%"></label><p id="mcAudioStatus" role="status"></p></div><label>Or local file path<input class="input" id="mcAudioFile" placeholder="C:/StreamingMedia/your-edit.mp3"></label><p style="color:var(--muted)">No file yet? The artwork runs silently. You can also drop an ID-named file into this module’s audio folder.</p>
 <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><label>Trim start (file seconds)<input class="input" id="mcStart" type="number" min="0" max="14400" step=".01"></label><label>Excerpt length (seconds)<input class="input" id="mcDuration" type="number" min="4" max="60" step=".01"></label><label>Lift / cue anchor (excerpt seconds)<input class="input" id="mcAnchor" type="number" min="0" max="60" step=".01"></label><label>BPM<input class="input" id="mcBpm" type="number" min="40" max="200" step=".1"></label><label>Audio speed<input class="input" id="mcRate" type="number" min=".5" max="2" step=".01"></label><label>Variation level (dB offset)<input class="input" id="mcVolume" type="number" min="-60" max="6" step=".1"></label></div><p style="color:var(--muted)">Cue anchor is seconds after the trimmed start, at the selected speed. It places the visual reveal on your musical lift. Each repeat replays this exact excerpt.</p><label><input type="checkbox" id="mcRecord"> Retain this audio in recordings, replays, VODs and clips</label><p style="color:var(--muted)">Off: headphones + live stream only. On: effect audio is also sent to clean track 2. The original Love Me routing is preserved.</p><button class="btn btn-primary" type="submit">Save variation</button></form></section></div>`;
 const $=id=>container.querySelector('#'+id),say=message=>{if(token===epoch)$('mcFeedback').textContent=message;};
 let current=null,cloneId=null,busy=false;
 function lyricCues(){return $('mcLyrics').value.split(/\n/).filter(line=>line.trim()).map(line=>{const match=line.trim().match(/^(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)\s+(.+)$/);if(!match)throw Error('Word cue format: start end word, using original-file seconds.');return {start:Number(match[1]),end:Number(match[2]),text:match[3]};});}
 function draft(){return {...current,name:$('mcName').value.trim(),hotkey:$('mcHotkey').value.trim(),mode:$('mcMode').value,repeats:Number($('mcRepeats').value),opacity:Number($('mcOpacity').value)/100,scale:Number($('mcScale').value)/100,position:$('mcPosition').value,reduced_motion:$('mcReduced').checked,words:[0,1,2].map(i=>$('mcWord'+i).value),image_onset:$('mcImageOnset').value===''?null:Number($('mcImageOnset').value),lyric_cues:lyricCues(),lyric_offset:Number($('mcLyricOffset').value),font_interval:Number($('mcFontInterval').value),hold_fade:Number($('mcHoldFade').value),audio_file:$('mcAudioFile').value.trim(),audio_start:Number($('mcStart').value),duration:Number($('mcDuration').value),audio_anchor:Number($('mcAnchor').value),bpm:Number($('mcBpm').value),audio_rate:Number($('mcRate').value),volume_db:Number($('mcVolume').value),record_audio:$('mcRecord').checked};}
 function preview(play=false){if(!current)return;const row=draft();$('mcPreview').contentWindow?.postMessage({type:'mood-preview',row,time:Number($('mcScrub').value),play,audio:play&&current.audio_ready?`${location.origin}${endpoint}/audio/${encodeURIComponent(current.id)}`:null},previewOrigin);}
 function gallery(){
  $('mcGallery').innerHTML=data.variations.map(row=>`<button class="btn" type="button" data-mood="${esc(row.id)}" aria-pressed="${row.id===selected}" style="display:block;text-align:left;white-space:normal;padding:18px;border:1px solid ${row.id===selected?row.palette[0]:'#ffffff20'};background:radial-gradient(ellipse at top right,${row.palette[0]}24,transparent 75%)"><span style="color:${row.palette[0]};font-size:11px;text-transform:uppercase;letter-spacing:.12em">${esc(row.spirit)} spirit</span><strong style="display:block;font:23px Georgia;margin:9px 0">${esc(row.name)}</strong><span style="display:block;color:var(--muted);font-size:12px">${esc(row.feeling)}</span><span style="display:block;margin-top:15px">${esc(row.hotkey||'No hotkey')} · ${row.audio_ready?'Audio ready':'Visuals ready'}</span></button>`).join('');
  $('mcGallery').querySelectorAll('[data-mood]').forEach(button=>button.onclick=()=>{if(dirty&&!window.confirm('Discard unsaved mood edits?'))return;select(button.dataset.mood);});
 }
 function select(id){
  current=data.variations.find(r=>r.id===id)||data.variations[0];selected=current.id;cloneId=null;dirty=false;gallery();
  $('mcTitle').textContent=current.name;$('mcDescription').textContent=current.description;
  for(const [id,key] of Object.entries({mcName:'name',mcHotkey:'hotkey',mcMode:'mode',mcRepeats:'repeats',mcPosition:'position',mcAudioFile:'audio_file',mcStart:'audio_start',mcDuration:'duration',mcAnchor:'audio_anchor',mcBpm:'bpm',mcRate:'audio_rate',mcVolume:'volume_db'}))$(id).value=current[key];
  $('mcOpacity').value=Math.round(current.opacity*100);$('mcScale').value=Math.round(current.scale*100);$('mcReduced').checked=current.reduced_motion;$('mcRecord').checked=current.record_audio;
  $('mcTreatment').textContent=current.style==='signal'?'35 distinct full-screen film and TV stills start rapid changes on your musical hit and finish with HAVE YOU BEEN: very fast on WHERE, then slightly slower and rapidly fading. Twenty-three lyric typefaces. This preview is private.':'Transparent artwork stays in the perimeter. This preview is private.';
  $('mcPosition').closest('label').hidden=current.style==='signal';$('mcScaleLabel').textContent=current.style==='signal'?'Text size (%)':'Size (%)';
  $('mcCaptionFields').hidden=current.style==='signal';$('mcLyricFields').hidden=current.style!=='signal';
  $('mcImageOnset').value=current.image_onset??'';$('mcAnchor').closest('label').hidden=current.style==='signal';$('mcLyrics').value=(current.lyric_cues||[]).map(cue=>`${cue.start} ${cue.end} ${cue.text}`).join('\n');$('mcLyricOffset').value=current.lyric_offset??0;$('mcFontInterval').value=current.font_interval??.12;$('mcHoldFade').value=current.hold_fade??.75;
  current.words.forEach((word,i)=>$('mcWord'+i).value=word);$('mcScrub').max=current.duration;$('mcScrub').value=current.style==='signal'?(current.lyric_cues?.[0]?.start??1)+.15:current.audio_anchor;
  $('mcReference').innerHTML=`<a href="${esc(current.reference_url)}" target="_blank" rel="noopener">${esc(current.reference)} ↗</a>`;$('mcHint').textContent=current.audio_hint;
  $('mcAudioStatus').textContent=current.audio_error||current.audio_name||'Artwork ready · waiting for your audio';$('mcRepeats').disabled=current.mode!=='repeat';say('');preview();
 }
 const fields=['name','hotkey','mode','repeats','opacity','scale','position','reduced_motion','words','audio_file','audio_start','duration','audio_anchor','bpm','audio_rate','volume_db','record_audio','image_onset','lyric_cues','lyric_offset','font_interval','hold_fade'];
 async function save(){const row=draft(),changes=Object.fromEntries(fields.map(key=>[key,row[key]]));const value=await request(endpoint+'/settings',{id:row.id,clone_from:cloneId,revision:data.revision,changes});if(token!==epoch)return;data=value;select(row.id);say('Saved. Hotkeys and the next cue use these settings.');}
 async function action(name){await request(endpoint+'/control',{action:name});}
 async function withFeedback(fn){if(busy)return;busy=true;try{await fn();}catch(error){say(error.message);}finally{busy=false;}}
 $('mcForm').addEventListener('input',()=>{dirty=true;$('mcRepeats').disabled=$('mcMode').value!=='repeat';$('mcScrub').max=$('mcDuration').value;try{preview();}catch(error){say(error.message);}});
 $('mcForm').addEventListener('submit',event=>{event.preventDefault();withFeedback(save);});
 $('mcScrub').oninput=()=>preview();$('mcPreviewPlay').onclick=()=>{preview(true);say(current.audio_ready?'Playing your excerpt privately.':'Silent preview. Add audio when ready.');};$('mcPreviewStop').onclick=()=>preview();
 $('mcPlay').onclick=()=>withFeedback(async()=>{await save();if(token!==epoch)return;await action(selected);say('Cue requested in OBS. Trigger again or use Stop cue to stop.');});
 $('mcOriginal').onclick=()=>withFeedback(()=>action('original'));$('mcStop').onclick=()=>withFeedback(()=>action('revert'));
 $('mcReload').onclick=()=>withFeedback(async()=>{if(dirty&&!window.confirm('Discard unsaved mood edits?'))return;const value=await request();if(token!==epoch)return;data=value;select(selected);});
 $('mcClone').onclick=()=>{if(dirty&&!window.confirm('Discard unsaved mood edits?'))return;cloneId=current.id;current={...current,id:'mood_'+crypto.randomUUID().replaceAll('-','').slice(0,12),hotkey:'',audio_ready:false,audio_file:'',name:current.name+' · variation'};$('mcName').value=current.name;$('mcHotkey').value='';$('mcAudioFile').value='';$('mcAudioStatus').textContent='Choose audio for this variation.';dirty=true;say('Name it, assign a hotkey, then save.');};
 async function upload(file){
  if(!file)return;if(file.size>20*1024*1024)throw Error('Audio must be smaller than 20 MB.');
  const id=current.id;await save();if(token!==epoch)return;
  const payload=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read audio.'));reader.readAsDataURL(file);});
  const value=await request(endpoint+'/audio',{id,filename:file.name,data:payload,revision:data.revision});if(token!==epoch)return;data=value;select(id);say('Audio imported. Preview the excerpt to align its lift.');
 }
 $('mcUpload').onchange=event=>withFeedback(()=>upload(event.target.files[0]));$('mcDrop').ondragover=event=>event.preventDefault();$('mcDrop').ondrop=event=>{event.preventDefault();withFeedback(()=>upload(event.dataTransfer.files[0]));};
 const onMessage=event=>{if(event.origin!==previewOrigin||event.source!==$('mcPreview').contentWindow)return;if(event.data?.type==='mood-preview-ready')preview();if(event.data?.type==='mood-preview-error')say(event.data.message);};window.addEventListener('message',onMessage);
 container._moodCleanup=()=>{window.removeEventListener('message',onMessage);$('mcPreview').contentWindow?.postMessage({type:'mood-preview'},previewOrigin);};
 try{data=await request();if(token!==epoch)return;$('mcPreview').onload=()=>preview();$('mcPreview').src=data.preview_url;select(selected);
  async function poll(){try{const value=await request();if(token!==epoch)return;$('mcPlay').disabled=$('mcOriginal').disabled=!value.ready;$('mcRuntime').textContent=value.runtime.error||`${value.runtime.active||(value.ready?'Ready':'Waiting for OBS and module startup')}${value.runtime.paused?' · paused':''}${value.runtime.iteration?' · play '+value.runtime.iteration:''}`;}catch(error){if(token===epoch)$('mcRuntime').textContent=error.message;}if(token===epoch)timer=setTimeout(poll,2000);}poll();
 }catch(error){say(error.message);}
}
export function unmount(){++epoch;clearTimeout(timer);root?._moodCleanup?.();root=null;data=null;dirty=false;}
