import {partyTracks} from './characters.js';
const $=id=>document.getElementById(id);
let selected='crab',settings={volume:.22,muted:false,custom:{}},library=[],initialized=false;
const titles={crab:['🦀','Crab Carnival','Crab Rave / crab dance'],dragon:['🐉','Dragon Disco','Driftveil City / Toothless energy'],cat:['🐈','Cosmic Cat Club','Nyan Cat / rainbow chaos'],frog:['🐸','Frog Fiesta','Pedro / raccoon party']};
const spiritTitles={crab:['🐻','Stormclaw','Lightning claw reveal / quick paw welcome'],dragon:['🐢','Verdant Aegis','Runic shield bloom / little spirit greeting'],cat:['🐏','Sundering Gold','Golden horn impact / tiny horn salute'],frog:['🔥','Cinder Ascension','Fiery hatch and flight / ember welcome']};
async function post(path,body={}){try{const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Hub-CSRF':window.CSRF},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error);$('message').textContent=data.scene?'Overlay added to '+data.scene:'Done.';return data;}catch(e){$('message').textContent=e.message;return null;}}
function slots(){for(const [id,key,re] of [['visual','visual',/\.(webm|mp4|gif|png|webp)$/i],['music','audio',/\.(wav|mp3|ogg|m4a)$/i]]){const select=$(id);select.replaceChildren(new Option(key==='visual'?'Original spirit / raid artwork':['follow','subscribe','gift'].includes($('kind').value)?'Original spirit sound (default)':partyTracks[selected].label+' (default)',''));for(const file of library.filter(x=>re.test(x)))select.add(new Option(file,file));select.value=settings.custom?.[selected]?.[key]||'';}}
for(const [key,[icon,title,description]]of Object.entries(titles)){const button=document.createElement('button');button.className='theme'+(key===selected?' selected':'');button.innerHTML=`<strong>${icon} ${title}</strong><span>${description}</span>`;button.onclick=()=>{selected=key;document.querySelectorAll('.theme').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');slots();};$('themes').append(button);}
function flavorLabels(){const support=['subscribe','gift','follow'].includes($('kind').value),labels=support?spiritTitles:titles;document.querySelectorAll('.theme').forEach((button,i)=>{const [icon,title,description]=labels[Object.keys(titles)[i]];button.querySelector('strong').textContent=icon+' '+title;button.querySelector('span').textContent=description;});$('personalPreview').hidden=!['subscribe','gift'].includes($('kind').value);$('months').disabled=$('kind').value==='gift';$('subMessage').disabled=$('kind').value==='gift';slots();}
$('kind').onchange=flavorLabels;flavorLabels();
const event=()=>({kind:$('kind').value,name:$('name').value,count:Number($('count').value),theme:selected,details:{tier:$('tier').value,months:$('kind').value==='gift'?undefined:Number($('months').value)||undefined,renewal:$('kind').value!=='gift'&&Number($('months').value)>1,message:$('kind').value==='gift'?'':$('subMessage').value}});
$('previewButton').onclick=()=>{$('preview').contentWindow.postMessage({type:'preview',item:{...event(),id:crypto.randomUUID(),elapsed:0,duration:({raid:8,follow:2.2,subscribe:3.8,gift:3.8,cheer:7})[$('kind').value]},settings},location.origin);};
$('stopPreview').onclick=()=>$('preview').contentWindow.postMessage({type:'stop'},location.origin);
$('test').onclick=()=>post('test',event());$('stop').onclick=()=>post('stop');$('obs').onclick=()=>post('obs');
$('connect').onclick=async()=>{await post('connect');await refresh();};
for(const key of ['enabled','muted'])$(key).onchange=async()=>{const value=$(key).checked;if(await post('settings',{[key]:value}))settings[key]=value;};
$('volume').oninput=()=>{$('level').textContent=$('volume').value+'%';};
$('volume').onchange=async()=>{const volume=Number($('volume').value)/100;if(await post('settings',{volume}))settings.volume=volume;};
$('saveMedia').onclick=async()=>{const custom={...settings.custom,[selected]:{visual:$('visual').value,audio:$('music').value}};if(await post('settings',{custom}))settings.custom=custom;};
async function refresh(){try{const r=await fetch('/api/state');if(!r.ok)throw Error();const state=await r.json();settings=state.settings;$('connection').textContent=state.connected?'TWITCH CONNECTED':'LOCAL PREVIEW READY';$('twitchStatus').textContent=state.message;$('obsStatus').textContent=state.overlay_ready?'Overlay is connected. '+state.queue+' queued.':'Add the overlay to each scene where you want celebrations.';$('auth').replaceChildren();if(state.auth){const a=document.createElement('a');a.href=state.auth.url;a.target='_blank';a.rel='noopener';a.textContent='Authorize on Twitch · code '+state.auth.code;$('auth').append(a);}$('recent').replaceChildren(...state.history.slice(-6).reverse().map(x=>{const row=document.createElement('div');row.textContent=`${x.kind} · ${x.name} · ${titles[x.theme][1]}`;return row;}));if(!initialized){$('enabled').checked=settings.enabled;$('muted').checked=settings.muted;$('volume').value=settings.volume*100;$('level').textContent=Math.round(settings.volume*100)+'%';library=await(await fetch('/api/library')).json();slots();initialized=true;}}catch{$('connection').textContent='HUB OFFLINE';}}
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.data.type==='celebration-audio-blocked')$('message').textContent='Browser blocked preview audio. Allow autoplay for this site; OBS uses its own audio output.';});
refresh();setInterval(refresh,2000);

async function eventHealth(){try{const state=await(await fetch('/api/state')).json();const labels={raid:'Raids',follow:'Follows',subscribe:'Subscriptions',resub:'Returning subs',gift:'Gift subs',cheer:'Cheers'};$('eventHealth').textContent=Object.entries(labels).map(([key,label])=>`${state.connected&&state.subscriptions?.[key]?.enabled?'●':'○'} ${label}`).join('  ·  ')+(state.last_event?`  | Last live event: ${state.last_event.kind} from ${state.last_event.name}`:'  | Waiting for the first live event.');}catch{}}
eventHealth();setInterval(eventHealth,2000);

