// Generated by tools/build_border_art.py; edit art/celebration-scenes.js.
// Native celebration assembly. The existing shows own timing and cleanup.
import {WorldPaint,Optics,EdgeFinish,smooth,TAU,pathOf} from './subtle.js';
// Local material vocabulary; performances own subjects/routes and the clock.
function partyInk(c,t,duration){
 const p=t/Math.max(.1,duration),o=new Optics(c),w=new WorldPaint(c);
 const line=(pts,color,width=1,alpha=.7)=>o.line(pts,color,width,alpha);
 const curve=(fn,color,width=1,alpha=.5)=>o.curve(fn,color,width,alpha);
 const disc=(x,y,rx,ry,color,alpha=1)=>{c.save();c.globalAlpha*=alpha;c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,TAU);c.fill();c.restore();};
 const poly=(pts,color,alpha=1)=>{c.save();c.globalAlpha*=alpha;c.fillStyle=color;c.beginPath();pts.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.fill();c.restore();};
 const path=(draw,color,alpha=1,outline='#dbf9ff')=>{c.save();c.globalAlpha*=alpha;c.beginPath();draw(c);c.fillStyle=color;c.fill();if(outline){c.strokeStyle=outline;c.lineWidth=.8;c.stroke();}c.restore();};
 const metal=(axis,colors=['#edfbff','#698b9d','#102635','#89bfcd'])=>{const g=c.createLinearGradient(...axis);colors.forEach((col,i)=>g.addColorStop(i/(colors.length-1),col));return g;};
 const local=(x,y,size,turn,draw)=>{c.save();c.translate(x,y);c.rotate(turn);c.scale(size/100,size/100);draw();c.restore();};
 const sweep=(fn,color,offset=0,width=2)=>o.light(fn,p*1.35-offset,color,width,.22,.95);
 const ribbon=(fn,color,second,width=16,phase=t)=>o.ribbon(fn,{color,secondary:second,width,phase,glass:true,alpha:.7});
 const ring=(x,y,rx,ry,color,alpha=.5,turn=0)=>o.arc(x,y,rx,ry,0,TAU,color,1,alpha,turn);
 const foil=(x,y,size,color,turn=0)=>o.shard(x,y,size,color,p,turn,true);
 // Absolute serial births develop through the cue, with no independent loop.
 const births=(count,first,gap,life,draw)=>{for(let j=0;j<count;j++){const age=t-first-j*gap;if(age<0||age>=life)continue;const u=age/life;c.save();c.globalAlpha*=smooth(u/.12)*smooth((1-u)/.24);draw(u,j,age);c.restore();}};
 return {c,t,p,o,w,line,curve,disc,poly,path,metal,local,sweep,ribbon,ring,foil,births};
}

// Subject silhouettes. Their acting and placement belong to the event owner.
function partyProps(i){
 const {c,t,o,w,line,curve,disc,poly,path,metal,local,ring}=i;
 const gem=(x,y,size,color,turn=0)=>local(x,y,size,turn,()=>{o.sheet([[0,-43],[33,-12],[24,25],[0,44],[-29,17],[-34,-17]],color,t/5,{glass:true});line([[0,-43],[8,-8],[0,44],[-10,-6],[0,-43]],'#eaffff',1,.7);});
 const bow=(x,y,size,color)=>local(x,y,size,Math.sin(t*2)*.03,()=>{path(q=>{q.moveTo(0,0);q.bezierCurveTo(-60,-43,-52,28,0,0);q.bezierCurveTo(58,-46,55,25,0,0);},metal([-50,0,50,0],['#f4fcff',color,'#163341',color]),.9);disc(0,0,7,8,'#e7ffff');});
 const leaf=(x,y,size,color,turn=0)=>local(x,y,size,turn,()=>{path(q=>{q.moveTo(0,42);q.bezierCurveTo(-44,-7,-17,-46,20,-44);q.bezierCurveTo(42,-3,35,19,0,42);},metal([-28,-40,28,40],['#f1ffca',color,'#123f39',color]),.75);line([[0,40],[8,6],[20,-41]],'#e8ffe3',1,.8);for(let j=0;j<4;j++)line([[6,25-j*15],[-17,13-j*12]],color,1,.7);});
 const feather=(x,y,size,color,turn=0)=>local(x,y,size,turn,()=>{path(q=>{q.moveTo(0,46);q.bezierCurveTo(-36,6,-25,-44,19,-48);q.bezierCurveTo(35,-19,23,15,0,46);},metal([-30,-40,25,40],['#ffefce',color,'#512d37',color]),.8);line([[0,48],[18,-43]],'#fff3ce',1.4,.9);for(let j=0;j<6;j++)line([[j*2,38-j*14],[-16+j*3,19-j*12]],'#ffe5bb',.8,.7);});
 const bell=(x,y,size,color,turn=0)=>local(x,y,size,turn,()=>{ring(0,-29,9,12,color,.8);path(q=>{q.moveTo(-23,24);q.quadraticCurveTo(-14,0,-14,-15);q.quadraticCurveTo(0,-31,14,-15);q.quadraticCurveTo(13,2,23,24);q.closePath();},metal([-23,-28,23,25],['#fff6d9',color,'#392e40',color]),.95);disc(0,28,6,6,'#ffedb8');line([[-28,23],[28,23]],color,1.5);});
 const lantern=(x,y,size,color,turn=0)=>local(x,y,size,turn,()=>{line([[0,-58],[0,-42]],color,1);path(q=>{q.moveTo(-23,-31);q.bezierCurveTo(-43,1,-30,34,0,39);q.bezierCurveTo(32,35,42,0,23,-31);q.closePath();},metal([-30,-32,32,35],['#ffe6ad',color,'#302936',color]),.75);for(let a=-1;a<=1;a++)curve(u=>[a*(15+Math.sin(u*Math.PI)*9),-31+u*65],color,.7,.8);line([[-26,-33],[26,-33]],'#fff0c6',2);line([[-22,38],[22,38]],color,2);w.mist(0,0,40,39,color,.25);line([[0,41],[0,61]],color,1);});
 const bear=(x,y,size,color,pose=0)=>local(x,y,size,Math.sin(t*2+pose)*.025,()=>{const fur=metal([-45,-44,40,47],['#e8f7ff','#44667e','#102838',color]);disc(-24,-32,13,14,fur);disc(24,-32,13,14,fur);path(q=>{q.moveTo(-34,-26);q.bezierCurveTo(-51,4,-34,48,0,44);q.bezierCurveTo(35,47,49,5,34,-26);q.quadraticCurveTo(0,-47,-34,-26);},fur,1);disc(-23,26+Math.sin(t*4+pose)*4,13,15,fur);disc(23,26-Math.sin(t*4+pose)*4,13,15,fur);disc(0,12,19,15,'#9bb8c5');disc(0,6,7,5,'#0d1c28');line([[-10,23],[0,27],[10,22]],'#ecfcff',1.3);for(const side of [-1,1]){disc(side*13,-5,4,3,color);disc(side*13-1,-6,1,1,'#fff');}line([[-32,5],[-43,19],[-32,24]],color,1.4);});
 const turtle=(x,y,size,color,pose=0)=>local(x,y,size,Math.sin(t*2+pose)*.03,()=>{const shell=metal([-44,-40,45,35],['#ddf5bf',color,'#184841','#719b7f']);disc(-33,24,12,9,'#7bbea9');disc(33,24,12,9,'#7bbea9');disc(0,-27,16,18,'#8bd4bb');disc(-6,-31,2,3,'#fff8df');disc(6,-31,2,3,'#fff8df');path(q=>{q.moveTo(-40,8);q.bezierCurveTo(-39,-39,39,-39,40,8);q.quadraticCurveTo(0,39,-40,8);},shell,1);for(let n=0;n<5;n++){const a=n*TAU/5,x=Math.cos(a)*20,y=Math.sin(a)*15;line([[x-10,y-9],[x,y-13],[x+10,y-4],[x+9,y+10],[x-9,y+9],[x-10,y-9]],'#eaffc9',1,.6);}});
 const ram=(x,y,size,color,pose=0)=>local(x,y,size,Math.sin(t*3+pose)*.025,()=>{for(const side of [-1,1]){path(q=>{q.moveTo(side*15,-24);q.bezierCurveTo(side*57,-48,side*61,33,side*27,19);q.bezierCurveTo(side*7,10,side*22,-15,side*36,-9);},metal([-50,-30,50,30],['#fff1b7',color,'#554344',color]),1);for(let j=0;j<7;j++)line([[side*(24+j*3),-29+j*5],[side*(34+j*2),-25+j*5]],color,.8,.6);}path(q=>{q.moveTo(-21,-25);q.quadraticCurveTo(0,-44,21,-25);q.lineTo(17,22);q.quadraticCurveTo(0,47,-17,22);q.closePath();},metal([-23,-27,22,36],['#eff7ef','#7b9299','#142633','#aebbb2']),1);disc(-9,-5,3,2,color);disc(9,-5,3,2,color);poly([[-7,23],[0,29],[7,23]],'#f5d8b5');});
 const bird=(x,y,size,color,pose=0)=>local(x,y,size,Math.sin(t*2+pose)*.04,()=>{const flap=.68+.22*Math.sin(t*5+pose);for(const side of [-1,1])path(q=>{q.moveTo(0,0);q.bezierCurveTo(side*27,-50*flap,side*65,-46*flap,side*54,14);q.lineTo(side*39,2);q.lineTo(side*26,21);q.closePath();},metal([-55,-45,55,28],['#fff5c8',color,'#763642',color]),.9);path(q=>{q.moveTo(-10,-8);q.quadraticCurveTo(-17,-37,5,-35);q.lineTo(20,-23);q.lineTo(9,-20);q.quadraticCurveTo(14,20,0,37);q.quadraticCurveTo(-16,10,-10,-8);},color,.9);disc(3,-27,2,2,'#fff6dc');line([[0,27],[-14,46],[0,39],[14,47]],'#ffd7a0',2,.8);});
 const crab=(x,y,size,color,pose=0)=>local(x,y,size,Math.sin(t*3+pose)*.04,()=>{for(const side of [-1,1]){for(let j=0;j<3;j++)line([[side*18,4+j*7],[side*(33+j*4),13+j*6+Math.sin(t*5+j+pose)*3]],color,4);path(q=>{q.moveTo(side*18,0);q.lineTo(side*36,-23);q.lineTo(side*49,-30);q.lineTo(side*45,-10);q.lineTo(side*38,-18);},color,1);}disc(0,4,25,19,metal([-25,-17,25,26],['#fff3d6',color,'#443d53',color]));for(const side of [-1,1]){line([[side*11,-9],[side*12,-23]],color,3);disc(side*12,-23,5,6,'#fff7e1');disc(side*12+1,-23,2,3,'#213444');}line([[-7,12],[0,16],[7,12]],'#efffff',1);});
 const frog=(x,y,size,color,pose=0)=>local(x,y,size,Math.sin(t*3+pose)*.045,()=>{disc(-22,24,16,8,color);disc(22,24,16,8,color);disc(0,7,29,25,metal([-25,-24,30,29],['#efffcb',color,'#184b4c',color]));for(const side of [-1,1]){disc(side*18,-15,12,13,color);disc(side*18,-17,7,8,'#fffbe1');disc(side*18+1,-16,3,5,'#153c49');}line([[-16,11],[-7,18],[7,18],[16,11]],'#d8ffec',1.4);});
 const cat=(x,y,size,color,pose=0)=>local(x,y,size,Math.sin(t*3+pose)*.035,()=>{const fur=metal([-34,-38,33,38],['#f7ecdf',color,'#373e60','#92a5c1']);path(q=>{q.moveTo(-27,-11);q.lineTo(-32,-40);q.lineTo(-7,-28);q.quadraticCurveTo(5,-31,11,-26);q.lineTo(33,-42);q.lineTo(30,-8);q.bezierCurveTo(43,27,-34,36,-27,-11);},fur,1);for(const side of [-1,1]){disc(side*13,-4,5,4,'#efffcf');disc(side*13,-4,1.4,4,'#1d2d44');for(let j=0;j<2;j++)line([[side*20,8+j*6],[side*42,4+j*13]],'#d8edff',1,.8);}poly([[-4,9],[4,9],[0,13]],'#ffb7ce');line([[0,13],[-6,17],[0,13],[6,17]],'#eee9ff',1);});
 const boat=(x,y,size,color,turn=0)=>local(x,y,size,turn,()=>{path(q=>{q.moveTo(-46,11);q.lineTo(46,11);q.quadraticCurveTo(28,41,-28,31);q.closePath();},metal([-45,10,43,37],['#eafaff',color,'#183b4d',color]),.9);line([[0,11],[0,-46]],'#d6eaff',1.5);poly([[3,-41],[3,7],[37,6]],color,.65);line([[-49,35],[44,35]],color,.8,.4);});
 const dragon=(x,y,size,color,pose=0)=>local(x,y,size,Math.sin(t*2+pose)*.04,()=>{
  const body=metal([-60,-40,57,45],['#e6f8ef',color,'#222d52',color]);
  path(q=>{q.moveTo(-6,-21);q.bezierCurveTo(-43,-57,-73,-24,-53,8);q.bezierCurveTo(-81,-16,-56,47,-21,37);q.bezierCurveTo(0,61,49,25,25,4);q.bezierCurveTo(15,4,14,-15,30,-19);q.lineTo(52,-17);q.lineTo(56,-29);q.lineTo(33,-37);q.lineTo(19,-48);q.lineTo(18,-34);q.closePath();},body,1);
  for(const side of [-1,1]){const flap=Math.sin(t*4+pose)*7;path(q=>{q.moveTo(-8,1);q.lineTo(side*39,-44-flap);q.lineTo(side*55,-2);q.lineTo(side*34,-13);q.lineTo(side*26,10);q.closePath();},color,.35);line([[-8,1],[side*39,-44-flap],[side*26,10]],'#f2ffe9',1,.75);}
  disc(30,-29,3,2,'#fff7ce');line([[31,-17],[48,-15]],'#ecffef',1);for(let j=0;j<6;j++)poly([[-31+j*6,-21+j*4],[-37+j*6,-33+j*4],[-39+j*6,-18+j*4]],color,.8);
 });
 return {gem,bow,leaf,feather,bell,lantern,bear,turtle,ram,bird,crab,frog,cat,boat,dragon};
}

// Four den/grove/forge/flock stories, with separately staged gifting acts.
function supporterPerformance(c,theme,t,duration,gift,seed){
 const i=partyInk(c,t,duration),s=partyProps(i),{p,o,w,line,curve,disc,poly,path,metal,local,sweep,ribbon,ring,foil,births}=i;
 const arrive=smooth((t-.15)/.55),spread=smooth((t-.65)/1.35);
 if(theme==='bear'){
  const a='#92ddff',b='#c4b7ff',gold='#f5d39d';
  // Thunder is a series of little branching deliveries, never a screen flash.
  for(let side=0;side<2;side++)for(let j=0;j<3;j++){
   const x=side?1894-j*15:26+j*19,sign=side?-1:1;
   const route=pathOf([[x,210],[x+sign*35,321],[x-sign*9,386],[x+sign*42,519],[x+sign*14,666],[x+sign*37,861],[x,1009]]);
   curve(route,a,.8,.25);sweep(route,j%2?a:b,j*.1,1.8);
  }
  if(!gift){
   s.bear(665,84+(1-arrive)*56,137,a);ring(663,131,74,13,a,.6);
   for(let j=0;j<3;j++){const y=300+j*156;s.bear(j%2?1829:91,y+Math.sin(t*3+j)*6,75+j*8,j%2?b:a,j);s.bell(j%2?1890:24,y+33,32,gold,Math.sin(t*4+j)*.12);}
   // A glass umbrella, tiny den steps and pawprints catch the storm.
   local(1819,323,145,Math.sin(t)*.02,()=>{path(q=>{q.moveTo(-49,0);q.quadraticCurveTo(-33,-53,0,-46);q.quadraticCurveTo(34,-53,49,0);q.quadraticCurveTo(25,-9,0,0);q.quadraticCurveTo(-25,-9,-49,0);},metal([-50,-48,50,4],['#dcefff66',b+'72','#19394718',a+'6b']),.8);line([[0,-46],[0,54],[13,61],[19,52]],gold,1.4);for(let z of [-1,1])curve(u=>[z*Math.sin(u*Math.PI/2)*49,-46+u*46],a,1,.5);});
   for(let j=0;j<7;j++){const x=425+j*153,y=1017+Math.sin(t*2+j)*7;poly([[x-29,y],[x+24,y-7],[x+32,y+18],[x-22,y+21]],'#193648',.4);line([[x-29,y],[x+24,y-7]],a,.9,.8);}
   births(22,.5,.095,1.2,(u,j)=>{const x=j%2?1880-32*Math.sin(u*Math.PI):48+37*Math.sin(u*Math.PI),y=740-u*490-j%3*15;disc(x,y,5,4,gold,.7);for(let n=0;n<3;n++)disc(x-7+n*7,y-9,2.3,3,a,.9);});
  }else{
   s.bear(634,82,118,a);s.bear(724,94,70,b,2);s.bow(649,37,42,gold);
   // Silk gift boxes ride a perimeter rail, then open into cubs and paw charms.
   ribbon(u=>[300+u*1320,1024-27*Math.sin(u*Math.PI)],a,b,14,t*1.5);
   for(let j=0;j<5;j++){const q=smooth((t-.2-j*.12)/1.8),x=280+q*(310+j*275),y=1032-30*Math.sin(q*Math.PI);local(x,y,63,Math.sin(t*3+j)*.025,()=>{o.sheet([[-30,-23],[30,-23],[30,24],[-30,24]],j%2?a:b,p,{glass:true});line([[0,-23],[0,24]],gold,2);s.bow(0,-25,65,gold);});if(t>1.15+j*.12)s.bear(x,y-62*spread,52,a,j);}
   for(let j=0;j<6;j++){const side=j%2,x=side?1848:79,y=245+j%3*180;s.bell(x,y+Math.sin(t*4+j)*10,40,gold,Math.sin(t*3+j)*.14);ring(x,y,34,57,j%2?b:a,.4);}
   births(32,.45,.065,1.65,(u,j)=>{const x=j%2?1900-u*62:18+u*69,y=1010-u*870;s.gem(x,y,14+j%3*6,j%2?a:gold,u+j);});
  }
  for(let j=0;j<14;j++){const x=335+j*96,y=12+Math.sin(t*1.4+j)*7;w.star(x,y,1+j%3,j%2?a:gold,.6);}
 }else if(theme==='turtle'){
  const a='#b7efb0',b='#70e0cb',rose='#f5bdcf';
  if(!gift){
   s.turtle(663,91+(1-arrive)*70,137,b);s.leaf(590,85,74,a,-.5-spread*.4);s.leaf(741,78,67,a,.8+spread*.3);
   // A terrarium opens leaf by leaf; little keepers tend each sprout.
   for(let j=0;j<5;j++){const x=j%2?1861:58,y=227+j*111;ring(x,y,38,55,b,.55);s.leaf(x+Math.sin(t*2+j)*6,y,51,a,j*.7+t*.04);if(j%2===0)s.turtle(x,y+43,52,b,j);}
   for(let j=0;j<8;j++){const x=340+j*176,y=1043;curve(u=>[x+Math.sin(u*3+t*.3+j)*13,y-u*(22+j%3*16)*spread],b,1.1,.65);s.leaf(x+15,y-18*spread,27+j%3*6,j%2?a:rose,-.8);}
   for(let j=0;j<4;j++){const x=j%2?1798:110,y=360+j%2*240;local(x,y,70,Math.sin(t*3+j)*.08,()=>{for(let side of [-1,1]){s.leaf(side*17,0,47,rose,side*.9);s.leaf(side*12,24,33,a,side*.5);}line([[0,-8],[0,32]],'#f1ffe5',2,.8);});}
  }else{
   s.turtle(638,92,117,b);s.turtle(728,101,73,a,3);s.bow(643,43,53,rose);
   // Seed packets become a tiny living flotilla, with new leaves appearing late.
   for(let j=0;j<6;j++){const u=smooth((t-.25-j*.13)/2.15),x=310+j*235+Math.sin(u*Math.PI)*32,y=1060-u*(28+j%3*12);s.boat(x,y,72,j%2?a:b,-.04+Math.sin(t*2+j)*.03);s.leaf(x,y-32,34+u*17,rose,.3);if(u>.65)s.turtle(x+13,y-59,35,a,j);}
   for(let j=0;j<8;j++){const y=210+j%4*185,x=j%2?1855:62;s.leaf(x,y+Math.sin(t*2+j)*9,41+j%3*10,j%3?a:rose,j*.6);s.gem(x+28,y-38,22,b,p+j);}
   births(24,.25,.09,1.75,(u,j)=>{const x=j%2?1825+Math.sin(u*8+j)*28:84+Math.sin(u*8+j)*28,y=970-u*820;s.leaf(x,y,24+j%3*6,a,-u+j);});
  }
  for(let side=0;side<2;side++)for(let j=0;j<3;j++){const fn=u=>[side?1899-j*13+Math.sin(u*9+t*.2)*15:19+j*17+Math.sin(u*8+t*.2)*15,1030-u*890];curve(fn,b,1,.27);sweep(fn,j%2?a:rose,j*.16,1.5);}
  births(28,.4,.08,1.1,(u,j)=>{const x=330+j*47,y=1059-u*23-Math.sin(u*Math.PI)*19;w.star(x,y,1.5,a,.7);});
 }else if(theme==='ram'){
  const a='#ffd48b',b='#aee7ed',hot='#ffad9c';
  s.ram(gift?630:662,83+(1-arrive)*48,gift?129:143,a);
  if(!gift){
   // Golden horn workshop: geared arches, prism blanks and a jeweled anvil.
   for(let side=0;side<2;side++){const x=side?1879:41;const spiral=u=>{const r=8+u*64;return[x+Math.cos(u*TAU*1.65+t*.15)*r,420+Math.sin(u*TAU*1.65+t*.15)*r*1.6];};curve(spiral,a,7,.16);curve(spiral,a,1.2,.8);sweep(spiral,b,side*.19,2);for(let j=0;j<3;j++){const y=226+j*215;ring(x,y,24,24,a,.6);for(let n=0;n<10;n++){const q=n*TAU/10+t*.25;line([[x+Math.cos(q)*24,y+Math.sin(q)*24],[x+Math.cos(q)*29,y+Math.sin(q)*29]],a,2,.6);}s.gem(x,y,34,b,t+j);}}
   local(1819,617,147,0,()=>{o.sheet([[-45,-16],[46,-16],[28,1],[17,11],[17,29],[-17,29],[-19,9],[-45,4]],a,p);s.gem(0,-43,39,hot,t*.3);line([[-26,-67],[-7,-47]],b,4,.8);});
   for(let j=0;j<9;j++){const x=326+j*148;s.gem(x,1037+Math.sin(t*2+j)*8,30+j%3*10,j%2?a:b,j*.3+p);}
  }else{
   s.ram(726,91,74,a,3);s.bow(639,32,60,hot);
   // A golden carriage hands out crowns. Recipients salute in sequence.
   const carriage=310+smooth(t/2.7)*1260;
   local(carriage,1022,115,0,()=>{o.sheet([[-52,-32],[51,-32],[55,18],[-47,18]],a,p,{glass:true});for(let side of [-1,1]){ring(side*30,26,14,14,b,.8);line([[side*30-13,26],[side*30+13,26]],a,1);}s.bow(0,-35,70,hot);});
   for(let j=0;j<5;j++){const x=360+j*287,y=979;s.ram(x,y+Math.sin(t*3+j)*5,56,a,j);const crownY=934-20*smooth((t-.6-j*.16)/.6);poly([[x-22,crownY+12],[x-25,crownY-7],[x-9,crownY+1],[x,crownY-14],[x+11,crownY+1],[x+25,crownY-7],[x+21,crownY+12]],a,.75);line([[x-21,crownY+12],[x+21,crownY+12]],'#fff8d5',1);}
   for(let j=0;j<8;j++){const x=j%2?1861:55,y=227+j%4*183;s.gem(x,y+Math.sin(t*2+j)*10,37+j%2*9,j%2?hot:b,j*.4+p);}
   births(33,.35,.066,1.45,(u,j)=>{const x=j%2?1855+u*43:64-u*43,y=180+u*760;foil(x,y,8+j%4,a,j+u);});
  }
  for(let j=0;j<3;j++){const fn=u=>[320+u*1290,1059+Math.sin(u*13+t*.3+j)*9];sweep(fn,j%2?a:b,j*.15,1.7);}
  for(let j=0;j<14;j++){const x=330+j*96;line([[x,9],[x+9,21],[x+19,9]],j%2?a:b,1,.65);}
 }else{
  const a='#ffb479',b='#f7d19f',violet='#e0b2ee';
  if(!gift){
   // Egg opens, a small phoenix rises and its loose feathers charge the edges.
   const hatch=smooth((t-.45)/.5);local(663,101,115,Math.sin(t*5)*(1-hatch)*.035,()=>{path(q=>{q.moveTo(0,-48);q.bezierCurveTo(-42,-36,-43,39,0,43);q.bezierCurveTo(45,39,41,-35,0,-48);},metal([-40,-40,40,42],['#fff0d5',a,'#60364b',b]),1-hatch);});
   c.save();c.globalAlpha*=hatch;s.bird(661,97-hatch*18,145,a);c.restore();
   for(let j=0;j<6;j++){const x=j%2?1866:63,y=229+j%3*202;s.feather(x,y+Math.sin(t*2+j)*8,78+j%2*15,j%3?a:violet,j%2?.55:-.55);if(j%3===0)s.bird(x+21,y+48,54,b,j);}
   for(let j=0;j<12;j++){const x=322+j*111;const y=1041+Math.sin(t*2+j)*9;s.feather(x,y,37+j%3*9,j%2?a:violet,-1.1+j*.18+p*.25);}
  }else{
   s.bird(618,88,119,a);s.bird(720,88,81,b,1);s.bow(668,33,44,violet);
   // Little ember envelopes open into different fledglings, never a fire wall.
   for(let j=0;j<7;j++){const x=332+j*191,y=1038-12*Math.sin(t*2+j);const opened=smooth((t-.45-j*.14)/.55);local(x,y,61,-.08+j*.025,()=>{o.sheet([[-35,-20],[35,-20],[35,21],[-35,21]],j%2?a:violet,p,{glass:true});line([[-35,-20],[0,9-opened*33],[35,-20]],b,1.3,.8);});s.bird(x,y-52*opened,47*opened,a,j);}
   for(let j=0;j<6;j++){const x=j%2?1856:77,y=232+j%3*214;s.lantern(x,y+Math.sin(t*2+j)*7,65,j%2?b:violet,Math.sin(t*2+j)*.07);s.feather(x+21,y+57,34,a,.4);}
  }
  for(let side=0;side<2;side++)for(let j=0;j<3;j++){const route=u=>[side?1903-j*18+Math.sin(u*8+t*.25)*17:20+j*17+Math.sin(u*9+t*.2)*19,1058-u*899];ribbon(route,j%2?a:violet,b,5+j*2,t+j);sweep(route,b,j*.16,1.4);}
  births(37,.3,.065,1.5,(u,j)=>{const x=j%2?1841+Math.sin(u*7+j)*45:70+Math.sin(u*8+j)*45,y=1020-u*830;s.feather(x,y,13+j%3*8,j%3?a:violet,u+j);});
 }
}

// Each raid is an eight-second ensemble, timed by the existing server deadline.
function raidPerformance(c,theme,t,duration,seed){
 const i=partyInk(c,t,duration),s=partyProps(i),{p,o,w,line,curve,disc,poly,path,metal,local,sweep,ribbon,ring,foil,births}=i;
 const landing=smooth((t-.4)/1.1),parade=smooth((t-1)/5.7),finale=smooth((t-5)/1.4);
 if(theme==='crab'){
  const a='#a1e9ea',b='#f0c1a0',pearl='#f6ead1';
  // A fleet assembles along the bottom shore. Each captain has its own bob.
  for(let j=0;j<9;j++){const x=260+j*177+parade*(j%2?25:-25),y=1022+Math.sin(t*2+j*.9)*7;s.boat(x,y,83+j%3*14,j%2?a:b,Math.sin(t*1.6+j)*.025);s.crab(x,y-43-landing*9,39+j%3*8,b,j);s.bell(x,y-78,18,pearl,Math.sin(t*4+j)*.2);}
  local(81,504,140,0,()=>{o.sheet([[-29,-80],[29,-80],[38,89],[-37,89]],a,p,{glass:true});for(let j=0;j<4;j++)line([[-28-j*2,-45+j*34],[29+j*2,-45+j*34]],pearl,5,.7);o.sheet([[-47,-82],[48,-82],[40,-113],[-40,-113]],b,p);o.orb(0,-96,16,pearl,t,{glass:true});line([[-46,91],[46,91]],a,1);});
  for(let j=0;j<5;j++){const x=j%2?1844:102,y=250+j%3*179;s.crab(x,y+Math.sin(t*3+j)*8,74+j%2*12,b,j);o.orb(x-37,y+41,8+j%3*2,pearl,t+j,{glass:true});}
  for(let j=0;j<4;j++){const fn=u=>[180+u*1610,1067+Math.sin(u*16-t*.8+j*.6)*(6+j*2)];curve(fn,a,1,.45);sweep(fn,j%2?a:pearl,j*.1,1.8);}
  births(56,.6,.105,2.2,(u,j)=>{const x=j%2?1830+Math.sin(j+u*5)*43:79+Math.sin(j+u*6)*39,y=1010-u*790;o.orb(x,y,3+j%3*1.5,j%3?a:pearl,t+j,{glass:true});});
  for(let j=0;j<13;j++){const x=320+j*97;s.bow(x,12+Math.sin(t*2+j)*5,24,j%2?a:b);}
  // Pearl signal grows near one corner instead of sweeping across gameplay.
  ring(1830,390,45+finale*17,81+finale*30,a,.6);sweep(u=>[1830+Math.cos(u*TAU)*55,390+Math.sin(u*TAU)*96],pearl,0,2.5);
 }else if(theme==='dragon'){
  const a='#c6b1ff',b='#ffe0a2',mint='#99e9d1';
  // A procession of glass lanterns carried by dragons ascending the two sides.
  for(let j=0;j<7;j++){const q=smooth((t-.35-j*.2)/5.5),side=j%2,x=side?1820+Math.sin(q*5+j)*45:93+Math.sin(q*5+j)*33,y=990-q*(350+j%4*164);s.dragon(x,y,91+j%3*13,j%2?a:mint,j);s.lantern(x-26,y+61,44,b,Math.sin(t*2+j)*.08);}
  for(let j=0;j<9;j++){const x=268+j*172,y=22+Math.sin(t*.8+j)*5;s.lantern(x,y,34+j%3*7,j%2?b:a,Math.sin(t*1.5+j)*.09);line([[x,0],[x,y-19]],b,.7,.6);}
  for(let side=0;side<2;side++)for(let j=0;j<3;j++){const fn=u=>[side?1902-j*18+Math.sin(u*9+t*.4)*18:24+j*17+Math.sin(u*10+t*.4)*17,1050-u*872];ribbon(fn,j%2?a:mint,b,7+j*3,t*.8+j);sweep(fn,b,j*.14,1.6);}
  for(let j=0;j<6;j++){const x=330+j*254;s.gem(x,1028+Math.sin(t*1.4+j)*10,37+j%2*13,a,j*.3+p);s.bell(x+46,1052,27,b,Math.sin(t*3+j)*.14);}
  births(62,.2,.093,2,(u,j)=>{const x=j%2?1839+Math.sin(u*6+j)*53:77+Math.sin(u*8+j)*47,y=1010-u*851;w.star(x,y,1+j%3,mint,.8);});
  s.dragon(1584,84+(1-landing)*55,140,a,5);s.lantern(1530,121,46,b,.08);
 }else if(theme==='cat'){
  const a='#9de8ed',b='#e3baff',gold='#ffe0a2';
  // The cosmic express has five differently occupied carriages, articulated wheels.
  const travel=170+parade*1170;
  for(let j=0;j<5;j++){const x=travel+j*129,y=1012+Math.sin(t*2+j)*3;local(x,y,104,0,()=>{o.sheet([[-48,-25],[48,-25],[49,30],[-49,30]],j%2?a:b,p,{glass:true});o.sheet([[-43,-30],[42,-30],[32,-42],[-31,-42]],gold,p,{glass:true});for(const side of [-1,1]){ring(side*26,36,12,12,a,.9);line([[side*26-10*Math.cos(t*3),36-10*Math.sin(t*3)],[side*26+10*Math.cos(t*3),36+10*Math.sin(t*3)]],gold,1);}line([[-56,22],[-48,22],[48,22],[57,22]],gold,1.5);s.cat(0,-9,45,j%2?gold:a,j);});}
  for(let side=0;side<2;side++)for(let j=0;j<3;j++){const x=side?1875-j*10:44+j*10,y=309+j*187;ring(x,y,39+j*6,78,a,.55,-.3);sweep(u=>[x+Math.cos(u*TAU)*43,y+Math.sin(u*TAU)*81],j%2?b:gold,j*.16,1.8);if(j!==1)s.cat(x,y,64,j%2?a:b,j);}
  for(let j=0;j<38;j++){const x=290+j*39,y=12+Math.sin(j+t*.6)*9;w.star(x,y,1+j%4,j%2?a:gold,.55);}
  for(let j=0;j<2;j++){const fn=u=>[160+u*1650,1063+j*6];curve(fn,a,1,.6);sweep(fn,b,j*.08,2);}
  births(45,.4,.14,1.5,(u,j)=>{const side=j%2,x=side?1886-29*Math.sin(u*Math.PI):40+30*Math.sin(u*Math.PI),y=210+u*640;foil(x,y,6+j%4,j%2?b:a,u+j);});
  // A tiny station canopy unfurls late, with an actual swinging departure bell.
  local(1837,398,114,0,()=>{path(q=>{q.moveTo(-55,0);q.lineTo(-40,-23*landing);q.lineTo(39,-23*landing);q.lineTo(56,0);q.closePath();},b,.35);line([[-39,0],[-39,82],[39,82],[39,0]],a,1.5,.7);s.bell(0,17,40,gold,Math.sin(t*3)*.1);});
 }else{
  const a='#b9eca2',b='#ecb7db',mint='#8eede0';
  // A lily-pad carnival: jumping frogs, petal fans and little glass drum kits.
  for(let j=0;j<8;j++){const x=271+j*206,y=1046+Math.sin(j)*5,hop=Math.max(0,Math.sin((t-j*.13)*3))*13;s.leaf(x,y,91,a,-1.4);s.frog(x,y-41-hop,57+j%3*9,j%2?a:mint,j);s.bow(x,y-75-hop,24,b);ring(x,y+5,67,11,mint,.55);}
  for(let j=0;j<6;j++){const side=j%2,x=side?1839:81,y=249+j%3*196;local(x,y,92,Math.sin(t*2+j)*.04,()=>{for(let n=0;n<5;n++){const angle=n*TAU/5+t*.1;s.leaf(Math.cos(angle)*24,Math.sin(angle)*24,48,n%2?a:b,angle+.9);}s.frog(0,4,61,mint,j);});}
  local(1840,655,137,0,()=>{disc(0,9,37,20,metal([-37,-9,39,29],['#eaffe9',mint,'#24564c',b]));ring(0,-4,38,15,b,.8);line([[-25,12],[-25,38],[25,38],[25,12]],a,2,.7);const q=Math.sin(t*6)*7;line([[-45,-24],[-11,-7-q]],b,2.3);line([[47,-22],[15,-7+q]],a,2.3);s.frog(0,-48,67,a,4);});
  for(let j=0;j<4;j++){const fn=u=>[180+u*1560,1064-j*4+Math.sin(u*16-t*.6+j*.5)*(7+j*2)];curve(fn,mint,1,.5);sweep(fn,j%2?b:mint,j*.14,1.5);}
  births(55,.3,.105,2,(u,j)=>{const x=j%2?1842+Math.sin(u*6+j)*43:79+Math.sin(u*6+j)*43,y=1010-u*847;s.leaf(x,y,13+j%3*6,j%2?a:b,u+j);});
  for(let j=0;j<15;j++){const x=300+j*96;s.leaf(x,14+Math.sin(t+j)*6,22,j%2?a:b,j*.4);}
 }
}

// Generosity scenes: treasure, alchemy, observatory and botanical sound garden.
function cheerPerformance(c,theme,t,duration,seed){
 const i=partyInk(c,t,duration),s=partyProps(i),{p,o,w,line,curve,disc,poly,path,metal,local,sweep,ribbon,ring,foil,births}=i;
 const open=smooth((t-.4)/1.2),rise=smooth((t-1.9)/2.3);
 if(theme==='crab'){
  const a='#b0eded',b='#ffc8a5',gold='#f7e3b9';
  // Hinged glass treasure chest. Pearls are collected by three small crabs.
  local(110,532,166,0,()=>{o.sheet([[-40,-15],[40,-15],[38,31],[-38,31]],a,p,{glass:true});o.sheet([[-41,-17-open*32],[41,-17-open*32],[38,-44-open*20],[-38,-44-open*20]],b,p,{glass:true});line([[-42,-15],[42,-15]],gold,2);s.gem(0,9,19,gold);for(let j=0;j<4;j++)o.orb(-23+j*14,-12,7,gold,t+j,{glass:true});});
  for(let j=0;j<4;j++){const x=j%2?1828:107,y=268+j%2*369;s.crab(x,y+Math.sin(t*3+j)*6,81,b,j);s.gem(x+43,y-27,31,a,t+j);}
  births(48,.8,.115,2.5,(u,j)=>{const side=j%2,x=side?1815+Math.sin(u*Math.PI)*65:108-Math.sin(u*Math.PI)*50,y=720-u*515;o.orb(x,y,4+j%4*2,gold,t+j,{glass:true});});
  for(let j=0;j<10;j++){const x=288+j*157,y=1046+Math.sin(t*2+j)*7;s.bow(x,y,35,j%2?a:b);ring(x,y,28,12,gold,.5);}
  for(let j=0;j<3;j++){const fn=u=>[1835+Math.sin(u*8+t*.3+j)*41,1020-u*846];ribbon(fn,a,b,9+j*3,t+j);sweep(fn,gold,j*.18,1.6);}
  for(let j=0;j<14;j++)o.orb(290+j*96,18+Math.sin(t*2+j)*5,3+j%3,gold,t+j,{glass:true});
 }else if(theme==='dragon'){
  const a='#c8abff',b='#ffd99c',mint='#95ece0';
  // A retort distils one gem into a constellation of hanging amethyst droplets.
  local(1817,445,171,0,()=>{path(q=>{q.moveTo(-12,-64);q.lineTo(-12,-23);q.bezierCurveTo(-55,4,-37,48,0,49);q.bezierCurveTo(37,49,58,2,12,-23);q.lineTo(12,-64);q.closePath();},metal([-40,-66,39,52],['#e7fcff52',a+'4c','#1d315426',mint+'54']),.9);ring(0,-65,15,5,b,.9);curve(u=>[-28+u*56,20+Math.sin(u*8+t*2)*3],a,2,.7);s.gem(0,15,37,a,t*.2);line([[12,-54],[40,-65],[56,-32],[46,-9]],b,2,.8);disc(46,4+rise*25,5,8,mint,.7);});
  for(let j=0;j<7;j++){const x=j%2?1878:56,y=239+j%4*169;s.gem(x,y+Math.sin(t*2+j)*10,45+j%3*13,j%3?a:mint,j*.3+p);ring(x,y,31,57,b,.35,.2);line([[x,Math.max(175,y-100)],[x,y-36]],b,.8,.65);}
  for(let j=0;j<5;j++){const x=377+j*283,y=1038;s.lantern(x,y,44+j%2*12,j%2?a:b,Math.sin(t*2+j)*.1);s.gem(x+37,y+12,29,mint,j+p);}
  births(52,.6,.105,2.1,(u,j)=>{const x=j%2?1850+Math.sin(u*7+j)*32:71+Math.sin(u*7+j)*42,y=1000-u*801;foil(x,y,5+j%5,j%2?a:b,u+j);});
  for(let side=0;side<2;side++)for(let j=0;j<2;j++){const fn=u=>[side?1895-j*17+Math.sin(u*12+t*.25)*14:20+j*20+Math.sin(u*12+t*.25)*14,1037-u*860];curve(fn,a,1,.25);sweep(fn,mint,j*.16,2);}
  for(let j=0;j<12;j++){const x=310+j*109;s.gem(x,15,19,j%2?a:b,t+j);}
 }else if(theme==='cat'){
  const a='#a3eaf1',b='#f3bedb',gold='#ffe3ac';
  // Telescope, changing star mobiles and a cat in a tiny orbital capsule.
  local(105,399,145,-.23,()=>{o.sheet([[-40,-17],[25,-17],[49,-26],[49,25],[25,15],[-40,15]],a,p,{glass:true});ring(48,0,8,25,b,.8);line([[-9,15],[-32,68],[-9,45],[29,68]],gold,2);o.orb(48,0,13,gold,t,{glass:true,flat:.65});});
  for(let j=0;j<4;j++){const x=j%2?1848:80,y=233+j%2*390;ring(x,y,46,67,a,.6,-.35);sweep(u=>[x+Math.cos(u*TAU)*46,y+Math.sin(u*TAU)*67],b,j*.15,2);s.cat(x,y,67,j%2?a:b,j);for(let n=0;n<3;n++){const q=t*.4+n*TAU/3;w.star(x+Math.cos(q)*48,y+Math.sin(q)*71,3,gold,.8);}}
  for(let j=0;j<8;j++){const x=277+j*209,y=1046+Math.sin(t+j)*8;ring(x,y,28,9,b,.45);w.star(x,y-12,9+j%3*3,j%2?a:gold,.9);line([[x,y-3],[x,y+17]],a,.8,.5);}
  for(let j=0;j<3;j++){const fn=u=>[290+u*1300,1063-Math.sin(u*Math.PI)*(13+j*13)];curve(fn,a,.8,.35);sweep(fn,j%2?b:gold,j*.16,1.8);}
  births(61,.35,.09,1.4,(u,j)=>{const x=j%2?1844+Math.sin(u*7+j)*55:61+Math.sin(u*9+j)*44,y=199+u*625;w.star(x,y,1+j%3,j%3?a:b,.8);});
  for(let j=0;j<22;j++){const x=290+j*66;w.star(x,15+Math.sin(t*.7+j)*5,1+j%3,gold,.7);if(j%3===0)line([[x,14],[x+66,18]],a,.7,.4);}
 }else{
  const a='#bbeba6',b='#f3bdd7',mint='#97ede0';
  // A botanical wind instrument: bubble keys open and frog musicians answer.
  for(let side=0;side<2;side++)for(let j=0;j<5;j++){const x=side?1875-j%2*19:36+j%2*18,y=230+j*154;const stem=u=>[x+Math.sin(u*2+t*.3+j)*14,1050-u*(1060-y)*open];curve(stem,a,2,.7);sweep(stem,mint,j*.08,1.3);s.leaf(x+13,y+22,47,a,-.9);o.orb(x,y,13+j%3*4,mint,t+j,{glass:true});line([[x,y+21],[x,y+37],[x+12,y+34]],b,1.3,.8);}
  for(let j=0;j<4;j++){const x=j%2?1817:117,y=340+j%2*327;s.frog(x,y+Math.sin(t*3+j)*6,85,j%2?a:mint,j);s.bell(x+41,y-11,32,b,Math.sin(t*3+j)*.12);}
  for(let j=0;j<8;j++){const x=283+j*208,y=1044;s.leaf(x,y,73,j%2?a:b,-1.3);o.orb(x,y-13-Math.sin(t*3+j)*4,8,mint,t+j,{glass:true});}
  births(53,.5,.11,1.8,(u,j)=>{const x=j%2?1830+Math.sin(u*7+j)*36:99+Math.sin(u*7+j)*31,y=970-u*740;s.leaf(x,y,17+j%3*8,j%3?a:b,j*.6+u);});
  for(let j=0;j<3;j++){const fn=u=>[220+u*1490,1065-j*5+Math.sin(u*15-t*.5+j)*9];curve(fn,mint,1,.4);sweep(fn,b,j*.17,1.7);}
  for(let j=0;j<15;j++)s.leaf(291+j*96,15+Math.sin(t+j)*4,19,j%2?a:b,j*.3);
 }
}

export const celebrationArtReady=Promise.resolve();
export const RAID_WORLDS={
 crab:{title:'THE HARBOR IS HOPPING',label:'Pearl harbor',colors:['#f3c18d','#7ddbdc','#e7ebdc']},
 dragon:{title:'A LITTLE MAGIC JUST LANDED',label:'Lantern migration',colors:['#c0a0f0','#f5ce8a','#85dbc9']},
 cat:{title:'NEXT STOP: GOOD COMPANY',label:'Celestial railway',colors:['#93d9ee','#deb2e4','#f5d699']},
 frog:{title:'ROOM FOR THE WHOLE POND',label:'Moonlit water garden',colors:['#b0dc91','#e5b3cc','#92dfd0']}
};
export function celebrationWorld(c,theme,t,duration,mode='raid',seed=0){
 if(mode==='raid')raidPerformance(c,theme,t,duration,seed);
 else if(mode==='cheer')cheerPerformance(c,theme,t,duration,seed);
 else supporterPerformance(c,theme,t,duration,mode==='gift',seed);
}
export class RaidArt{
 constructor(canvas){this.canvas=canvas;this.c=canvas.getContext('2d');this.finish=new EdgeFinish();this.ready=celebrationArtReady;}
 clear(){this.c.clearRect(0,0,1920,1080);}
 start(item){this.theme=RAID_WORLDS[item.theme]?item.theme:'crab';this.seed=Array.from(String(item.id||item.name)).reduce((v,ch)=>(v*31+ch.charCodeAt(0))>>>0,7);}
 draw(t,reduced=false){const c=this.c;c.clearRect(0,0,1920,1080);if(t<0||t>=8)return;c.save();c.globalAlpha=smooth(t/.65)*smooth((8-t)/.75);celebrationWorld(c,this.theme,reduced?4.6:t,8,'raid',this.seed);c.restore();this.finish.apply(c,10);}
}
