"""Authored emotional still selection; no download or runtime resource effects."""

# Alternating loss, joy and triumph makes the emotional contrast read in fast cuts.
SHOTS = [
    dict(id='interstellar',title='Interstellar · Cooper watching the messages',emotion='grief',source='https://www.gq.com.mx/entretenimiento/articulo/escenas-que-hacen-llorar-a-cualquier-hombre',image='https://media.gq.com.mx/photos/5de80d12f428fa0008c86a3d/16%3A9/w_1920%2Cc_limit/escenas-que-hacen-llorar.png'),
    dict(id='soul',title='Soul · Joe rediscovers life',emotion='wonder',source='https://www.slashfilm.com/1650680/pixar-saddest-movie-moments-ranked/',image='https://www.slashfilm.com/img/gallery/saddest-pixar-moments-ranked/joes-epiphany-in-soul-1724694238.jpg'),
    dict(id='happyness',title='The Pursuit of Happyness · finally hired',emotion='tears of joy',source='https://www.youtube.com/watch?v=56fngopihOo',image='https://i.ytimg.com/vi/56fngopihOo/maxresdefault.jpg'),
    dict(id='monsters',title='Monsters, Inc. · Sulley and Boo',emotion='farewell',source='https://www.slashfilm.com/1650680/pixar-saddest-movie-moments-ranked/',image='https://www.slashfilm.com/img/gallery/saddest-pixar-moments-ranked/sulley-says-goodbye-to-boo-in-monsters-inc-1724694238.jpg'),
    dict(id='titanic',title='Titanic · Jack and Rose’s farewell',emotion='heartbreak',source='https://genial.guru/articles/15-escenas-de-peliculas-que-inevitablemente-nos-hacen-sentir-un-nudo-en-la-garganta-1355910/',image='https://wl-genial.cf.tsp.li/resize/728x/jpg/f3b/571/e5fd83597aa0d2acfba0cb0945.jpg'),
    dict(id='walle',title='WALL-E · lost recognition',emotion='longing',source='https://www.slashfilm.com/1650680/pixar-saddest-movie-moments-ranked/',image='https://www.slashfilm.com/img/gallery/saddest-pixar-moments-ranked/wall-e-forgets-eve-in-wall-e-1724694238.jpg'),
    dict(id='rocky',title='Rocky · the steps',emotion='triumph',source='https://getwallpapers.com/collection/rocky-balboa-wallpaper',image='https://getwallpapers.com/wallpaper/full/9/2/4/1127485-free-download-rocky-balboa-wallpaper-1920x1200.jpg'),
    dict(id='dory',title='Finding Dory · family',emotion='belonging',source='https://www.slashfilm.com/1650680/pixar-saddest-movie-moments-ranked/',image='https://www.slashfilm.com/img/gallery/saddest-pixar-moments-ranked/dory-reunites-with-her-parents-in-finding-dory-1724694238.jpg'),
    dict(id='dobby',title='Harry Potter · farewell to Dobby',emotion='loss',source='https://www.slashfilm.com/1916959/why-harry-potter-hermione-house-elves-subplot-hbo-biggest-challenge/',image='https://www.slashfilm.com/img/gallery/why-harry-potters-controversial-hermione-house-elves-subplot-is-hbos-biggest-challenge/how-did-the-movies-handle-this-storyline-they-didnt-1753019308.jpg'),
    dict(id='elemental',title='Elemental · Ember’s tears',emotion='vulnerability',source='https://www.slashfilm.com/1650680/pixar-saddest-movie-moments-ranked/',image='https://www.slashfilm.com/img/gallery/saddest-pixar-moments-ranked/ember-tells-the-truth-in-elemental-1724694238.jpg'),
    dict(id='lotr',title='The Return of the King · you bow to no one',emotion='recognition',source='https://nofilmschool.com/you-bow-to-no-one-lotr-return-of-the-king',image='https://nofilmschool.com/media-library/a-still-from-the-lord-of-the-rings-the-return-of-the-king-2003.jpg?coordinates=0%2C0%2C0%2C0&height=700&id=62642462&width=1245'),
    dict(id='nemo',title='Finding Nemo · Marlin’s loss',emotion='grief',source='https://www.slashfilm.com/1650680/pixar-saddest-movie-moments-ranked/',image='https://www.slashfilm.com/img/gallery/saddest-pixar-moments-ranked/marlin-loses-his-family-in-finding-nemo-1724694238.jpg'),
    dict(id='jesse',title='Breaking Bad · Jesse’s escape',emotion='release',source='https://www.slashfilm.com/961617/jesse-pinkman-was-the-true-heart-and-soul-of-breaking-bad/',image='https://www.slashfilm.com/img/gallery/jesse-pinkman-was-the-true-heart-and-soul-of-breaking-bad/a-kicked-puppy-1660241010.jpg'),
    dict(id='coco',title='Coco · Miguel and Mamá Coco',emotion='remembrance',source='https://www.slashfilm.com/1650680/pixar-saddest-movie-moments-ranked/',image='https://www.slashfilm.com/img/gallery/saddest-pixar-moments-ranked/remember-me-from-coco-1724694238.jpg'),
    dict(id='friends',title='Friends · Chandler and Monica’s proposal',emotion='love',source='https://canaltech.com.br/entretenimento/friends-momentos-mais-emocionantes/',image='https://t.ctcdn.com.br/X1l9RaCu0gKdX-l9KtBVyyUZAwM%3D/1024x0/smart/i384534.jpeg'),
    dict(id='logan',title='Logan · Laura’s farewell',emotion='loss',source='https://www.looper.com/130351/the-most-powerful-sad-endings-in-cinematic-history/',image='https://www.looper.com/img/gallery/the-most-powerful-sad-endings-in-cinematic-history/logan-1770131852.jpg'),
    dict(id='up',title='Up · Carl and Ellie',emotion='loss',source='https://www.slashfilm.com/590314/the-best-pixar-scenes-ranked/',image='https://www.slashfilm.com/img/gallery/the-15-best-pixar-scenes-ranked/2-up-opening-montage-1626381083.jpg'),
    dict(id='infinitywar',title='Infinity War · Peter and Tony',emotion='heartbreak',source='https://www.looper.com/130351/the-most-powerful-sad-endings-in-cinematic-history/',image='https://www.looper.com/img/gallery/the-most-powerful-sad-endings-in-cinematic-history/avengers-infinity-war-1770131852.jpg'),
    dict(id='endgame',title='Avengers: Endgame · Captain America is worthy',emotion='victory',source='https://www.adorocinema.com/noticias/filmes/noticia-1000040767/',image='https://br.web.img3.acsta.net/img/c5/c8/c5c898f7179ba733da1c110cbea45f88.jpg'),
    dict(id='terminator',title='Terminator 2 · farewell',emotion='sacrifice',source='https://www.looper.com/130351/the-most-powerful-sad-endings-in-cinematic-history/',image='https://www.looper.com/img/gallery/the-most-powerful-sad-endings-in-cinematic-history/terminator-2-judgment-day-1770131856.jpg'),
    dict(id='office',title='The Office · Jim and Michael’s goodbye',emotion='farewell',source='https://rollingstone.com.br/noticia/office-john-krasinski-chorou-de-verdade-em-cena-emotiva-entre-jim-e-michael-scott/',image='https://rollingstone.com.br/wp-content/uploads/jim-michael-john-krasinski-steve-carell-the-office-reproducao.jpg'),
    dict(id='notebook',title='The Notebook · together at last',emotion='love',source='https://www.looper.com/130351/the-most-powerful-sad-endings-in-cinematic-history/',image='https://www.looper.com/img/gallery/the-most-powerful-sad-endings-in-cinematic-history/the-notebook-1770131860.jpg'),
    dict(id='eleven',title='Stranger Things · Eleven and Hopper reunited',emotion='relief',source='https://tvobsessive.com/2022/07/26/favorite-moments-from-stranger-things-season-4/',image='https://tvobsessive.com/wp-content/uploads/2022/07/maxresdefault-700x394.jpg'),
    dict(id='manonfire',title='Man on Fire · Pita and Creasy',emotion='reunion',source='https://www.looper.com/130351/the-most-powerful-sad-endings-in-cinematic-history/',image='https://www.looper.com/img/gallery/the-most-powerful-sad-endings-in-cinematic-history/man-on-fire-1770131848.jpg'),
    dict(id='toystory',title='Toy Story 3 · so long, partner',emotion='farewell',source='https://vlipsy.com/clips/toy-story-3-so-long-partner-ID8NhEgt',image='https://cdn.vlipsy.com/clips/ID8NhEgt/preview.jpg'),
    dict(id='callme',title='Call Me by Your Name · Elio’s tears',emotion='heartbreak',source='https://www.looper.com/130351/the-most-powerful-sad-endings-in-cinematic-history/',image='https://www.looper.com/img/gallery/the-most-powerful-sad-endings-in-cinematic-history/call-me-by-your-name-1770131866.jpg'),
    dict(id='shawshank',title='The Shawshank Redemption · freedom in the rain',emotion='liberation',source='https://nofilmschool.com/2016/04/100-most-iconic-shots-100-years-cinema',image='https://nofilmschool.com/media-library/shawshank.jpg?coordinates=259%2C0%2C31%2C0&height=1500&id=34065616&width=2000'),
    dict(id='irongiant',title='The Iron Giant · Hogarth and the Giant',emotion='friendship',source='https://www.slashfilm.com/1445794/superman-moment-the-iron-giant-best-action-scene-ever/',image='https://www.slashfilm.com/img/gallery/the-superman-moment-in-the-iron-giant-is-the-best-action-scene-ever/the-key-moment-1699913058.jpg'),
    dict(id='forrest',title='Forrest Gump · Jenny and Forrest',emotion='regret',source='https://www.looper.com/657829/tom-hanks-movie-moments-that-made-us-cry/',image='https://www.looper.com/img/gallery/tom-hanks-movie-moments-that-made-us-cry/when-he-visits-jennys-grave-in-forrest-gump-1636589329.jpg'),
    dict(id='insideout',title='Inside Out · Riley and her parents',emotion='comfort',source='https://filmaholic.tw/films/666ef9bbfd8978000100940a/',image='https://images.vocus.cc/27e8dbff-e22c-4765-a4c4-85acaa803224.jpg'),
    dict(id='lalaland',title='La La Land · the last look',emotion='bittersweet',source='https://www.buzzfeed.com/devinherenda/which-movies-had-perfect-endings',image='https://img.buzzfeed.com/buzzfeed-static/static/2023-04/15/14/asset/bbaab0b30d83/sub-buzz-564-1681570424-2.jpg?downsize=900%3A%2A&output-format=auto&output-quality=auto'),
    dict(id='lastofus',title='The Last of Us · Joel and Ellie reunited',emotion='reassurance',source='https://www.looper.com/1218811/tlou-episode-8-brought-an-iconic-joel-and-ellie-moment-to-the-small-screen/',image='https://www.looper.com/img/gallery/tlou-episode-8-gives-fans-the-joel-and-ellie-moment-theyve-been-waiting-for/the-pet-name-that-broke-a-million-hearts-1678122146.jpg'),
    dict(id='goodwill',title='Good Will Hunting · Will and Sean’s embrace',emotion='healing',source='https://fandomwire.com/24-most-heart-wrenching-movie-scenes-ever/',image='https://patricklmitchell.files.wordpress.com/2013/10/good-will-hunting-1997-xvid-dts-cd3-waf-avi_001529070.jpg'),
    dict(id='lionking',title='The Lion King · Simba beside Mufasa',emotion='grief',source='https://medium.com/@iammelo/mufasas-death-and-the-importance-of-naming-emotions-5632d9ec5cfd',image='https://miro.medium.com/v2/1*B6RssNgugowpzeGOUSDWcg.png'),
    dict(id='greenmile',title='The Green Mile · John Coffey’s tears',emotion='sorrow',source='https://www.looper.com/331618/how-the-green-mile-is-different-than-the-book/',image='https://www.looper.com/img/gallery/how-the-green-mile-is-different-than-the-book/intro-1612990961.jpg'),
]


def shot_file(shot):
    return 'shot-'+shot['id']+'.jpg'
