// Public preview entry point + actual feature HTTP fixture; no Twitch or OBS events.
const {chromium}=require('playwright'),{spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=process.env.BORDER_REVIEW_ARTIFACT_DIR||path.join(root,'tmp_obs_debug');
const server=spawn('py',['-3.11','-X','utf8','-u','tools/celebration_fixture.py'],{cwd:root,windowsHide:true,stdio:['pipe','pipe','pipe']});server.stderr.on('data',d=>process.stderr.write(d));
const endpoint=new Promise((resolve,reject)=>{let buffer='';const timer=setTimeout(()=>reject(Error('Fixture startup timeout')),10000);server.stdout.on('data',d=>{buffer+=d;const line=buffer.split(/\r?\n/).find(x=>x.startsWith('{'));if(line){clearTimeout(timer);resolve('http://127.0.0.1:'+JSON.parse(line).port);}});server.on('exit',code=>{clearTimeout(timer);reject(Error('Fixture exited '+code));});});
(async()=>{let browser;try{const base=await endpoint;browser=await chromium.launch({headless:true,channel:'chrome',args:['--mute-audio']});const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.audioLog=[];window.Audio=class{constructor(src){this.src=src;window.audioLog.push(this);}play(){return Promise.resolve();}pause(){this.paused=true;}};});await page.goto(base+'/overlay?preview');await page.evaluate(async()=>await (await import('/supporter_show.js')).artReady);
 const hashes=[];let maxMs=0;
 for(const theme of ['crab','dragon','cat','frog']){
  const item={id:'cheer-'+theme,kind:'cheer',theme,name:'TheViewer <3 & Friends',count:2645,duration:7,elapsed:0};
  await page.evaluate(item=>window.postMessage({type:'preview',item,settings:{volume:.22,muted:true,custom:{}}},location.origin),item);await page.waitForTimeout(150);
  assert.equal(await page.locator('#name').textContent(),item.name);assert((await page.locator('#detail').textContent()).includes('2,645 Bits'));assert.equal(await page.locator('.mascot').count(),0);
  const check=await page.evaluate(async item=>{const {CheerShow}=await import('/cheer_show.js');const art=new CheerShow(document.getElementById('stage'));art.start(item,{custom:{}});const frames=[];for(const t of [0,.8,1.8,3.5,5.8,6.7,7]){art.update(t);const pixels=art.c.getImageData(0,0,1920,1080).data;let count=0,max=0;for(let i=3;i<pixels.length;i+=4){if(pixels[i])count++;max=Math.max(max,pixels[i]);}frames.push({t,count,max,center:art.c.getImageData(240,170,1440,670).data.some((v,i)=>i%4===3&&v),image:art.canvas.toDataURL()});}const start=performance.now();for(let j=0;j<60;j++)art.update(2+j/30);const ms=(performance.now()-start)/60;art.update(3.5);const image=art.canvas.toDataURL();const panel=document.getElementById('banner').getBoundingClientRect();art.stop();return {frames,ms,image,bottom:panel.bottom};},item);
  assert(check.frames.every(f=>!f.center));assert.equal(check.frames[0].count,0);assert.equal(check.frames.at(-1).count,0);assert(check.frames.some(f=>f.max>230&&f.count>2000));assert.equal(new Set(check.frames.slice(1,-1).map(f=>f.image)).size,5);assert(check.ms<30);assert(check.bottom<170);maxMs=Math.max(maxMs,check.ms);hashes.push(crypto.createHash('sha256').update(check.image).digest('hex'));
  await page.evaluate(()=>window.postMessage({type:'stop'},location.origin));await page.waitForTimeout(550);assert.equal(await page.locator('#cheerLayer').count(),0);
 }
 assert.equal(new Set(hashes).size,4);
 for(const width of [1920,960]){await page.setViewportSize({width,height:width*9/16});await page.evaluate(()=>window.postMessage({type:'preview',item:{id:'name',kind:'cheer',theme:'dragon',name:'W'.repeat(48),count:1,duration:7,elapsed:2},settings:{volume:.22,muted:true,custom:{}}},location.origin));await page.waitForTimeout(100);assert(await page.locator('#name').evaluate(n=>n.scrollWidth<=n.clientWidth+1),'Long runtime name must fit');}await page.setViewportSize({width:1920,height:1080});
 await page.evaluate(()=>window.postMessage({type:'preview',item:{id:'custom',kind:'cheer',theme:'cat',name:'Personal',count:1,duration:7,elapsed:1},settings:{volume:.4,muted:false,custom:{cat:{visual:'minions-dance.mp4',audio:'cat.wav'}}}},location.origin));await page.waitForTimeout(150);assert.equal(await page.locator('#cheerCustom').count(),1);assert(await page.evaluate(()=>audioLog.at(-1).src.endsWith('/cat.wav')));await page.evaluate(()=>window.postMessage({type:'stop'},location.origin));await page.waitForTimeout(550);assert.equal(await page.locator('#cheerLayer').count(),0);assert(await page.evaluate(()=>audioLog.every(a=>a.paused)));
 assert.equal((await (await fetch(base+'/api/state')).json()).queue,0);
 const context=await browser.newContext({viewport:{width:1920,height:1080},recordVideo:{dir:out,size:{width:1920,height:1080}}}),review=await context.newPage();await review.goto(base+'/overlay?preview');await review.evaluate(base=>{document.body.innerHTML='';document.body.style.cssText='background:#152332;display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:14px';for(const theme of ['crab','dragon','cat','frog']){const p=document.createElement('div');p.style.cssText='background:radial-gradient(ellipse at center,#3c514d,#162c32);position:relative';const f=document.createElement('iframe');f.src=base+'/overlay?preview';f.dataset.theme=theme;f.style.cssText='position:relative;width:100%;height:100%;border:0';p.append(f);document.body.append(p);}},base);await review.waitForTimeout(700);await review.evaluate(()=>document.querySelectorAll('iframe').forEach(f=>f.contentWindow.postMessage({type:'preview',item:{id:f.dataset.theme,kind:'cheer',theme:f.dataset.theme,name:'SparklyNewFriend',count:2645,duration:7,elapsed:0},settings:{volume:0,muted:true,custom:{}}},location.origin)));await review.waitForTimeout(3200);await review.screenshot({path:path.join(out,'cheer-material-worlds.png')});await review.waitForTimeout(4500);const video=review.video();await context.close();await video.saveAs(path.join(out,'cheer-material-motion.webm'));assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,cheerWorlds:4,liveNames:true,clearCenter:true,maxFrameMs:Math.round(maxMs*100)/100}));
}finally{if(browser)await browser.close();server.stdin.end();}})().catch(e=>{console.error(e);process.exitCode=1;});
