// Real browser tests with disposable stats; no live observations or OBS writes.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {chromium} = require('playwright');
const web = path.resolve(__dirname,'../hub_ui/app');
const output = process.env.LEAGUE_STATS_TEST_OUTPUT || path.resolve(__dirname,'../output/league-stats');
const metric=(total,average=total)=>({total,average,games:1,completed_games:1});
const summary={completed_games:12,live_or_partial_games:1,wins:8,losses:4,win_rate:66.666,cs_per_minute:7.42,average_game_seconds:1560,kda:3.4,kill_participation:62,
 metrics:{kills:metric(85,7.08),deaths:metric(40,3.33),assists:metric(51,4.25),cs:metric(2291,190.9),missed_minions:metric(20),missed_melee:metric(8),missed_ranged:metric(8),missed_cannon:metric(4)}};
const state={status:'Tracking Jinx',history_status:'Recent match history is synchronized',settings:{helpers:['trusted'],allow_moderators:true,helper_enabled:true,cooldown_seconds:15,include_custom:false,region:'na1'},chat:{connected:true,status:'Listening to #caster (read only)'},accounts:['test-account'],champions:['Jinx'],queues:['420'],archive_path:'Example archive',
 current:{champion:'Jinx',state:'live',connected:true,duration:900,cs_per_minute:7.6,metrics:{kills:6,deaths:2,assists:5,cs:114,vision_score:8,missed_melee:3,missed_ranged:2,missed_cannon:1},items:[{id:1001,name:'Boots'}],observations:[]},summary,
 breakdowns:{enemy_adc:[{name:'Caitlyn',...summary}],ally_support:[],enemy_support:[],ally_adc:[],champion:[{name:'Jinx',...summary}]},items:[{name:'Boots',games:12,wins:8,win_rate:66.6}],matches:[]};
state.settings.custom_counters={bad_recall:'Bad recalls'};
state.sessions={current:{id:'current',name:'Friday ranked',started_at:1700000000},history:[{id:'previous',name:'Previous stream',started_at:1699900000,ended_at:1700000000}]};
state.insights={streak:{current:3,kind:'wins',longest_wins:5,longest_losses:2},records:[{metric:'cs',value:310,champion:'Jinx',games:12}],trends:[{metric:'cs_per_minute',recent:7.4,previous:6.8,change:0.6,recent_games:10,previous_games:10}],deathless_games:2,deathless_coverage:12};
state.matches=[{id:'p:7',champion:'Jinx',state:'complete',win:true,started_at:1700000000,duration:1200,metrics:{kills:6,deaths:2,assists:5,cs:170},items:[],review:{revision:0,note:''},observations:[{id:'obs1',actor:'trusted',metric:'missed_cannon',game_time:500}],timeline_version:1,timeline_checkpoints:{10:{sample_seconds:600,cs:72,cs_difference:-8,gold_difference:-200,xp_difference:100}}}];
state.enrichment={configured:false,state:'unconfigured',message:'Local tracking works without a Riot key',pending:0};
state.coverage={recorded:12,official:10,timelines:8};
state.ranked=[{queue:'RANKED_SOLO_5x5',label:'Solo / Duo',tier:'GOLD',division:'I',lp:15,session_movement:25,at:1700000000}];
state.recap={champion:'Jinx',win:true,metrics:{kills:6,deaths:2,assists:5,cs_per_minute:7.5}};
state.progress={cs_target:7,reached_games:8,covered_games:12,success_rate:66.6};
state.settings.cs_goal=7;
state.account_labels={'test-account':'Tester#NA1'};
state.live_progress={available:true,target:7,cs:114,expected_cs:105,cs_per_minute:7.6,difference:9,needed:0,on_target:true};
state.session_summary=summary;state.session_insights=state.insights;
state.form=Array.from({length:12},(_,i)=>({id:i===11?'p:7':'p:'+String(i+8),champion:i%2?'Jinx':'Ashe',win:i%3!==0,started_at:1700000000+i*2000,duration:1200,metrics:{...(i===4?{}:{cs_per_minute:5.5+i*.3}),kills:i+2,deaths:i%5,vision_score:8+i,damage_per_minute:600+i*20}}));
state.current.observations=[{id:'liveobs',actor:'trusted',label:'Cannon miss',metric:'missed_cannon',game_time:880,at:Date.now()/1000-30}];
state.settings.chat_replies=true;
state.chat.delivery={ready:true,message:'Ready · replies from @caster'};
state.reply_previews=[{topic:'cs',command:'!stats cs',label:'🌾 Farming',text:'🌾 Session CS · 2,291 total · 7.42/min (completed)'},{topic:'kda',command:'!stats kda',label:'⚔️ K / D / A',text:'⚔️ Session K/D/A · 85 / 40 / 51 · 3.40 KDA (completed)'},{topic:'help',command:'!stats',label:'📖 Command guide',text:'📖 Stats → !stats cs · !stats kda'}];
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],posts=[],queries=[];let delayReview=false,releaseReview=null;
  page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.__copied=text;}}}));
  await page.route('http://stats.test/**',async route=>{
   const u=new URL(route.request().url());
   if(u.pathname.startsWith('/api/league-stats')){
    if(route.request().method()==='POST'){
     const body=route.request().postDataJSON();posts.push({path:u.pathname,body});
     if(u.pathname.endsWith('/review')){if(delayReview)await new Promise(resolve=>{releaseReview=resolve;});const m=state.matches.find(m=>m.id===body.id);if(m)m.review={note:body.note,excluded:body.excluded,revision:(m.review?.revision||0)+1};return route.fulfill({json:{ok:true,revision:m?.review.revision}});}
     return route.fulfill({json:{ok:true,text:'Observation counted'}});
    }
    queries.push(u.search);return route.fulfill({json:state});
   }
   if(u.pathname==='/test')return route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><link rel="stylesheet" href="/css/main.css"></head><body style="overflow:auto;height:auto;display:block"><main style="max-width:1300px;margin:25px auto;padding:20px" id="page"></main><div id="toasts"></div><script type="module">import {mount} from "/js/pages/league-stats.js";await mount(document.getElementById("page"));</script></body></html>'});
   const file=path.resolve(web,'.'+u.pathname);
   if(!file.startsWith(web+path.sep)||!fs.existsSync(file))return route.fulfill({status:404});
   return route.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html'});
  });
  async function clickPost(selector){const response=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().includes('/api/league-stats/'));await page.locator(selector).click();await response;}
  await page.goto('http://stats.test/test');
  await page.waitForFunction(()=>document.getElementById('lsCards')?.textContent.includes('7.42'));
  assert.match(await page.locator('#lsMatchups').innerText(),/Caitlyn/);
  assert.match(await page.locator('#lsAccount').innerText(),/Tester#NA1/);
  assert.equal(await page.locator('#lsFormMatches button').count(),12);
  assert.match(await page.locator('#lsFormCoverage').innerText(),/11\/12 games/);
  assert.equal((await page.locator('.ls-chart-line').getAttribute('d')).match(/M/g).length,2,'Missing CS must split the line');
  await page.selectOption('#lsFormMetric','deaths');assert.match(await page.locator('#lsFormCoverage').innerText(),/12\/12 games reported deaths/);
  assert.equal(await page.locator('.ls-chart-goal').count(),0);
  await page.selectOption('#lsFormMetric','cs_per_minute');
  await page.locator('#lsFormMatches button').last().click();assert.equal(await page.inputValue('#lsReviewMatch'),'p:7');
  assert.match(await page.locator('#lsLivePace').innerText(),/9 CS above pace/);
  assert.match(await page.locator('#lsHelperFeed').innerText(),/Cannon miss.*trusted/);
  assert.equal(await page.locator('#lsSetup').getAttribute('open'),null,'Setup starts folded away from daily controls');
  await page.locator('[data-jump="lsSetup"]').click();
  await page.selectOption('#lsOverlayView','rotate');await page.selectOption('#lsOverlayTheme','violet');await page.selectOption('#lsOverlayCycle','20');
  const overlayUrl=new URL(await page.inputValue('#lsOverlayUrl'));assert.equal(overlayUrl.searchParams.get('theme'),'violet');assert.equal(overlayUrl.searchParams.get('cycle'),'20');
  const previewPostCount=posts.length;await page.click('#lsPreviewOverlay');
  await page.frameLocator('#lsOverlayPreview iframe').locator('main').waitFor();assert.equal(posts.length,previewPostCount,'Overlay preview cannot change OBS or counters');
  await page.click('#lsCopyOverlay');assert.equal(await page.evaluate(()=>window.__copied),overlayUrl.href);
  await page.click('#lsPreviewOverlay');assert.equal(await page.locator('#lsOverlayPreview iframe').count(),0,'Hidden preview must stop its polls');
  assert.match(await page.locator('#lsReplyPreview').innerText(),/🌾 Session CS.*2,291/);
  const postCount=posts.length;await page.selectOption('#lsReplyCommand','help');
  assert.match(await page.locator('#lsReplyPreview').innerText(),/📖 Stats →/);
  assert.equal(posts.length,postCount,'Preview must never send a message');
  await page.locator('summary').filter({hasText:'Chat reply settings'}).click();
  await page.uncheck('#lsChatReplies');await page.waitForTimeout(2200);
  assert.equal(await page.isChecked('#lsChatReplies'),false,'Polling must preserve unsaved chat preference');
  await clickPost('#lsSaveReplies');assert.deepEqual(posts.at(-1).body,{chat_replies:false});
  await page.selectOption('#lsReplyCommand','cs');
  await page.selectOption('#lsBreakdown','ally_support');assert.match(await page.locator('#lsMatchups').innerText(),/No completed games/);
  await page.selectOption('#lsPeriod','today');await page.waitForFunction(()=>document.getElementById('lsExport').href.includes('period=today'));
  assert(queries.some(q=>q.includes('period=today')));
  await clickPost('[data-miss="missed_cannon"]');assert.equal(posts.at(-1).body.metric,'missed_cannon');
  await page.locator('summary').filter({hasText:'Helper permissions & preferences'}).click();await page.fill('#lsHelpers','trusted, next_helper');
  await page.waitForTimeout(2200);assert.equal(await page.inputValue('#lsHelpers'),'trusted, next_helper','polls must not overwrite unsaved helper preferences');
  await clickPost('#lsSave');assert.deepEqual(posts.at(-1).body.helpers,['trusted','next_helper']);
  await page.fill('#lsCustomCounters','bad_recall = Bad recalls\nmissed_hook = Missed hooks');await clickPost('#lsSave');
  assert.equal(posts.at(-1).body.custom_counters.missed_hook,'Missed hooks');
  await page.selectOption('#lsSession','previous');await page.waitForFunction(()=>document.getElementById('lsExport').href.includes('session_id=previous'));
  await page.fill('#lsSessionName','Saturday climb');await clickPost('#lsNewSession');assert.equal(posts.at(-1).body.name,'Saturday climb');
  assert.match(await page.locator('#lsStreak').innerText(),/3 wins/);
  await page.fill('#lsMetricSearch','cannon');assert.match(await page.locator('#lsMetrics').innerText(),/missed cannon/);assert.doesNotMatch(await page.locator('#lsMetrics').innerText(),/missed melee/);
  await page.fill('#lsMetricSearch','');
  await page.fill('#lsReviewNote','Keep my unsaved note');
  state.matches.push({id:'p:99',champion:'Ashe',state:'complete',win:false,started_at:1700003000,duration:1300,metrics:{kills:1,deaths:4,assists:3,cs:100},items:[],review:{revision:0,note:'Existing review'},observations:[]});
  await page.waitForFunction(()=>document.getElementById('lsReviewMatch')?.options.length===2);
  await page.selectOption('#lsReviewMatch','p:99');assert.equal(await page.inputValue('#lsReviewNote'),'Existing review');
  await page.selectOption('#lsReviewMatch','p:7');assert.equal(await page.inputValue('#lsReviewNote'),'Keep my unsaved note','Switching games must preserve unsaved reviews');
  await page.locator('#lsFormMatches button').last().click();assert.equal(await page.inputValue('#lsReviewNote'),'Keep my unsaved note','Same-game shortcut must preserve the draft');
  state.matches[0].observations.push({id:'obs2',actor:'other',metric:'missed_melee',game_time:600});
  await page.waitForTimeout(2200);assert.equal(await page.inputValue('#lsReviewNote'),'Keep my unsaved note');
  await page.check('#lsExcludeMatch');await clickPost('#lsSaveReview');assert.equal(posts.at(-1).body.excluded,true);assert.equal(posts.at(-1).body.note,'Keep my unsaved note');
  delayReview=true;const pendingReview=page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/review'));await page.click('#lsSaveReview');await pendingReview;
  await page.fill('#lsReviewNote','Edited while the previous save is pending');
  assert(await page.isDisabled('#lsSaveReview'),'Duplicate saves must be bounded');
  const finishedReview=page.waitForResponse(r=>r.url().endsWith('/review'));releaseReview();await finishedReview;delayReview=false;
  await page.waitForFunction(()=>!document.getElementById('lsSaveReview').disabled);
  assert.equal(await page.inputValue('#lsReviewNote'),'Edited while the previous save is pending');
  assert.match(await page.locator('#lsReviewDraftState').innerText(),/Unsaved review/);
  await clickPost('#lsSaveReview');assert.equal(posts.at(-1).body.revision,2,'Later edits must use the newly saved revision');
  await page.locator('#lsObservationReview button').first().click();assert.equal(posts.at(-1).body.observation_id,'obs1');
  assert.match(await page.locator('#lsTimelineReview').innerText(),/-200/);
  assert.match(await page.locator('#lsRank').innerText(),/GOLD I.*25/);
  await page.fill('#lsCsGoal','8');await clickPost('#lsSaveGoal');assert.equal(posts.at(-1).body.cs_goal,8);
  await page.locator('summary').filter({hasText:'Optional Riot enrichment'}).click();await clickPost('#lsRetryRiot');assert.equal(posts.at(-1).path,'/api/league-stats/enrichment');
  assert.match(await page.locator('#lsCoverage').innerText(),/10 verified official records/);
  fs.mkdirSync(output,{recursive:true});await page.locator('#lsForm').screenshot({path:path.join(output,'recent-form.png')});
  fs.mkdirSync(output,{recursive:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(output,'dashboard.png'),fullPage:true});
  await page.setViewportSize({width:390,height:900});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile page must not overflow');
  await page.goto('http://stats.test/league-stats/overlay.html');await page.waitForFunction(()=>document.getElementById('champion')?.textContent==='Jinx');
  assert.equal(await page.locator('#kda').innerText(),'6 / 2 / 5');
  assert.match(await page.locator('#misses').innerText(),/Cannon 1/);
  await page.setViewportSize({width:520,height:190});await page.screenshot({path:path.join(output,'overlay.png')});
  state.spotlight={title:'Farming',text:'2,291 CS · 7.42 / min',requested_by:'<img src=x onerror=alert(1)>',scope:'Current saved session',expires_at:Date.now()/1000+20};
  await page.waitForFunction(()=>document.getElementById('spotlight')?.textContent.includes('2,291'));
  assert.equal(await page.locator('#spotlight img').count(),0);
  await page.screenshot({path:path.join(output,'viewer-spotlight.png')});
  state.spotlight=null;await page.waitForFunction(()=>document.getElementById('spotlight')?.hidden);
  await page.goto('http://stats.test/league-stats/overlay.html?view=rank');await page.waitForFunction(()=>document.getElementById('spotlight')?.textContent.includes('GOLD I'));
  assert.match(await page.locator('#spotlight').innerText(),/25 observed ladder movement/);
  state.live_progress.available=false;
  await page.goto('http://stats.test/league-stats/overlay.html?view=goal');await page.waitForFunction(()=>document.getElementById('spotlight')?.textContent.includes('8 / 12'));
  await page.goto('http://stats.test/league-stats/overlay.html?view=recap');await page.waitForFunction(()=>document.getElementById('spotlight')?.textContent.includes('Jinx'));
  assert.match(await page.locator('#spotlight').innerText(),/7.5 CS\/min/);
  await page.goto('http://stats.test/league-stats/overlay.html?view=session&theme=gold');
  await page.waitForFunction(()=>document.getElementById('spotText')?.textContent.includes('8 W'));
  assert.equal(await page.locator('html').getAttribute('data-theme'),'gold');
  assert.doesNotMatch(await page.locator('#spotTitle').innerText(),/undefined|requested by/);
  assert(await page.evaluate(()=>document.querySelector('main').getBoundingClientRect().height===190));
  await page.screenshot({path:path.join(output,'session-overlay.png')});
  state.live_progress.available=true;
  await page.goto('http://stats.test/league-stats/overlay.html?view=goal&theme=violet');
  await page.waitForFunction(()=>document.getElementById('spotText')?.textContent.includes('On target'));
  assert.equal(await page.locator('#spotBar').evaluate(e=>e.value),100);
  await page.screenshot({path:path.join(output,'live-goal-overlay.png')});
  const models=await page.evaluate(async()=>{const {chooseView}=await import('/league-stats/model.js');return [chooseView(new URLSearchParams('view=rotate&cycle=8'),{summary:{},current:{connected:true}},0),chooseView(new URLSearchParams('view=rotate&cycle=8'),{summary:{},current:{connected:true}},8000),chooseView(new URLSearchParams('view=rotate'),{summary:{}},12000)];});
  assert.deepEqual(models,['live','session','session']);
  state.current=null;state.recap=null;state.live_progress={available:false,target:7};
  await page.goto('http://stats.test/league-stats/overlay.html?theme=garbage');
  await page.waitForFunction(()=>document.getElementById('state')?.textContent==='SESSION');
  assert.match(await page.locator('#misses').innerText(),/Cannon —/);assert.doesNotMatch(await page.locator('#misses').innerText(),/Cannon 0/);
  assert.equal(await page.locator('html').getAttribute('data-theme'),'teal');
  assert.deepEqual(errors,[]);
  console.log('League Stats browser: chat previews and drafts, dashboard, helpers, sessions, reviews, filters, mobile and overlay passed');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
