// Actual production entry point + real loopback routes, never the live Hub.
const {chromium}=require('playwright'),{spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=process.env.BORDER_REVIEW_ARTIFACT_DIR||path.join(root,'tmp_obs_debug');fs.mkdirSync(out,{recursive:true});
const fixture=spawn('py',['-3.11','-u','tools/celebration_fixture.py'],{cwd:root,stdio:['pipe','pipe','pipe']});fixture.stderr.on('data',d=>process.stderr.write(d));
const endpoint=new Promise((resolve,reject)=>{let buffer='';const timeout=setTimeout(()=>reject(Error('Fixture startup timeout')),10000);fixture.stdout.on('data',d=>{buffer+=d;const line=buffer.split(/\r?\n/).find(l=>l.startsWith('{'));if(line){clearTimeout(timeout);resolve('http://127.0.0.1:'+JSON.parse(line).port);}});fixture.on('exit',c=>{clearTimeout(timeout);reject(Error('Fixture exited '+c));});});
function fakeAudio(){window.audioLog=[];window.Audio=class{constructor(src){this.src=src;this.volume=1;this.currentTime=0;audioLog.push(this);}play(){this.played=true;return Promise.resolve();}pause(){this.paused=true;}};}
(async()=>{let browser;try{const base=await endpoint;browser=await chromium.launch({headless:true,channel:'chrome',args:['--mute-audio']});const page=await browser.newPage({viewport:{width:1920,height:1080}});await page.addInitScript(fakeAudio);const errors=[];page.on('pageerror',e=>errors.push(e.message));const missing=[];page.on('response',r=>{if(r.status()>=400)missing.push(r.url());});await page.goto(base+'/overlay?preview');await page.evaluate(async()=>await (await import('/supporter_show.js')).artReady);
 const start=async(kind,theme,elapsed=1.45,details={tier:'2000',months:12,message:'You make every stream a little brighter.',renewal:true})=>{await page.evaluate(({kind,theme,elapsed,details})=>window.postMessage({type:'preview',item:{id:kind+theme,kind,theme,name:'Friend <3 & Company',count:5,elapsed,duration:kind==='follow'?2.2:3.8,details},settings:{volume:.22,muted:true,custom:{}}},location.origin),{kind,theme,elapsed,details});await page.waitForTimeout(90);};
 const fingerprints=[];let maxDrawMs=0,subPixels=0,followPixels=0;
 // Fixed-clock evidence for the approved follower artwork and layout.
 const followerBaseline=await page.evaluate(async()=>{const {SupporterShow}=await import('/supporter_show.js');const result={};for(const theme of ['crab','dragon','cat','frog']){const s=new SupporterShow(document.querySelector('#stage'));s.start({kind:'follow',theme,name:'Approved follower',duration:2.2},{custom:{}});const frames=[];for(const t of [.3,.8,1.4,1.95]){s.update(t);frames.push(s.canvas.toDataURL());}const panel=document.querySelector('#supporterPanel'),name=document.querySelector('#supporterName');result[theme]={frames,panel:[panel.offsetLeft,panel.offsetTop,panel.offsetWidth],font:getComputedStyle(name).fontSize};s.stop();}return result;});
 const followerHashes=Object.fromEntries(Object.entries(followerBaseline).map(([key,value])=>[key,{...value,frames:value.frames.map(frame=>crypto.createHash('sha256').update(frame).digest('hex'))}]));
 const baselinePath=path.join(out,'approved-follower-fingerprints.json');
 if(process.argv.includes('--capture-followers'))fs.writeFileSync(baselinePath,JSON.stringify(followerHashes,null,2));
 else if(fs.existsSync(baselinePath))assert.deepEqual(followerHashes,JSON.parse(fs.readFileSync(baselinePath)),'Approved follower drawings, timing and layout must be unchanged');
 for(const theme of ['crab','dragon','cat','frog']){
  await start('subscribe',theme);assert.equal(await page.locator('#supporterName').textContent(),'Friend <3 & Company');assert((await page.locator('#supporterDetail').textContent()).includes('12 MONTHS'));assert((await page.locator('#supporterDetail').textContent()).includes('TIER II'));assert.equal(await page.locator('#supporterMessage').textContent(),'You make every stream a little brighter.');assert.equal(await page.locator('.mascot').count(),0);await page.screenshot({path:path.join(out,'subscriber-'+theme+'.png')});
  const check=await page.evaluate(async()=>{const {SupporterShow}=await import('/supporter_show.js');const s=new SupporterShow(document.querySelector('#stage'));s.start({theme:document.querySelector('#stage').dataset.spirit==='bear'?'crab':document.querySelector('#stage').dataset.spirit==='turtle'?'dragon':document.querySelector('#stage').dataset.spirit==='ram'?'cat':'frog',kind:'subscribe',name:'Different name',duration:3.8}, {custom:{}});s.update(1.45);const data=s.c.getImageData(0,0,1920,1080).data;let painted=0;for(let i=3;i<data.length;i+=4)if(data[i])painted++;const frame=s.canvas.toDataURL();s.update(2.35);const evolved=s.canvas.toDataURL()!==frame;const started=performance.now();for(let i=0;i<90;i++)s.update(.8+i/50);const drawMs=(performance.now()-started)/90;s.update(3.8);const ended=s.c.getImageData(0,0,1920,1080).data.some((v,i)=>i%4===3&&v);s.stop();return {painted,frame,evolved,drawMs,ended};});
  assert(check.painted>10000&&check.painted<250000,'Celebration should occupy the top strip and visible edge decorations');assert(check.evolved);assert(!check.ended);assert(check.drawMs<30);maxDrawMs=Math.max(maxDrawMs,check.drawMs);subPixels+=check.painted;fingerprints.push(crypto.createHash('sha256').update(check.frame).digest('hex'));
  const safety=await page.evaluate(async theme=>{const {SupporterShow}=await import('/supporter_show.js');const s=new SupporterShow(document.querySelector('#stage'));s.start({kind:'subscribe',theme,name:'Top-center supporter',duration:3.8},{custom:{}});let centerClear=true,edgeMax=0;for(const t of [0,.2,.55,.85,1.1,1.45,2,2.8,3.25,3.65,3.8]){s.update(t);centerClear&&=!s.c.getImageData(240,170,1440,670).data.some((v,i)=>i%4===3&&v);const edge=s.c.getImageData(0,180,1920,650).data;for(let i=3;i<edge.length;i+=4)edgeMax=Math.max(edgeMax,edge[i]);}const panel=s.layer.querySelector('#supporterPanel').getBoundingClientRect(),background=getComputedStyle(s.layer.querySelector('#supporterPanel')).backgroundColor;s.stop();return {centerClear,edgeMax,panelBottom:panel.bottom,background};},theme);
  assert(safety.centerClear,'Gameplay center stays fully transparent throughout the complete show');assert(safety.edgeMax>150,'Edge light heads must be readable without a blanket opacity ceiling');assert(safety.panelBottom<=170);assert.equal(safety.background,'rgba(0, 0, 0, 0)');
  // Re-start through the actual entry point after the direct rendering inspection.
  await start('follow',theme,.7,{});const follow=await page.evaluate(()=>{const c=document.querySelector('#supporterCanvas').getContext('2d'),p=c.getImageData(0,0,1920,1080).data;let n=0;for(let i=3;i<p.length;i+=4)if(p[i])n++;return {n,outside:c.getImageData(800,0,1120,1080).data.some((v,i)=>i%4===3&&v)};});assert(follow.n>500&&follow.n<40000);assert(!follow.outside);followPixels+=follow.n;await page.screenshot({path:path.join(out,'follower-'+theme+'.png')});
 }
 assert.equal(new Set(fingerprints).size,4);assert(subPixels>followPixels);
 // Live copy uses observed context; every spirit/event has its own vocabulary.
 const wording=await page.evaluate(async()=>{const {copyFor}=await import('/supporter_show.js');const result=[];for(const theme of ['crab','dragon','cat','frog'])for(const kind of ['new','returning','gift']){const samples=new Set();for(let i=0;i<30;i++){const item={id:'wording-'+i,name:'RuntimeViewer',theme,kind:kind==='gift'?'gift':'subscribe',count:1,details:kind==='returning'?{renewal:true,months:7}:{}};const copy=copyFor(item);samples.add(copy.kicker+'|'+copy.message);if(copy.message.match(/\{\w+\}/)||copy.message.includes('1 new seats')||copy.message.includes('1 gifted subs'))throw Error('Unresolved placeholder or plural');if(kind==='new'&&/MONTHS|TIER/.test(copy.detail))throw Error('Invented subscription facts');if(JSON.stringify(copy)!==JSON.stringify(copyFor(item)))throw Error('Different overlays must agree on event wording');}result.push({theme,kind,samples:[...samples]});}const milestone=copyFor({id:'anniversary',name:'Live',kind:'subscribe',theme:'dragon',details:{renewal:true,months:24}});const shared='<img src=x onerror=alert(1)> & thank you';const custom=copyFor({kind:'subscribe',theme:'crab',details:{message:shared}});return {result,milestone,shared,custom};});
 assert(wording.result.every(x=>x.samples.length===3),'Three authored variants for every spirit and event');assert.equal(new Set(wording.result.flatMap(x=>x.samples)).size,36);assert(wording.milestone.message.includes('24 months'));assert.equal(wording.custom.message,wording.shared);
 await page.evaluate(()=>window.postMessage({type:'stop'},location.origin));await page.waitForTimeout(550);
 // Unknown future usernames, including long and international names, fit safely.
 for(const width of [1920,960]){await page.setViewportSize({width,height:width*9/16});for(const name of ['W'.repeat(48),'月光の旅人_Étoile_🌙','<img src=x onerror=alert(1)> & crew']){
  const fitted=await page.evaluate(async({name})=>{const {SupporterShow}=await import('/supporter_show.js');const s=new SupporterShow(document.querySelector('#stage'));s.start({id:name,kind:'subscribe',theme:'frog',name,duration:3.8,details:{}},{custom:{}});s.update(.6);const n=s.layer.querySelector('#supporterName'),partial=n.style.clipPath;s.update(1.2);const panel=s.panel.getBoundingClientRect(),msg=s.layer.querySelector('#supporterMessage').getBoundingClientRect();const result={name:n.textContent,noMarkup:n.children.length===0,partial,revealed:n.style.clipPath,overflow:n.scrollWidth>n.clientWidth+1||n.scrollHeight>n.clientHeight+1,bottom:panel.bottom,messageFits:msg.bottom<=panel.bottom+1};s.stop();return result;},{name});
  assert.equal(fitted.name,name);assert(fitted.noMarkup);assert(!fitted.overflow,'Runtime username must fit without truncation');assert.notEqual(fitted.partial,fitted.revealed);assert.equal(fitted.revealed,'inset(0px 0% 0px 0px)');assert(fitted.bottom<=width*168/1920+2);assert(fitted.messageFits,'The themed message must fit inside the top strip');
 }}await page.setViewportSize({width:1920,height:1080});
 await start('gift','frog',1.4,{tier:'3000'});assert((await page.locator('#supporterDetail').textContent()).includes('5 GIFTED SUBS'));
 await start('subscribe','cat',1.4,{});assert(!(await page.locator('#supporterDetail').textContent()).match(/TIER|MONTHS/),'Never invent absent facts');
 await page.emulateMedia({reducedMotion:'reduce'});await start('subscribe','dragon',1.4);assert.equal(await page.locator('#supporterPanel').evaluate(n=>getComputedStyle(n).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});
 // Custom asset preference and audio seeking, replacement, stop, natural expiry.
 await page.evaluate(()=>window.postMessage({type:'preview',item:{id:'custom',kind:'subscribe',theme:'crab',name:'Personal',count:1,elapsed:1,duration:3.8},settings:{volume:.4,muted:false,custom:{crab:{visual:'minions-dance.mp4',audio:'cat.wav'}}}},location.origin));await page.waitForTimeout(130);assert.equal(await page.locator('#supporterCustom').count(),1);assert(await page.evaluate(()=>audioLog.at(-1).src.endsWith('/cat.wav')));assert((await page.evaluate(()=>audioLog.at(-1).volume))<=.4);
 await page.evaluate(()=>window.postMessage({type:'stop'},location.origin));await page.waitForTimeout(550);assert.equal(await page.locator('#supporterLayer').count(),0);assert.equal(await page.locator('video').count(),0);assert(await page.evaluate(()=>audioLog.every(a=>a.paused)));
 await start('follow','crab',2.05,{});await page.waitForTimeout(350);assert.equal(await page.locator('#supporterLayer').count(),0);
 // Control preview must expose the same durations/details and never consume live events.
 await page.goto(base+'/');await page.locator('#kind').selectOption('subscribe');await page.locator('#themes button').nth(2).click();await page.locator('#months').fill('18');await page.locator('#tier').selectOption('3000');await page.locator('#subMessage').fill('The best crew.');await page.locator('#previewButton').click();const previewFrame=page.frameLocator('#preview');await previewFrame.locator('#supporterName').waitFor();assert((await previewFrame.locator('#supporterDetail').textContent()).includes('18 MONTHS'));assert.equal((await (await fetch(base+'/api/state')).json()).queue,0);
 await page.close();
 // Four simultaneous subscription previews, then four lightweight followers.
 const context=await browser.newContext({viewport:{width:1920,height:1080},recordVideo:{dir:out,size:{width:1920,height:1080}}});const review=await context.newPage();await review.addInitScript(fakeAudio);review.on('pageerror',e=>errors.push(e.message));await review.goto(base+'/overlay?preview');await review.evaluate(base=>{document.body.innerHTML='';document.body.style.cssText='background:#111b28;display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:12px';for(const [i,theme]of ['crab','dragon','cat','frog'].entries()){const p=document.createElement('div');p.style.cssText='position:relative;background:radial-gradient(ellipse at 50% 50%,#273640,#101b28);border:1px solid #344654';const label=document.createElement('span');label.textContent=['STORMCLAW','VERDANT AEGIS','SUNDERING GOLD','CINDER ASCENSION'][i];label.style.cssText='position:absolute;bottom:12%;width:100%;text-align:center;color:#869ca7;font:16px Arial;letter-spacing:4px';p.append(label);const f=document.createElement('iframe');f.dataset.theme=theme;f.src=base+'/overlay?preview';f.style.cssText='position:relative;width:100%;height:100%;border:0';p.append(f);document.body.append(p);}},base);await review.waitForTimeout(900);
 const play=async kind=>review.evaluate(kind=>document.querySelectorAll('iframe').forEach((f,i)=>f.contentWindow.postMessage({type:'preview',item:{id:kind+f.dataset.theme,kind:i===2&&kind!=='follow'?'gift':kind,theme:f.dataset.theme,name:['PixelPaws','MoonlitMoss','GoldenGoose','EmberWanderer'][i],count:i===2?5:1,elapsed:0,duration:kind==='follow'?2.2:3.8,details:kind==='follow'||i===2?{}:i===1?{tier:'2000',months:24,renewal:true}:i===3?{months:7,renewal:true}:{tier:'1000'}},settings:{volume:.22,muted:true,custom:{}}},location.origin)),kind);
 await play('subscribe');await review.waitForTimeout(1600);await review.screenshot({path:path.join(out,'subscriber-spirits.png')});await review.waitForTimeout(2500);await play('follow');await review.waitForTimeout(700);await review.screenshot({path:path.join(out,'follower-spirits.png')});await review.waitForTimeout(2200);const video=review.video();await context.close();await video.saveAs(path.join(out,'supporter-spirits-motion.webm'));
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log(JSON.stringify({passed:true,subscriberVariants:4,followerVariants:4,maxFrameMs:Math.round(maxDrawMs*100)/100,subPixels,followPixels,preview:path.join(out,'supporter-spirits-motion.webm')}));
 }finally{if(browser)await browser.close();fixture.stdin.end();}})().catch(e=>{console.error(e);process.exitCode=1;});
