// Browser regression checks use fixture APIs and never change OBS or personal data.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),{PNG}=require('pngjs');
const output=path.resolve(__dirname,'../output/replay-studio-v3');fs.mkdirSync(output,{recursive:true});
const base='http://replay.test',app=path.resolve(__dirname,'../hub_ui/app');
async function staticFixture(page){
 await page.route(base+'/**',route=>{
  const url=new URL(route.request().url());
  if(url.pathname.startsWith('/api/'))return route.fulfill({json:{}});
  const file=path.resolve(app,url.pathname==='/'?'index.html':'.'+decodeURIComponent(url.pathname));
  if(!file.startsWith(app+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return route.fulfill({status:404});
  const type={'.js':'application/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp','.woff2':'font/woff2'}[path.extname(file)]||'application/octet-stream';
  return route.fulfill({body:fs.readFileSync(file),contentType:type});
 });
}
const prefs={replay:{companion:'live',camera:true,transition:'fade',clip_transition:'sweep'},showcase:{companion:'off',camera:true,transition:'current',clip_transition:'iris'},motion:true};
let fixture={active:true,kind:'replay',mode:'replay',view:'live',camera:true,camera_online:true,live_online:true,phase:'playing',title:'Baron steal',context:'Game 1061 · Sep 18 · 08:45',index:1,total:3,cursor_ms:12500,duration_ms:38000,next_title:'Teamfight · 22:37',revision:1,motion:true,settings:prefs,clip_transition:'sweep'};
const alpha=(png,x,y)=>png.data[(y*png.width+x)*4+3];
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 try{
  const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[],acks=[],writes=[];
  page.on('pageerror',e=>errors.push(e.message));
  await staticFixture(page);
  await page.route('**/api/projects/instant_replay/stage',route=>route.fulfill({json:fixture}));
  await page.route('**/api/projects/instant_replay/stage-cue',route=>{acks.push(route.request().postDataJSON());return route.fulfill({json:{accepted:true}});});
  await page.goto(base+'/replay-stage.html?layer=motion');
  await page.locator('#stage[data-ready=true]').waitFor();
  assert.equal(await page.locator('.world').isVisible(),false);
  assert.equal(await page.locator('.loading').isVisible(),false);
  assert.deepEqual(await page.locator('.frame-effect').boundingBox(),{x:56,y:182,width:1376,height:774});
  assert.equal(await page.locator('#clipTitle').textContent(),'Baron steal');
  assert.equal(await page.locator('#chapter').textContent(),'CLIP 1 / 3');
  assert.doesNotMatch(await page.locator('body').textContent(),/THE MOMENT|ONCE MORE|A SECOND LOOK|CUEING/);
  fixture={...fixture,camera_online:false};await page.locator('#cameraStatus').waitFor({state:'visible'});
  assert.deepEqual(await page.locator('#cameraStatus').boundingBox(),{x:1480,y:466,width:384,height:216});
  fixture={...fixture,camera_online:true,paused:true,cursor_ms:15000};
  await page.getByText('PAUSED  0:15 / 0:38',{exact:true}).waitFor();
  await page.locator('#cameraStatus').waitFor({state:'hidden'});
  for(const style of ['sweep','iris','fade','cut']){
   fixture={...fixture,paused:false,handoff:true,phase:'covering',clip_transition:style,revision:fixture.revision+1,index:2,title:'Teamfight · 22:37'};
   await page.waitForFunction(({style,revision})=>{const e=document.getElementById('handoff');return e.dataset.style===style&&e.dataset.closed==='true'&&e.dataset.revision===String(revision);},{style,revision:fixture.revision});
   await page.waitForFunction(()=>document.getElementById('handoff').dataset.acknowledged==='true');
   const shot=await page.screenshot({path:path.join(output,`transition-${style}.png`),omitBackground:true});
   const png=PNG.sync.read(shot);
   for(const [x,y] of [[59,185],[1429,185],[59,953],[1429,953],[744,570]])assert.equal(alpha(png,x,y),255,`${style} must fully cover every part of the clip before swapping`);
   assert.equal(alpha(png,1500,220),0,'Transition must leave live screen visible');
   assert.equal(alpha(png,1500,500),0,'Transition must leave face cam visible');
   const revision=fixture.revision;
   assert.equal(acks.filter(a=>a.event==='covered'&&a.revision===revision).length,1);
   fixture={...fixture,phase:'revealing'};
   await page.locator('#handoff').waitFor({state:'hidden'});
   assert.equal(acks.filter(a=>a.event==='revealed'&&a.revision===revision).length,1);
   fixture={...fixture,phase:'playing'};
  }
  fixture={...fixture,handoff:false,phase:'loading',revision:fixture.revision+1,title:'<img src=x onerror="window.injected=true">'};
  await page.locator('.loading').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>!!window.injected),false);
  fixture={...fixture,phase:'playing',mode:'showcase',kind:'highlights',view:'off',camera:false,paused:false,next_title:''};
  await page.waitForFunction(()=>!document.body.classList.contains('side'));
  assert.deepEqual(await page.locator('.frame-effect').boundingBox(),{x:184,y:144,width:1552,height:873});
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('.frame-effect').evaluate(el=>getComputedStyle(el,':before').animationName),'none');
  fixture={...fixture,handoff:true,phase:'covering',clip_transition:'iris',revision:fixture.revision+1};
  await page.waitForFunction(()=>document.getElementById('handoff').dataset.closed==='true');
  assert.equal(await page.locator('#handoff').evaluate(e=>Math.max(...e.getAnimations({subtree:true}).map(a=>Number(a.effect.getTiming().duration)))),0);
  await page.goto(base+'/replay-stage.html?preview=replay');await page.locator('#stage[data-ready=true]').waitFor();
  await page.screenshot({path:path.join(output,'quick-replay-preview.png')});
  assert.deepEqual(await page.locator('.camera-window').boundingBox(),{x:1480,y:466,width:384,height:216});
  await page.goto(base+'/replay-stage.html?preview=showcase');await page.locator('#stage[data-ready=true]').waitFor();
  await page.screenshot({path:path.join(output,'showcase-preview.png')});
  assert.deepEqual(await page.locator('.camera-window').boundingBox(),{x:1480,y:182,width:384,height:216});
  assert.equal(await page.locator('.recording-badge').isVisible(),true);
  await page.close();
  fixture={...fixture,active:false,handoff:false,title:'',phase:'idle',view:'off'};
  const ui=await browser.newPage({viewport:{width:1500,height:1050}});ui.on('pageerror',e=>errors.push(e.message));let stageReads=0;
  await staticFixture(ui);
  await ui.route('**/api/status',route=>route.fulfill({json:{projects:[{name:'instant_replay',is_active:false,current_activity:null,actions:[]}]}}));
  await ui.route('**/api/projects/instant_replay/stage',route=>{stageReads++;return route.fulfill({json:fixture});});
  const catalog=[{id:'keeper',path:'C:/fixture/keeper.mkv',name:'keeper.mkv',title:'Baron steal',purpose:'highlight',scope:'saved',saved_at:1,size_bytes:1000},{id:'small',path:'C:/fixture/small.mkv',name:'small.mkv',title:'Funny miss',purpose:'replay_only',scope:'saved',saved_at:2,size_bytes:1000}];
  let revision=0,holdCatalog=false,releaseCatalog,catalogReady=true;
  await ui.route('**/api/projects/instant_replay/clips',async route=>{
    if(holdCatalog)await new Promise(resolve=>{releaseCatalog=resolve;});
    return route.fulfill({json:{clips:catalog,groups:[],revision,ready:catalogReady}});
  });
  await ui.route('**/api/projects/instant_replay/capture',route=>{writes.push(route.request().postDataJSON());return route.fulfill({status:202,json:{ok:true}});});
  await ui.route('**/api/projects/instant_replay/library',route=>{
    const body=route.request().postDataJSON();writes.push(body);
    for(const c of catalog)if(body.paths?.includes(c.path))c.purpose=body.purpose;
    if(body.paths?.includes(fixture.clip_path))fixture={...fixture,purpose:body.purpose};
    revision++;
    return route.fulfill({json:{clips:Object.fromEntries(catalog.map(c=>[c.id,c])),groups:[],revision}});
  });
  await ui.route('**/api/projects/instant_replay/presentation',route=>{
   const data=route.request().postDataJSON();writes.push(data);
   for(const key of Object.keys(data))prefs[key]=typeof data[key]==='object'?{...prefs[key],...data[key]}:data[key];
   return route.fulfill({json:{...fixture,settings:prefs,motion:prefs.motion}});
  });
  await ui.route('**/api/project-actions/instant_replay/*',route=>{writes.push(route.request().url().split('/').at(-1));return route.fulfill({json:{ok:true}});});
  await ui.goto(base+'/#projects/instant_replay');await ui.locator('#irReplay:not([disabled])').waitFor();
  assert.equal(await ui.locator('#irScope').inputValue(),'highlight');
  assert.equal(await ui.locator('#irClips .ir-clip').count(),1);
  await ui.locator('#irQuickSeconds').selectOption('30');await ui.locator('#irQuickReplay').click();
  assert.deepEqual(writes.pop(),{seconds:30});
  await ui.locator('#irScope').selectOption('replay_only');
  await ui.locator('#irClips [data-id=small] input').check();
  await ui.locator('#irMakeHighlight').click();
  await ui.waitForFunction(()=>document.querySelectorAll('#irClips .ir-clip').length===0);
  assert.equal(catalog[1].purpose,'highlight');assert.equal(writes.pop().action,'purpose');
  await ui.locator('#irScope').selectOption('highlight');
  assert.equal(await ui.locator('#irClips .ir-clip').count(),2);
  await ui.locator('[data-mode=showcase][data-pref=camera]').uncheck();
  await ui.waitForFunction(()=>!document.querySelector('[data-mode=showcase][data-pref=camera]').disabled);
  assert.deepEqual(writes[0],{showcase:{camera:false}});
  await ui.locator('[data-mode=replay][data-pref=clip_transition]').selectOption('iris');
  await ui.waitForFunction(()=>!document.querySelector('[data-mode=replay][data-pref=clip_transition]').disabled);
  assert.deepEqual(writes[1],{replay:{clip_transition:'iris'}});
  const beforePreview=writes.length;
  await ui.locator('[data-preview-transition=replay]').click();
  await ui.frameLocator('iframe[src*="preview=replay"]').locator('#handoff[data-style=iris]').waitFor({state:'visible'});
  assert.equal(writes.length,beforePreview,'Transition preview must stay off stream');
  await ui.locator('#irSaveReplay').click();await ui.locator('#irLatest').click();
  assert.equal(writes.includes('save_replay'),true);assert.equal(writes.includes('play_showcase'),true);
  catalog[1].purpose='replay_only';fixture={...fixture,active:true,phase:'playing',mode:'replay',clip_path:catalog[1].path,purpose:'replay_only',title:'Funny miss'};
  await ui.locator('#irKeepCurrent').waitFor({state:'visible'});
  holdCatalog=true;await ui.locator('#irKeepCurrent').click();
  await ui.waitForFunction(()=>document.querySelector('#irKeepCurrent').disabled);
  while(!releaseCatalog)await new Promise(resolve=>setTimeout(resolve,10));
  fixture={...fixture,clip_path:catalog[0].path,purpose:'highlight',title:'Baron steal'};
  holdCatalog=false;releaseCatalog();
  await ui.waitForFunction(()=>document.querySelector('#irKeepCurrent').hidden);
  await ui.waitForFunction(()=>!document.querySelector('#irKeepCurrent').disabled);
  assert.deepEqual(writes.at(-1),{action:'purpose',paths:[catalog[1].path],purpose:'highlight',revision:1},'Keep must save the clicked clip even if playback advances during its catalog read');
  assert.equal(catalog[1].purpose,'highlight');
  fixture={...fixture,active:false,phase:'idle',clip_path:''};
  await ui.screenshot({path:path.join(output,'hub-studio.png'),fullPage:true});
  catalogReady=false;await ui.locator('#irRefresh').click();
  await ui.waitForFunction(()=>document.querySelector('#irQuickReplay').disabled);
  await ui.waitForTimeout(4300);
  assert.equal(await ui.locator('#irQuickReplay').isDisabled(),true,'Stage polling must keep quick capture disabled while playback is offline');
  await ui.setViewportSize({width:760,height:1000});assert.equal(await ui.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await ui.evaluate(()=>{location.hash='#dashboard';});await ui.waitForTimeout(200);const before=stageReads;
  await ui.waitForTimeout(4300);assert.equal(stageReads,before,'Studio polling must stop after navigating away');
  assert.deepEqual(errors,[]);console.log('Replay studio v3: copy, camera/live layout, opaque sweep/iris/fade/cut, cue/reveal handshake, reduced motion, settings, off-stream preview, mobile and cleanup passed');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
