// Isolated Chromium proof + review artifacts. Never enqueues on the live Hub.
const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),web=path.join(root,'mini projects/twitch_celebrations'),out=process.env.BORDER_REVIEW_ARTIFACT_DIR||path.join(root,'tmp_obs_debug');
const types={'.js':'text/javascript','.css':'text/css','.html':'text/html','.wav':'audio/wav','.mp3':'audio/mpeg'};
let live=null,online=true;
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/api/overlay'){if(!online){res.writeHead(503);res.end();return;}res.setHeader('Content-Type','application/json');res.end(JSON.stringify({active:live,settings:{volume:.22,muted:true,custom:{}}}));return;}
 const file=['/subtle.js','/optics.js'].includes(url.pathname)?path.join(root,'lib/browser_effects/web',url.pathname==='/optics.js'?'production.js':'subtle.js'):path.join(web,url.pathname==='/overlay'?'overlay.html':url.pathname.slice(1));if(!file.startsWith(web+path.sep)&&!['/subtle.js','/optics.js'].includes(url.pathname)){res.writeHead(403);res.end();return;}try{res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
const fakeAudio=()=>{window.audioLog=[];window.Audio=class{constructor(src){this.src=src;this.volume=1;this.currentTime=0;window.audioLog.push(this);}play(){this.played=true;return Promise.resolve();}pause(){this.paused=true;}};};
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let browser;try{
 browser=await chromium.launch({headless:true,channel:'chrome',args:['--mute-audio']});const page=await browser.newPage({viewport:{width:1920,height:1080}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(fakeAudio);
 // Exercise browser-clock behavior at the feature's configured OBS frame rate.
 if(process.env.RAID_TEST_FPS)await page.addInitScript(fps=>{
  window.requestAnimationFrame=callback=>setTimeout(()=>callback(performance.now()),1000/fps);
  window.cancelAnimationFrame=clearTimeout;
 },Number(process.env.RAID_TEST_FPS));
 await page.goto(base+'/overlay?preview');await page.waitForTimeout(150);
 const hashes=[];let maxMs=0;
 for(const theme of ['crab','dragon','cat','frog']){
  const result=await page.evaluate(async theme=>{const {RaidArt}=await import('/raid_art.js');const canvas=document.createElement('canvas');canvas.width=1920;canvas.height=1080;const art=new RaidArt(canvas);await art.ready;art.start({id:'test',theme});const c=art.c;const checks=[];const start=performance.now();for(const t of [0,.8,1.8,3.5,5.5,7.8,8]){art.draw(t);const data=c.getImageData(0,0,1920,1080).data;let count=0,max=0;for(let i=3;i<data.length;i+=4){if(data[i])count++;max=Math.max(max,data[i]);}checks.push({t,count,max,center:c.getImageData(240,170,1440,670).data.some((v,i)=>i%4===3&&v)});}const ms=(performance.now()-start)/7;art.draw(3.5);const fingerprint=canvas.toDataURL();art.draw(4,true);const reducedA=canvas.toDataURL();art.draw(5,true);return {checks,ms,fingerprint,reducedStable:canvas.toDataURL()===reducedA};},theme);
  const drawMs=await page.evaluate(async theme=>{const {RaidArt}=await import('/raid_art.js');const cv=document.createElement('canvas');cv.width=1920;cv.height=1080;const a=new RaidArt(cv);a.start({theme,id:'timing'});a.draw(2);const start=performance.now();for(let i=0;i<90;i++)a.draw(2+i/30);return (performance.now()-start)/90;},theme);
  maxMs=Math.max(maxMs,drawMs);assert(drawMs<30,'Raid art must fit a 30fps frame budget');hashes.push(crypto.createHash('sha256').update(result.fingerprint).digest('hex'));assert(result.checks.every(x=>!x.center&&x.max<=255));assert.equal(result.checks[0].count,0);assert.equal(result.checks.at(-1).count,0);assert(result.checks[3].count>1000);assert(result.checks.some(x=>x.max>204),"Raid foreground must not receive a blanket opacity ceiling");assert(result.reducedStable);
  await page.evaluate(theme=>window.postMessage({type:'preview',item:{id:theme,kind:'raid',theme,name:'Friends <3 & Company',count:123,elapsed:3.5,duration:8},settings:{volume:.22,muted:true,custom:{}}},location.origin),theme);await page.waitForTimeout(120);assert.equal(await page.locator('#name').textContent(),'Friends <3 & Company');assert.equal(await page.locator('.mascot').count(),0);assert.equal(await page.locator('video').count(),0);await page.screenshot({path:path.join(out,'raid-'+theme+'.png')});
 }
 assert.equal(new Set(hashes).size,4,'Worlds must have different actual artwork');
 // No stale cues when opening halfway through; current-volume changes apply.
 await page.evaluate(()=>{window.audioLog=[];window.postMessage({type:'preview',item:{id:'late',kind:'raid',theme:'cat',name:'Late',count:12,elapsed:5.8,duration:8},settings:{volume:.4,muted:false,custom:{}}},location.origin);});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>audioLog.length),1);
 await page.evaluate(()=>window.postMessage({type:'stop'},location.origin));await page.waitForTimeout(120);assert.equal(await page.locator('#raidArt').count(),0);assert(await page.evaluate(()=>audioLog.every(a=>a.paused)));
 // Real polling, not preview: elapsed server time, disconnect and idle cleanup.
 live={id:'transport',kind:'raid',theme:'dragon',name:'Crew',count:42,elapsed:2,duration:8};await page.goto(base+'/overlay');await page.locator('#raidArt').waitFor({timeout:3000});assert.equal(await page.locator('#raidArt').count(),1);online=false;await page.waitForTimeout(2900);assert.equal(await page.locator('#raidArt').count(),0);online=true;live=null;
 await page.close();
 const context=await browser.newContext({viewport:{width:1920,height:1080},recordVideo:{dir:out,size:{width:1920,height:1080}}});const preview=await context.newPage();await preview.addInitScript(fakeAudio);preview.on('pageerror',e=>errors.push(e.message));
 await preview.goto(base+'/overlay?preview');await preview.evaluate(base=>{document.body.innerHTML='';document.body.style.cssText='background:#121e25;display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:12px';for(const theme of ['crab','dragon','cat','frog']){const panel=document.createElement('div');panel.style.cssText='position:relative;background:radial-gradient(ellipse at 50% 50%,#25363b,#111c25);border:1px solid #31434c';const label=document.createElement('span');label.textContent=({crab:'HARBOR FLOTILLA',dragon:'LANTERN FLIGHT',cat:'COSMIC EXPRESS',frog:'LILY-PAD CARNIVAL'})[theme];label.style.cssText='position:absolute;top:45%;width:100%;text-align:center;color:#8397a0;font:18px Arial;letter-spacing:5px';panel.append(label);const frame=document.createElement('iframe');frame.dataset.theme=theme;frame.src=base+'/overlay?preview';frame.style.cssText='width:100%;height:100%;border:0;position:relative';panel.append(frame);document.body.append(panel);}},base);
 await preview.waitForTimeout(500);await preview.evaluate(()=>document.querySelectorAll('iframe').forEach(f=>f.contentWindow.postMessage({type:'preview',item:{id:f.dataset.theme,kind:'raid',theme:f.dataset.theme,name:'Your lovely raiding crew',count:123,elapsed:0,duration:8},settings:{volume:.22,muted:true,custom:{}}},location.origin)));
 await preview.waitForTimeout(3500);await preview.screenshot({path:path.join(out,'raid-worlds.png')});await preview.waitForTimeout(5000);assert.deepEqual(errors,[]);const video=preview.video();await context.close();await video.saveAs(path.join(out,'raid-worlds-motion.webm'));
 console.log(JSON.stringify({passed:true,uniqueWorlds:4,clearCenter:true,disconnectCleanup:true,maxFrameMs:Math.round(maxMs*100)/100,preview:path.join(out,'raid-worlds-motion.webm')}));
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
