const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let settings=null,selected=null,dirty=false,audioBusy=false,audioState=null,settingsStale=false;
if(window.parent!==window)document.body.classList.add('embedded');
function notice(message,error=false){$('#notice').textContent=message;$('#notice').className=error?'error':''}
let settingsWrite=false;
async function req(path,body){const write=body!==undefined&&['/event','/custom','/delete','/options'].includes(path);if(write&&settingsStale)throw Error('Settings changed in another window. Discard or reload your edits before saving.');if(write&&settingsWrite)throw Error('A save is already in progress.');const regions=write?[...document.querySelectorAll('#editor,.safety-controls,.workspace aside,#pause,#slots')]:[];if(write){settingsWrite=true;regions.forEach(e=>e.inert=true)}try{const r=await fetch(path,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}finally{if(write){settingsWrite=false;regions.forEach(e=>e.inert=false)}}}
function act(fn){return async()=>{try{await fn()}catch(e){notice(e.message,true)}}}
async function load(){settings=await req('/settings');settingsStale=false;$('#total').textContent=Object.keys(settings.config.events).length;$('#slots').value=settings.config.max_alerts;list();if(selected&&selected!=='new')edit(selected);if(typeof showPresentation==='function')showPresentation()}
function eventName(key,rule={}){return rule.title||({dragon_earth:'Mountain Dragon',dragon_fire:'Infernal Dragon',dragon_water:'Ocean Dragon',dragon_air:'Cloud Dragon',dragon_hextech:'Hextech Dragon',dragon_chemtech:'Chemtech Dragon',dragon_elder:'Elder Dragon'}[key])||key.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function list(){if(!settings)return;const query=$('#search').value.toLowerCase(),filter=$('#filter').value;$('#events').replaceChildren();for(const [key,rule]of Object.entries(settings.config.events)){const desc=settings.descriptions[key];if(!`${key} ${eventName(key,rule)} ${desc.description}`.toLowerCase().includes(query))continue;if(filter==='enabled'&&!rule.enabled||filter==='disabled'&&rule.enabled||filter==='custom'&&!key.startsWith('custom_')||filter==='possible'&&desc.kind!=='Possible correlation')continue;if(filter==='dragons'&&!key.startsWith('dragon')||filter==='combat'&&!/kill|death|assist|ace|health|combat|teamfight|escape|respawn/.test(key)||filter==='objectives'&&!/turret|inhibitor|baron|herald|grub|steal|objective/.test(key))continue;const b=document.createElement('button');b.className='event'+(selected===key?' selected':'');b.innerHTML=`<div><span class="dot ${rule.enabled?'on':''}"></span>${esc(eventName(key,rule))}</div><div class="meta">${rule.enabled?'On':'Off'} · ${rule.media?'Visual / sound assigned':'Placeholder'}${desc.kind==='Possible correlation'?' · Inferred':''}</div>`;b.onclick=()=>{if(dirty&&!confirm('Discard unsaved event changes?'))return;edit(key)};$('#events').append(b)}if(!$('#events').children.length)$('#events').innerHTML='<p class="empty">No matching events. Try another search or choose All events.</p>'}
function options(entries,value){return entries.map(([k,label])=>`<option value="${esc(k)}" ${String(value)===k?'selected':''}>${esc(label)}</option>`).join('')}
function triggerForm(tr){return `<div class="rulebox"><h3>Detection rule</h3><label for="trType">Watch</label><select id="trType">${options([['event','A Riot event'],['snapshot','A local player value changes']],tr.type)}</select><div id="trFields"></div></div>`}
function triggerFields(tr={}){const type=$('#trType').value;$('#trFields').innerHTML=type==='event'?`<label for="trEvent">Riot event name</label><input id="trEvent" list="eventNames" value="${esc(tr.event_name||'ChampionKill')}"><datalist id="eventNames">${settings.event_names.map(n=>`<option value="${n}">`).join('')}</datalist><label for="trScope">Whose event?</label><select id="trScope">${options([['any','Anyone / global'],['local_killer','You are the killer or recipient'],['local_victim','You are the victim'],['local_assister','You assisted'],['local_team','Your team']],tr.scope||'local_killer')}</select><div class="fields two"><div><label for="trField">Optional event field</label><select id="trField">${options(['','DragonType','KillStreak','Result','Stolen','AcingTeam'].map(k=>[k,k||'No field filter']),tr.field||'')}</select></div><div><label for="trEquals">Equals</label><input id="trEquals" value="${esc(tr.equals||'')}" placeholder="e.g. Elder, 5, Win, true"></div></div><p class="muted">Only fresh events trigger. Use a global filter for events without participants. A new event name must actually be emitted by Riot.</p>`:`<label for="trField">Your player value</label><select id="trField">${options(Object.entries(settings.fields),tr.field||'health_percent')}</select><div class="fields two"><div><label for="trOp">Condition</label><select id="trOp">${options([['crosses_below','Crosses below or reaches'],['crosses_above','Crosses above or reaches'],['increases_by','Increases by at least'],['decreases_by','Decreases by at least']],tr.operator||'crosses_below')}</select></div><div><label for="trValue">Threshold / change amount</label><input id="trValue" type="number" min="0" max="1000000" step="any" value="${tr.value??15}"></div></div><p class="muted">Compares consecutive samples, at most three seconds apart. Health includes death/respawn changes. Reconnecting establishes a baseline without triggering.</p>`}
function edit(key,isNew=false){for(const m of document.querySelectorAll('#editor video,#editor audio')){m.pause();m.removeAttribute('src');m.load()}selected=key;dirty=false;const r=isNew?{title:'My alert',enabled:true,priority:50,duration:6,cooldown:10,volume:.7,media:'',trigger:{type:'snapshot',field:'health_percent',operator:'crosses_below',value:15}}:settings.config.events[key];if(!r)return;const d=isNew?{kind:'Custom rule',description:'Choose a Riot event or a local snapshot condition below.'}:settings.descriptions[key];list();$('#editor').innerHTML=`
<div class="section-head"><div><span class="eyebrow">2. EDIT REACTION</span><h2>${esc(isNew?'New alert':eventName(key,r))}</h2></div><label class="check"><input id="enabled" type="checkbox" ${r.enabled?'checked':''}> Event on</label></div>
<details class="explanation"><summary>How this event is detected</summary><p>${esc(d.description)}</p><p class="muted">${esc(d.kind)} · checks every ${settings.config.poll_seconds}s. Event on/off applies to both media setups.</p></details>
${r.trigger?triggerForm(r.trigger):''}
<div class="media-preview" id="mediaPreview"></div>
<p class="muted">Preview here without sending anything to OBS. Changes apply only when you save.</p>
<details class="replace-media"><summary>Change visual or main sound</summary>
<label for="media">Choose a saved file</label><select id="media"><option value="">Text placeholder</option>${options(settings.library.map(a=>[a.path,a.name]),r.media)}${r.media&&!settings.library.some(a=>a.path===r.media)?`<option selected value="${esc(r.media)}">${esc(r.media)}</option>`:''}</select>
<label for="upload">Upload a file · up to 256 MB</label><input type="file" id="upload" accept=".webm,.mp4,.mov,.png,.jpg,.jpeg,.gif,.webp,.mp3,.wav,.ogg,.m4a">
</details>
<div id="companionMount"></div>
<div class="fields two"><div><label for="duration">Show for (seconds)</label><input id="duration" type="number" min="1" max="60" step="0.1" value="${r.duration}"></div><div><label for="gain">Reaction volume (%)</label><input id="gain" type="number" min="0" max="100" step="1" value="${Math.round(r.volume*100)}"></div></div>
<details class="advanced-event"><summary>Timing, priority & display name</summary>
<label for="title">Display name</label><input id="title" maxlength="100" value="${esc(r.title||'')}" placeholder="${esc(eventName(key))}">
<div class="fields"><div><label for="startTime">Start visual at (seconds)</label><input id="startTime" type="number" min="0" max="86400" step="0.1" value="${r.start_time||0}"></div><div><label for="priority">Priority (0–100)</label><input id="priority" type="number" min="0" max="100" value="${r.priority}"></div><div><label for="cooldown">Wait between repeats (seconds)</label><input id="cooldown" type="number" min="0" max="600" value="${r.cooldown}"></div></div>
<label class="check"><input id="loop" type="checkbox" ${r.loop?'checked':''}> Repeat visual until alert ends</label><p class="muted">Higher priority wins when alert slots are full. Reaction volume affects this event’s visual and companion sound before the OBS master fader.</p></details>
<div class="savebar"><button id="save" class="primary">Save event</button><button id="play">Save & test in OBS</button><button id="discard">Discard edits</button>${!isNew&&key.startsWith('custom_')?'<button id="delete" class="danger">Remove rule</button>':''}<span id="saveState" class="muted">Saved</span></div>`;
if(r.trigger){triggerFields(r.trigger);$('#trType').onchange=()=>{triggerFields();markDirty()}}
$('#editor').oninput=markDirty;$('#gain').addEventListener('input',()=>{for(const m of document.querySelectorAll('#mediaPreview video,#mediaPreview audio'))m.volume=Math.max(0,Math.min(1,Number($('#gain').value)/100))});$('#startTime').onchange=mediaPreview;$('#media').onchange=()=>{markDirty();mediaPreview()};$('#upload').onchange=act(async()=>{const uploadControl=$('#upload'),f=uploadControl.files[0];if(!f)return;if(f.size>256*1024*1024)throw Error('File exceeds 256 MB');notice('Uploading '+f.name+'…');const response=await fetch('/upload?name='+encodeURIComponent(f.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:f});const data=await response.json();if(!response.ok)throw Error(data.error);settings.library=data.library;if(!uploadControl.isConnected){notice('File uploaded to library. Choose an event to assign it.');return}$('#media').innerHTML='<option value="">Text placeholder</option>'+options(settings.library.map(a=>[a.path,a.name]),data.path);markDirty();mediaPreview();notice('Uploaded. Save the event to assign this file.')});
const save=async()=>{const rule={title:$('#title').value,enabled:$('#enabled').checked,media:$('#media').value,audio:$('#companionAudio')?.value||'',volume:Number($('#gain').value)/100,start_time:Number($('#startTime').value),loop:$('#loop').checked,duration:Number($('#duration').value),priority:Number($('#priority').value),cooldown:Number($('#cooldown').value),...readPoolDraft()};if($('#trType'))rule.trigger=$('#trType').value==='event'?{type:'event',event_name:$('#trEvent').value,scope:$('#trScope').value,field:$('#trField').value,equals:$('#trEquals').value}:{type:'snapshot',field:$('#trField').value,operator:$('#trOp').value,value:Number($('#trValue').value)};const oldKeys=new Set(Object.keys(settings.config.events));settings=await req(isNew?'/custom':'/event',{revision:settings.config.revision,key,rule});if(isNew)key=Object.keys(settings.config.events).find(k=>!oldKeys.has(k));dirty=false;$('#total').textContent=Object.keys(settings.config.events).length;edit(key);notice('Saved. Future alerts use these settings.');return key};
$('#save').onclick=act(save);$('#play').onclick=act(async()=>{if(settings.config.overlay_enabled===false)throw Error('Turn League alerts on before testing in OBS. Your edits have not been saved.');const k=await save();await req('/preview',{keys:[k]});notice('Playing saved alert in OBS. The monitor is silent.')});$('#discard').onclick=act(async()=>{dirty=false;if(isNew)selected=null;await load();if(!selected)edit(Object.keys(settings.config.events)[0]);notice('Loaded saved settings.')});if($('#delete'))$('#delete').onclick=act(async()=>{if(!confirm('Remove this custom rule? Its media stays in your library.'))return;settings=await req('/delete',{key,revision:settings.config.revision});selected=null;dirty=false;$('#total').textContent=Object.keys(settings.config.events).length;list();$('#editor').innerHTML='<div class="empty">Rule removed. Choose another event.</div>'});mediaPreview()}
function markDirty(){dirty=true;if($('#saveState'))$('#saveState').textContent='Unsaved changes'}
function mediaPreview(){const path=$('#media').value,root=$('#mediaPreview');for(const m of root.querySelectorAll('video,audio')){m.pause();m.removeAttribute('src');m.load()}root.replaceChildren();if(!path){root.textContent='Hello World · '+($('#title').value||'event');return}const ext=path.split('.').pop().toLowerCase();const kind=['png','jpg','jpeg','gif','webp'].includes(ext)?'img':['mp3','wav','ogg','m4a'].includes(ext)?'audio':'video';const m=document.createElement(kind);m.src='/asset?path='+encodeURIComponent(path);if(kind!=='img'){m.controls=true;m.preload='metadata';m.volume=Math.max(0,Math.min(1,Number($('#gain').value)/100));const start=Math.max(0,Number($('#startTime').value)||0);m.onloadedmetadata=()=>{if(m.isConnected&&Number.isFinite(m.duration))m.currentTime=Math.min(start,Math.max(0,m.duration-.1))}}m.onerror=()=>{if(!m.isConnected)return;root.textContent='Cannot preview this file. Check that it exists and uses a supported browser codec.'};root.append(m)}
$('#search').oninput=list;$('#filter').onchange=list;$('#new').onclick=()=>{if(dirty&&!confirm('Discard unsaved changes?'))return;edit('new',true)};
$('#clear').onclick=act(()=>req('/clear',{}));$('#demo').onclick=act(()=>req('/preview',{keys:['pentakill','objective_steal','ace','level_up','minions_spawning']}));
$('#pause').onclick=act(async()=>{settings=await req('/options',{revision:settings.config.revision,paused:!settings.config.paused});notice(settings.config.paused?'Automatic alerts paused. Previews still work.':'Automatic alerts resumed.')});
$('#slots').onchange=act(async()=>{settings=await req('/options',{revision:settings.config.revision,max_alerts:Number($('#slots').value)});notice('Slot limit saved.')});
let audioRevision=0;
$('#master').oninput=()=>{audioRevision++;audioBusy=true;$('#masterValue').textContent=Number($('#master').value).toFixed(1)+' dB'};
async function saveAudio(body){audioRevision++;audioBusy=true;$('#master').disabled=true;$('#mute').disabled=true;try{audioState=await req('/volume',body);showAudio(audioState)}finally{audioBusy=false}}
$('#master').onchange=act(()=>saveAudio({db:Number($('#master').value)}));
$('#mute').onclick=act(()=>saveAudio({muted:!audioState.muted}));
function showAudio(v){$('#master').disabled=false;$('#mute').disabled=false;$('#master').value=Math.max(-60,v.db);$('#masterValue').textContent=(v.db<=-100?'−∞':v.db.toFixed(1))+' dB';$('#mute').textContent=v.muted?'Unmute':'Mute';$('#audioStatus').textContent=v.muted?'Muted in OBS':'Connected · reads OBS directly; no startup volume reset'}
async function pollAudio(){const revision=audioRevision;if(!audioBusy){try{const v=await req('/volume');if(!audioBusy&&revision===audioRevision){audioState=v;showAudio(v)}}catch(e){if(!audioBusy&&revision===audioRevision){$('#audioStatus').textContent=e.message;$('#master').disabled=true;$('#mute').disabled=true}}}setTimeout(pollAudio,1200)}
async function poll(){const polledRevision=settings?.config.revision;try{const d=await req('/state');$('#connection').textContent=d.overlay_enabled===false?'League alerts OFF':d.paused?'Automatic alerts paused':d.status;$('#activeCount').textContent=d.alerts.length+' / '+(settings?.config.max_alerts||3)+' active';$('#pause').textContent=d.paused?'Resume automatic alerts':'Pause automatic alerts';$('#history').className='';$('#history').innerHTML=d.history.slice().reverse().map(a=>`<div class="entry"><span>${a.time?new Date(a.time*1000).toLocaleTimeString():''}</span><div><strong>${esc(a.title||a.key)}</strong><br><span class="muted">${esc(a.detail)}</span></div><span>${esc(a.result||'Detected')}</span></div>`).join('')||'<p>No recent detections. Use a preview or start a game.</p>';$('#metrics').textContent=JSON.stringify({game:d.metrics,errors:d.media_errors},null,2);if(settings&&settings.config.revision===polledRevision&&!settingsWrite&&d.revision!==settings.config.revision&&!settingsStale){settingsStale=true;if(!dirty&&!(typeof layoutDraft!=='undefined'&&layoutDraft))await load();else notice('Settings changed in another window. Discard or reload your event and layout edits before saving.',true)}}catch{$('#connection').textContent='Alert service offline'}setTimeout(poll,700)}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
function assetDropEditor(){
  const upload=$('#upload');if(!upload)return;
  const zone=document.createElement('div');zone.className='asset-drop';zone.tabIndex=0;
  zone.textContent='Drop a media file here · preview it, then Save event';
  $('#mediaPreview').after(zone);
  const gallery=document.createElement('div');gallery.className='asset-gallery';const library=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Choose from library · '+settings.library.length+' files';library.append(summary,gallery);zone.after(library);
  for(const asset of settings.library){
    const tile=document.createElement('button');tile.type='button';tile.className='asset-tile';tile.draggable=true;
    const ext=asset.path.split('.').pop().toLowerCase();
    if(['png','jpg','jpeg','gif','webp'].includes(ext)||/^media\/meme-[a-z0-9-]+\.mp4$/.test(asset.path)){
      const img=document.createElement('img');img.loading='lazy';img.alt='';img.src=asset.path.startsWith('media/meme-')&&ext==='mp4'?'/meme-thumbnails/'+asset.path.slice(11,-4)+'.jpg':'/asset?path='+encodeURIComponent(asset.path);tile.append(img);
    }else{const icon=document.createElement('span');icon.className='asset-icon';icon.textContent=['mp3','wav','ogg','m4a'].includes(ext)?'♫':'▶';tile.append(icon)}
    const label=document.createElement('span');label.textContent=asset.name;tile.append(label);
    tile.ondragstart=e=>e.dataTransfer.setData('application/x-league-asset',asset.path);
    tile.onclick=()=>{$('#media').innerHTML='<option value="">Text placeholder</option>'+options(settings.library.map(a=>[a.path,a.name]),asset.path);markDirty();mediaPreview();notice('File selected. Preview it, then Save event to apply.')};
    gallery.append(tile);
  }
  zone.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();upload.click()}};
  zone.ondragover=e=>{e.preventDefault();zone.classList.add('drag-over')};
  zone.ondragleave=()=>zone.classList.remove('drag-over');
  zone.ondrop=async e=>{
    e.preventDefault();zone.classList.remove('drag-over');const eventKey=selected;
    try{
      let path=e.dataTransfer.getData('application/x-league-asset');
      if(!path){
        if(e.dataTransfer.files.length!==1)throw Error('Drop one file per event.');
        const file=e.dataTransfer.files[0];if(file.size>256*1024*1024)throw Error('File exceeds 256 MB');
        notice('Uploading '+file.name+'…');
        const response=await fetch('/upload?name='+encodeURIComponent(file.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});
        const data=await response.json();if(!response.ok)throw Error(data.error||'Upload failed');
        settings.library=data.library;path=data.path;
      }
      if(selected!==eventKey||!zone.isConnected){notice('File added to the library. Select the intended event to assign it.');return}
      if(!settings.library.some(a=>a.path===path))throw Error('Choose a file from this media library.');
      $('#media').innerHTML='<option value="">Text placeholder</option>'+options(settings.library.map(a=>[a.path,a.name]),path);
      markDirty();mediaPreview();notice('File selected. Preview it, then Save event to apply.');
    }catch(error){notice(error.message,true)}
  };
}
const editWithoutDrop=edit;
edit=function(...args){editWithoutDrop(...args);assetDropEditor()};
load().then(()=>{edit(Object.keys(settings.config.events)[0]);poll();pollAudio()}).catch(e=>notice(e.message,true));
