// Presentation controls share the event editor's revision checks and media library.
let layoutDraft=false;
const layoutKeys=['x','y','width','height'];
function layoutValues(){return Object.fromEntries(layoutKeys.map(k=>[k,Number($('#layout_'+k).value)]))}
function setLayout(l){for(const k of layoutKeys)$('#layout_'+k).value=Math.round(l[k]);drawLayout()}
function drawLayout(){const l=layoutValues(),b=$('#layoutBox');Object.assign(b.style,{left:l.x/19.2+'%',top:l.y/10.8+'%',width:l.width/19.2+'%',height:l.height/10.8+'%'});$('#layoutStatus').textContent=layoutDraft?'Unsaved size & position · Save to apply':'Saved size & position';$('#layoutSave').disabled=!layoutDraft;$('#layoutUndo').disabled=!layoutDraft}
function showPresentation(){if(!settings)return;const c=settings.config;$('#overlayToggle').textContent=c.overlay_enabled===false?'League alerts: OFF · turn on':'League alerts: ON · turn off';$('#overlayToggle').setAttribute('aria-pressed',String(c.overlay_enabled!==false));$('#presentation').value=c.presentation||'memes';$('#presentationStatus').textContent='Active: '+(c.presentation==='personal'?'My setup':'Meme pack')+' · edits are saved separately';if(!layoutDraft)setLayout(c.layout||{x:1305,y:86,width:557,height:248})}
$('#overlayToggle').onclick=act(async()=>{settings=await req('/options',{revision:settings.config.revision,overlay_enabled:settings.config.overlay_enabled===false});showPresentation();notice(settings.config.overlay_enabled?'League alerts on.':'League alerts off. All playing League media stopped.')});
$('#presentation').onchange=act(async()=>{const target=$('#presentation').value;if(dirty||layoutDraft){showPresentation();throw Error('Save or discard your event and layout edits before switching setups.')}try{settings=await req('/options',{revision:settings.config.revision,presentation:target})}finally{showPresentation()}if(selected)edit(selected);notice('Switched setup. Your previous media and layout are retained; volumes are unchanged.')});
for(const k of layoutKeys)$('#layout_'+k).oninput=()=>{layoutDraft=true;drawLayout()};
$('#layoutSave').onclick=act(async()=>{settings=await req('/options',{revision:settings.config.revision,layout:layoutValues()});layoutDraft=false;showPresentation();notice('Size and position saved for this setup.')});
$('#layoutUndo').onclick=()=>{layoutDraft=false;showPresentation()};
$('#layoutFull').onclick=()=>{layoutDraft=true;setLayout({x:0,y:0,width:1920,height:1080})};
const box=$('#layoutBox'),canvas=$('#layoutCanvas'),handle=$('#layoutHandle');let dragging=null;
box.onpointerdown=e=>{if(e.button!==0)return;dragging={x:e.clientX,y:e.clientY,l:layoutValues(),resize:e.target===handle};box.setPointerCapture(e.pointerId);e.preventDefault()};
box.onpointermove=e=>{if(!dragging)return;const scale=1920/canvas.clientWidth,l=dragging.l,dx=(e.clientX-dragging.x)*scale,dy=(e.clientY-dragging.y)*scale;layoutDraft=true;setLayout(dragging.resize?{...l,width:Math.max(32,Math.min(1920-l.x,l.width+dx)),height:Math.max(32,Math.min(1080-l.y,l.height+dy))}:{...l,x:Math.max(0,Math.min(1920-l.width,l.x+dx)),y:Math.max(0,Math.min(1080-l.height,l.y+dy))})};
box.onpointerup=box.onpointercancel=()=>dragging=null;
box.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const l=layoutValues(),step=e.shiftKey?10:1,dx=e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,dy=e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0;layoutDraft=true;setLayout(e.target===handle?{...l,width:Math.max(32,Math.min(1920-l.x,l.width+dx)),height:Math.max(32,Math.min(1080-l.y,l.height+dy))}:{...l,x:Math.max(0,Math.min(1920-l.width,l.x+dx)),y:Math.max(0,Math.min(1080-l.height,l.y+dy))})};
window.addEventListener('beforeunload',e=>{if(layoutDraft){e.preventDefault();e.returnValue=''}});
function companionEditor(){const rule=settings.config.events[selected]||{},section=document.createElement('details');section.open=!!rule.audio;section.innerHTML='<summary>Add a companion sound'+(rule.audio?' · assigned':' · optional')+'</summary><p class="muted">Play a sound alongside this visual, using the event clip volume and OBS master fader. Sound stops when the alert ends. Choose No companion sound to remove it.</p><select id="companionAudio" aria-label="Companion sound"></select><label for="audioUpload">Add audio (MP3, WAV, OGG, M4A)</label><input id="audioUpload" type="file" accept=".mp3,.wav,.ogg,.m4a"><div id="audioDrop" class="asset-drop" tabindex="0" role="button">Drop a companion audio file here · Save event to apply</div><audio id="audioPreview" controls preload="none"></audio>';
$('#companionMount').append(section);
const fill=value=>{$('#companionAudio').innerHTML='<option value="">No companion sound</option>'+options(settings.library.filter(a=>/\.(mp3|wav|ogg|m4a)$/i.test(a.path)).map(a=>[a.path,a.name]),value);if(value&&!Array.from($('#companionAudio').options).some(o=>o.value===value))$('#companionAudio').add(new Option(value,value,true,true));preview()};
const preview=()=>{const a=$('#audioPreview'),path=$('#companionAudio').value;a.pause();a.volume=Number($('#gain').value)/100;a.hidden=!path;if(path)a.src='/asset?path='+encodeURIComponent(path);else a.removeAttribute('src')};
$('#companionAudio').onchange=()=>{markDirty();preview()};
const assignAudio=async f=>{if(!f)return;if(!/\.(mp3|wav|ogg|m4a)$/i.test(f.name))throw Error('Choose MP3, WAV, OGG or M4A audio.');if(f.size>256*1024*1024)throw Error('File exceeds 256 MB');const r=await fetch('/upload?name='+encodeURIComponent(f.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:f}),data=await r.json();if(!r.ok)throw Error(data.error);settings.library=data.library;if(!section.isConnected){notice('Audio uploaded to library. Choose the intended event to assign it.');return}fill(data.path);markDirty();notice('Audio ready. Save event to apply.')};$('#audioUpload').onchange=act(()=>assignAudio($('#audioUpload').files[0]));const drop=$('#audioDrop');drop.onclick=()=>$('#audioUpload').click();drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();drop.click()}};drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag-over')};drop.ondragleave=()=>drop.classList.remove('drag-over');drop.ondrop=async e=>{e.preventDefault();drop.classList.remove('drag-over');try{if(e.dataTransfer.files.length!==1)throw Error('Drop one audio file.');await assignAudio(e.dataTransfer.files[0])}catch(error){notice(error.message,true)}};$('#gain').addEventListener('input',()=>{$('#audioPreview').volume=Math.max(0,Math.min(1,Number($('#gain').value)/100))});fill(rule.audio||'')}
const editBeforeCompanion=edit;edit=function(...args){editBeforeCompanion(...args);companionEditor()};
if(settings){showPresentation();if(selected)companionEditor()}
